### ISSUE TITLE
report bugs

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1000]
WHISPers is getting a lot of attention right now because we have a big rabbit die off happening in the southwest, and that shed light on a couple of issues with the reports...

If you go to the home page on the live site and then click on popular searches and then run the top one (rabbit hemorrhagic disease in 2020)...

You'll see that the "# of Species Affected" is tallying funny for both the search summary report and the event details report. It's not tallying the unique number of species across locations (per the metadata). I think this used to work fine?

For the event details report, the comment source is getting clipped off on the right side of the report.
![image](https://user-images.githubusercontent.com/49287076/80248569-c84b7b00-8635-11ea-8449-1cd2d32df4da.png)

Thanks!

**Comment by BlakeDraper** [comment]
Issue #1000!

**Comment by BlakeDraper** [comment]
Published in v2.14.5
