### ISSUE TITLE
Comment source is being clipped 

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#1001]
separated out from issue https://github.com/USGS-WiM/whispers/issues/1000

**Comment by JChipault** [comment]
comment source fits on the page now (yay!); however, if I do an event details report of 170069 from the test site, it doesn't transfer over the really long comment but instead gives me a blank page:
![image](https://user-images.githubusercontent.com/49287076/80640139-9f0d5f00-8a28-11ea-855d-89b2984d2f1e.png)

**Comment by lprivette** [comment]
Holy cow that's an essay not a comment! ha. 

I'm looking into what are options will be here. That's a lot of characters for a table so I'll try to figure out how our pdf generator handles it.

**Comment by lprivette** [comment]
also pulling this out into a separate issue: https://github.com/USGS-WiM/whispers/issues/1009

**Comment by BlakeDraper** [comment]
Published in v2.14.5
