### ISSUE TITLE
private fields viewable outside of org (and notifications sent with private fields)

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1005]
I logged in as abilenetest and turned on notifications for All Events.

I then logged in as jchipault and made a lot of changes to 170880 (an event owned by jchipault in org of NWHC with no collaborators).

When the standard notifications got issued, I logged in as abilenetest and noted that details about non-public fields (e.g., lat/long, location name) were provided in the notification. 

![image](https://user-images.githubusercontent.com/49287076/80511716-17e5bb80-8942-11ea-8ce4-e683df883489.png)

But it was weird that abilenetest didn't have an Org listed at the top of the dashboard (see screenshot above), so I checked the API and there's an org associated with that user in the browseable API.

![image](https://user-images.githubusercontent.com/49287076/80512376-04872000-8943-11ea-81e9-2f9feea47395.png)

I then just went right to event details page of 170880 as abilenetest and I could see these details. So I was thinking maybe it's just because the org for abilenetest is somehow not assigned??

But then I logged in as neilpartner (with org of Woods Hole) and neilpartner can see details of event 170880:

![image](https://user-images.githubusercontent.com/49287076/80512180-b7a34980-8942-11ea-9bbc-be4a6a84c0d1.png)

What am I missing? Shouldn't these private fields be blank for users who aren't collaborators and are outside the org of NWHC? And, thus it follows, that users outside of NWHC wouldn't get notifications about updates to fields that they can't access.

**Comment by JChipault** [comment]
I gotta jump on a 2p call... but Neil reminds me that I was possibly logged into the API still when I looked at the event details page and saw private data. Will re-check that soon! Still an issue with getting private data showing up in notifications though....

**Comment by JChipault** [comment]
Ok, yup, Neil called it, I could see details on the event details page only because I was still logged in on the API. Sorry about that. Seems like the lingering issues are:

1) Private info in a notification
2) Org not displaying in the dashboard

**Comment by JChipault** [comment]
@aaronstephenson tagging you because this should perhaps go in the Django queue

**Comment by BlakeDraper** [comment]
@JChipault I am going to create a new issue in the backend repository to capture the private fields in notifications issue. 

I have made a small change to fix the org not displaying issue - available next release.

**Comment by BlakeDraper** [comment]
Published in v2.14.5
