### ISSUE TITLE
Saved search - number affected

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#1008]
Saved search is not saving Number Affected value when provided.  For example if I save a search that searches for Event Diagnosis = 'Botulism Type C' and Number Affected >= 1,000, it appears only Event Diagnosis = 'Botulism Type C' is saved with that search.

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by BlakeDraper** [comment]
Done and published in v2.14.6.
