### ISSUE TITLE
read/write collaborator can't make additional service request comments

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1043]
a read/write collaborator can't make additional comments in the service request area. So if they put in an initial service request and then NWHC comments back, the collaborator can't comment back to NWHC (the "add comment" button is greyed out for write collaborators). 

**To Reproduce**
1. log in as a user that is a write collaborator on an event and go to that event
2. click on "add service request" and note that you can add an initial request with associated comments. no problem
3. click back in the service request area and note that the "add comment" button associated with the request you just made is greyed out. problem = that button should be blue and active

Here's an image showing what abilenetest sees in an incomplete event... they can comment at the event level (button is blue) but can't within the request area (button is grey)
![image](https://user-images.githubusercontent.com/49287076/84187028-0f12fa00-aa57-11ea-928a-9ebbc63deff2.png)

**Comment by JChipault** [comment]
I was working in event 170873 as abilene test. Here's a screen shot of a request that abilenetest submitted but showing that they can't make any additional comments:
![image](https://user-images.githubusercontent.com/49287076/84187548-cc9ded00-aa57-11ea-82c1-7483d1ae95cc.png)

**Comment by BlakeDraper** [comment]
Fixed and done in code. The wrong permission check (destroy) was applied to the `[disabled]` property on the button.

**Comment by BlakeDraper** [comment]
Done with v2.15.4.
