### ISSUE TITLE
UI changes to requiring email verification before activating issues

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1048]
This issue is to implement the user interface changes necessary to requiring that users verify their email address before being activated. The companion backend issue is USGS-WiM/whispersservices_django#386.

TODO:
- [x] Handle the email verification URL and call the `/confirm_email/` user service to confirm the email
- [x] display a success message to the user when the email address is verified
- [x] notify user that they should check their email to a verification URL to click, also should clearly display the email address to which the verification URL has been sent
  - and a reminder to check Junk folder
- [x] handle the case where the email verification fails (for example, URL token is expired)
- [x] handle the case user tries to login but hasn't verified their email yet and hence aren't active yet

**Comment by machristie** [comment]
I tried displaying a Snackbar message when the user successfully verifies their email address. This "works" but immediately after it is replaced by a "No events match your selected criteria. Please try again." message, mostly likely because this is my local instance and has no events at all.

I switched back to a simple text message in the login dialog. Unfortunately, there's not a good Angular Material component for this case, since the Material Banner component hasn't been implemented yet: https://github.com/angular/components/issues/11452

**Comment by BlakeDraper** [comment]
Published in v2.16.0.
