### ISSUE TITLE
Add an "I am not a robot" check to the user registration process

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1050]
To defend against spam accounts, we want to add an "I am not a robot" check to the user registration process. This will use the reCAPTCHA v2 Google service. Something like this:

![newCaptchaAnchor](https://user-images.githubusercontent.com/904957/88816234-300be780-d18a-11ea-8a99-fe5a895ed091.gif)

Using the reCAPTCHA service is free but requires registration to get a site key and secret.

I've done some initial research on components that can be used to implement this:
- https://www.npmjs.com/package/ng-recaptcha - an Angular component for the UI. This creates the reCAPTCHA response. It requires the site key.
- https://pypi.org/project/drf-recaptcha/ - a Django REST Framework serializer that can verify the reCAPTCHA response. The reCAPTCHA response will be sent as part of the user registration request and this serializer will verify it on the backend with the reCAPTCHA REST API (see https://developers.google.com/recaptcha/docs/verify for more details). This will need to be integrated into the whispersservices_django backend.

Questions:
- [x] Maybe bind the reCAPTCHA to the user registration submit button, invisibly, instead of having the checkbox? The reCAPTCHA response is only valid for 2 minutes. If the user takes more than 2 minutes from checking the "I am not a robot" checkbox until clicking submit, verifying the reCAPTCHA response will fail and the user will have to do it again.
- [x] The reCAPTCHA service requires registering to obtain a site id and a secret key. How should these be obtained for the production site and how should they be configured?

**Comment by machristie** [comment]
Regarding the 2 minute timeout of the reCAPTCHA response, Neil, Kim and Jenny and I decided to keep the reCAPTCHA checkbox visible and put it as far down the form as possible so it is the last thing the user checks before clicking Submit.

**Comment by machristie** [comment]
From an email I sent to Neil about registering for an API key pair:

----
Here are the details for registering a reCAPTCHA API key pair:

* the main documentation is here: https://developers.google.com/recaptcha/intro
* here is the page where you can register for an API key pair: http://www.google.com/recaptcha/admin
* when you register for the API key pair:
  * select the reCAPTCHA type as v2, "I am not a robot" checkbox
  * add the whispers domains, for example "whispers.usgs.gov" and "whispers.usgs.gov", etc.
  * I think the rest of the form is self-explanatory, but let me know if you have any questions
* I couldn't find any information on lifetime or renewal of API key pairs, so I assume it is perpetual
* Google describes the reCAPTCHA service as a "free service". In the FAQ it does mention rate limits:

	> If you wish to make more than 1k calls per second or 1m calls per month, you must use reCAPTCHA Enterprise or fill out this form and wait for an exception approval.

   But I doubt WHISPers would ever bump up against those limits.

**Comment by machristie** [comment]
Still to do:
- [ ] configurable site key in Angular environment
- [ ] reposition reCAPTCHA checkbox to be as far down and as close to the Submit button as possible
- [ ] test handling of reCAPTCHA validation errors

**Comment by BlakeDraper** [comment]
Published in v2.16.0.
