### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1053]
Allow users to reset their password. Here are the steps:
1. User clicks a *Forgot Password?* link on the login form.
2. The user is presented with a Reset Password Request dialog.
3. The user must supply their username and then submit.
4. On the backend, a reset password token is generated and emailed to the user.
5. When the user clicks on the link in the email, the Reset Password dialog will be displayed.
6. The user can then supply their new password and confirm it and then submit.
7. The backend accepts the request with the new password and the token. If the token is valid the user's password is updated.

TODO
- [x] "Forgot password?" link on the login dialog under password field
- [x] Request password reset dialog
- [x] Handle link with password reset token, similar to email verification
- [x] Password reset dialog - requires new password and confirmation
- [x] Refactor out component for password/confirmPassword form fields with validation, to be used in user-registration and reset-password components
  - [x] factor out component
  - [x] update user-registration form
- [x] forgot password button as link instead? Also, instead of putting it in the hint field, can we put it somewhere so that it always displays?
- [x] Testing: verify that password reset dialog enforces password business rules
- [x] Testing: verify that password reset dialog handles case where token has expired

Questions:
- [ ] Allow user to supply email address if they have forgotten their username?

**Comment by machristie** [comment]
Generally browsers ignore autocomplete="off" for login fields, but there's a relatively new autocomplete option `autocomplete="new-password"` that can be used as a hint to the browser that the user is supplying a new password. I'm going to use that for the reset password form.

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields

**Comment by machristie** [comment]
The implementation is essentially done now. The branch I've put the changes on is based on the email-verification branch so I'll wait until that one (#1049) is merged before opening up a new PR.

**Comment by BlakeDraper** [comment]
Published in v2.16.0.
