### ISSUE TITLE
Home page layout changes

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1057]
Main changes:

- [x] move the search fields on to the home page instead of in the search dialog
- [x] display for each search field a dismissable [chip](https://v7.material.angular.io/components/chips/overview)
  - only display the first 3 or so values. If more than 3, add a chip that says "and N more" where N is the additional criteria values selected past 3.
- [x] update affected count and dates to dismissable chips
- [x] 'Event Completion' is a boolean field. To aid saving a search the UI is designed so you can select complete and incomplete events, but selecting both of these is equivalent to selecting neither. Investigate whether we can just not show anything for this field when neither are selected.
- [x] Three new buttons at the bottom - SEARCH, CLEAR and DEFAULT
  - DEFAULT resets to the default search (all events of past 28 days)
  - SEARCH should be a contained, high-emphasis button
  - CLEAR search results in deactivating SEARCH button since at least one criteria must be selected (see below for more details)
  - the buttons should always be visible with the search form scrollable
- [x] Below search buttons, the export CSV and PDF report buttons (moved from between the map and data table)
- [x] text updates
  - `thru` -> `through`
  - `Event completion` -> `Record status`
- [x] `SAVE SEARCH CRITERIA` button - popup remove title, header = *Save the current search criteria*
- [x] search fields
  - clear the text entry line after selection is made or focus is changed
  - remove the grey dividing line between accordion header and body
  - change drop down text label from "Add" to "Select". For example, *Select Species"
  - for long names in drop down that are ellipsized, add a hover to reveal complete name, like *Create Event -> Contact Organization*
- [x] user must select at least one criteria. If the search results are too many, an error message should appear in the search form (currently, a toast message is used, but something more prominent in the search form would be better).
  - **In the wireframes we had this at the top of the search form, but I think it might be better below the search buttons (we moved the search buttons to the bottom of the form)**
  - [x] add validation message to search dialog as well
- [x] styling the search form to layout well when in the sidebar, but also needs to layout well in dialog when used from the dashboard
- [x] change "Your Query result is too large" error message from a toast message to an error message displayed near the search buttons
- [x] ~~fix exporting the data as CSV~~ fixed already on the main branch
- [x] save search criteria button alignment
- [x] update icon of report button on the event details page to use same pdf one
- [ ] use a grey placeholder in date range pill when no start or end date

---
**Note: these changes were dropped from the development schedule at this time because they were lower priority, except for the event id search which I've moved to a separate issue: #1083.**

Lower priority changes, in order:

- [ ] add event id search - currently not supported in the backend, but adding an additional field shouldn't be too hard https://github.com/USGS-WiM/whispersservices_django/blob/notifications/whispersservices/views.py#L3303
  - allow users to enter numeric ids, possible comma separated
- [ ] share search criteria button - displays popup with a URL that user can copy to send that search to another user
- [ ] Collapse search window to the left (to display more map)
- [ ] allow multiple selections in drop down
- [ ] focus when open search field. Currently users need to expand a search field (with an accordion like UI) and then click in the text field to type or search for a value to search on
- [x] invalidate free text that doesn't match any entry. When user types in something to the searchable drop down, if nothing is matched, the field should be invalidated and the form should be invalidated and submit should be disabled.
  - or, as described above, just clear out the field when focus is removed

**Comment by machristie** [comment]
Programmatically triggering focus on the autocomplete text input when the accordion panel is opened is proving tricky.  I found the following issue that seems most related but everything I've tried there hasn't worked: https://github.com/angular/components/issues/3106

**Comment by machristie** [comment]
In reviewing the wireframes, I found a couple more small main changes that I had missed. I've added them above. I also discovered that downloading data doesn't work when I'm not logged in, so I'll investigate that and fix it too.

**Comment by BlakeDraper** [comment]
@machristie the failure to download when not logged in was addressed in a recent commit and release to dev and test: https://github.com/USGS-WiM/whispers/releases/tag/v2.15.7 so probably fine to leave that one, and will be fixed when all is merged.

**Comment by machristie** [comment]
@BlakeDraper thanks, I'll just leave that one alone

**Comment by BlakeDraper** [comment]
Published in v2.16.0.
