### ISSUE TITLE
If enter lat/long in wrong format, event won't save even when lat/long cleared out

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1059]
Running into dead end when creating an event and have lat/long in the wrong format initially, e.g., :
![image](https://user-images.githubusercontent.com/49287076/94830670-6dcafd80-03d1-11eb-9adc-525b581cda60.png)

This greys out the "Save Event" button, appropriately so. So then the user notices the red text saying "Invalid latitude" and "Invalid longitude" and clears out those fields altogether, so both lat and long are null. Lat and Long are not required fields so user is now able to "Save Event"

Buuuuut... then user gets this toast error message:
Error. Event not Submitted. Error message: {"non_field_errors":["latitude and longitude must be in decimal degrees and represent a point in a country."]}

Should be able to save event with lat and long null. Was not able to save event and had to close out and lose all data entered.

Happened in both firefox and chrome, and in both live and test

Here's my form values when I did this:
Form Status: VALID

 {
  "event_reference": "",
  "event_type": "1",
  "complete": false,
  "public": false,
  "staff": null,
  "event_status": "1",
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [
    2
  ],
  "new_service_request": {
    "request_type": 0,
    "new_comments": []
  },
  "new_event_diagnoses": [],
  "new_comments": [],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "",
      "start_date": "2020-09-29",
      "end_date": null,
      "country": "30",
      "administrative_level_one": 51,
      "administrative_level_two": 3055,
      "latitude": "",
      "longitude": "",
      "land_ownership": "7",
      "gnis_name": "",
      "gnis_id": "",
      "site_description": "",
      "history": "test test test - not a real event",
      "environmental_factors": "",
      "clinical_signs": "",
      "comment": "",
      "new_location_species": [
        {
          "species": 875,
          "population_count": null,
          "sick_count": null,
          "dead_count": 1,
          "sick_count_estimated": null,
          "dead_count_estimated": null,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": []
        }
      ],
      "new_location_contacts": []
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": [],
  "quality_check": null
}

**Comment by BlakeDraper** [comment]
Fixed and released in v2.15.5
