### ISSUE TITLE
Cannot delete event group in whispersprod.cr

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#1070]
Dashboard event groups, delete selected event group --> pulls up weird popup and makes it so I can't do anything (site totally frozen) unless I hit my browser's back button. When navigate back to event group tab see that group I tried to delete is still there.

![image](https://user-images.githubusercontent.com/38669574/96274731-7b1de580-0f96-11eb-8e50-e398dc5c9b1f.png)

**Comment by BlakeDraper** [comment]
This appears fixed in the current test services (probably a side effect of another bug fix earlier). @nbaertlein please test this again on the test app (prod will still have the error until it is updated).
