### ISSUE TITLE
Service request notification on whisperstest.cr

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#1074]
I've updated the table whispers_configuration madison_epi_user from 11 to 1, but service request notices are still being sent to user 11.  Both from create event and event details.  A couple worked after the table update (sent to user 1), but seems all are being sent to 11 again.

From notifications table:
select a.id, a.event_id, a.created_date, a.client_page, a.source, a.recipient_id, b.email as recipient_email,
a.subject
from public.whispers_notification a
	left join public.whispers_user b on a.recipient_id = b.id
where subject like '%Services%Request%'
and created_date = '2020-10-16'
order by id desc;

id | event_id | created_date | client_page | source | recipient_id | recipient_email | subject
-- | -- | -- | -- | -- | -- | -- | --
8818 | 170928 | 10/16/2020 | event | nbaertlein | 11 | nbaertlein+id11@usgs.gov | TEST. TEST. Diagnostic and   Consultative Services Request: Event 170928
8814 | 170926 | 10/16/2020 | event | nbaertlein | 11 | nbaertlein+id11@usgs.gov | TEST. TEST. Consultative Services   ONLY Request: Event 170926
8813 | 170873 | 10/16/2020 | event | abilenetest | 11 | nbaertlein+id11@usgs.gov | TEST. TEST. Diagnostic and   Consultative Services Request: Event 170873
8807 | 170927 | 10/16/2020 | event | nbaertlein | 11 | nbaertlein+id11@usgs.gov | TEST. TEST. Diagnostic and   Consultative Services Request: Event 170927
8803 | 170927 | 10/16/2020 | event | nbaertlein | 11 | nbaertlein+id11@usgs.gov | TEST. TEST. Diagnostic and   Consultative Services Request: Event 170927
8802 | 170927 | 10/16/2020 | event | nbaertlein | 11 | nbaertlein+id11@usgs.gov | TEST. TEST. Diagnostic and   Consultative Services Request: Event 170927
8801 | 170919 | 10/16/2020 | event | nbaertlein | 11 | nbaertlein+id11@usgs.gov | TEST. TEST. Diagnostic and   Consultative Services Request: Event 170919
8800 | 170919 | 10/16/2020 | event | nbaertlein | 11 | nbaertlein+id11@usgs.gov | TEST. TEST. Consultative Services   ONLY Request: Event 170919
8799 | 170926 | 10/16/2020 | event | jchipault | 1 | whispers@usgs.gov | TEST. TEST. Consultative Services   ONLY Request: Event 170926
8798 | 170919 | 10/16/2020 | event | nbaertlein | 11 | nbaertlein+id11@usgs.gov | TEST. TEST. Diagnostic and   Consultative Services Request: Event 170919
8797 | 170920 | 10/16/2020 | event | jchipault | 1 | whispers@usgs.gov | TEST. TEST. Diagnostic and   Consultative Services Request: Event 170920
8744 | 170920 | 10/16/2020 | event | jchipault | 11 | nbaertlein+id11@usgs.gov | TEST. TEST. Diagnostic and   Consultative Services Request: Event 170920

**Comment by aaronstephenson** [comment]
Hi Neil. These configuration values are read into Django at start-up. The app won't read any changes to those values unless you restart the app. In this case, that means restarting the Apache daemon (and Celery for good measure, too, since many of these config values affect that module).

On the server, it's just a matter of issuing these two commands in the terminal:
```
sudo systemctl restart httpd
sudo systemctl restart celeryd
```

I will go ahead and do the restarts now for this case.
