### ISSUE TITLE
Collaborator Alert checkboxes disappear

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1077]
It's possible that this is not a bug, but it does render a function useless to me unless I know to resize my browser window

**Describe the bug**
If my browser window is maximized on either my laptop or my external screen, I cannot use the Collaborator Alert feature because I see vertical lines where the checkboxes should be. But if I "restore down" my browser window (make the window smaller) and thus the event details map moves to the top of the page, then I can see checkboxes.

Map at side, can't select checkboxes:
![image](https://user-images.githubusercontent.com/49287076/96507943-80419580-121f-11eb-8b7c-bebc6a4f3156.png)

Map at top, can select checkboxes:
![image](https://user-images.githubusercontent.com/49287076/96508093-b3842480-121f-11eb-9b2d-bbd28111343f.png)

Neil DOES see the checkboxes when his browser window is maximized but he can see the checkboxes turn to vertical lines as he shrinks the browser window.

**To Reproduce**
1. Go to event 170909 (because that event already has collaborators added)
2. Click "Alert Collaborators" tab
3. Play with browser window size

**Expected behavior**
Would like to be able to use checkboxes regardless of browser window size.

**Desktop (please complete the following information):**
Neil is likely using Chrome. Jenny has same issue in Chrome and Firefox

**Comment by JChipault** [comment]
Two more thoughts 1) I have the same issue in the old test site and 2) other checkboxes (e.g., those in the dashboard) seem fine when I change the size of my browser window

**Comment by BlakeDraper** [comment]
@JChipault I see what you mean. I have included a small CSS rule that will prevent this from happening. New patch release soon.

**Comment by BlakeDraper** [comment]
v2.15.9
