### ISSUE TITLE
Event ID search

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1083]
Splitting this feature out of #1057.

With Event ID search users can enter Event IDs as search criteria, useful when specific known events are being tracked. This will need some backend work to add a new event_id search criteria field.

**Comment by aaronstephenson** [comment]
Adding that to the back end would be very simple. With the recent refactor, query params are now centrally managed in the filters.py file.

**Comment by machristie** [comment]
Yes, thanks @aaronstephenson . I took some time to get familiar with the new django-filter refactor and it looks like it will be a one-line change to add event id search.

**Comment by machristie** [comment]
Created PR for backend changes: https://github.com/USGS-WiM/whispersservices/pull/416

**Comment by machristie** [comment]
Created PR #1084

**Comment by BlakeDraper** [comment]
Published in v2.16.0.
