### ISSUE TITLE
Use session based authentication to remain logged in when opening more tabs?

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1099]
Hi @BlakeDraper,

I'm working on an enhancement to simplify the map event popup so that it contains less event details but has a link the user can click to get to the event details page. One problem with this is that if the user opens an event details link in a separate tab. What do you think about switching from basic authentication to session-based authentication? The user would stay logged in as long as their Django session was active.

This would require
- having the backend authentication (CustomBasicAuthentication) log the user into a Django user session (https://docs.djangoproject.com/en/3.1/topics/auth/default/#how-to-log-a-user-in)
- would also need a backend logout REST endpoint
- add the CSRF token to all REST API requests
- would need a new way of checking if the user is logged in. Probably could make a GET request to /auth and have it return the User serialization if the user is logged in or a 401 if not and use that to determine if the user is logged in.

I'm happy to make the changes but I wanted to check with you and Aaron first to see if there is a reason to stick to the Basic Auth approach.

**Comment by BlakeDraper** [comment]
@machristie Aaron and I discussed this today, and our position is that we do not wish to change to session-based authentication. It would be a major refactor on the backend, and, more importantly, it would violate stateless REST principles on which the API is built. We think session-based auth would be a step backwards. 

We had planned at one point to introduce more robust authentication using  OAuth 2.0 via login.gov, but we ran out of time to implement that and priorities changed. You may have the time and priority to implement that integration, however. That is what I would suggest if changing the auth protocol in any way. 

But it seems like the main impetus for this conversation is the new tab link problem? That could more easily be solved by replacing sessionStorage in the client with localStorage. We went with sessionStorage at the time because it seemed marginally more secure (less chance of an errant tab left open with account logged in) - but that is minor, and ultimately up to the WHISPers staff to make that call.

**Comment by machristie** [comment]
Hi @BlakeDraper. Yes, this makes sense. I don't currently have time to do the OAuth integration, but that could be a good future effort.

And yes, the main impetus is to stay logged in in a new tab. Switching to localStorage seems like a good solution and I can't off the top of my head think of how it is less secure than sessionStorage. It is probably worth researching localStorage vs sessionStorage a bit first. I'll do some research then discuss with the WHISPers staff.

**Comment by machristie** [comment]
Here I'll attempt to summarize the various options we've discussed:

- **session-based** authentication: user logs into the Django backend, establishing a Django login session, and this is used to authenticate with the REST API. Since the Django login session is associated with a cookie, the user opening the site on another tab/window would still be logged in. This would require adding the CSRF (Cross Site Request Forgery) token to REST API requests to prevent session hijacking.
  - pros:
    - relatively simple to implement
    - secure
  - cons:
    - violates stateless REST principles on which API was designed
- **switch from SessionStorage to LocalStorage**. The user's username and password are stored in SessionStorage and used on each request. On the backend this is HTTP Basic authentication.  The SessionStorage goes away once the browser tab or window is closed. Switching to LocalStorage maintains the credentials across all browser tabs/windows, allowing the user to open another tab for the site and stay logged in.
  - pros:
    - very simple to implement
  - cons:
    - main security concern is XSS (Cross Site Scripting). (It's not clear though whether LocalStorage has a larger attack surface area compared to SessionStorage, since XSS requires the user to access the target site.)
    - another security concern is the physical security of the user's computer (assuming LocalStorage is persisted to the computer's disk).
- **token-based, OAuth2** authentication - The user logs into an authorization server and receives an access token. This access token is passed in all requests to the API server. The API server validates the token with the authorization server. The user has a login session with the authorization server and remains logged in until the user logs out or the session times out. The user can open another tab and remain logged in (i.e., single sign-on).
  - pros:
    - more secure approach to API security
    - congruent with the stateless REST API
    - (possibly) benefits to users if authorization server federates identity to existing authentication sources, for example, if user can sign in with an account they already have, there is no need to manage another set of credentials
  - cons:
    - much more development effort than other options. Will touch not only API authorization but also user login and account management.

**Comment by machristie** [comment]
Met with @nbaertlein, @BlakeDraper, Aaron and Ali. Here's our plan going forward:

- switch from SessionStorage to LocalStorage
- have a security scan run to check for XSS (or any other) vulnerabilities
- based on results from security scan, move forward or not with LocalStorage approach
- implement a login timeout as a separate feature where the user is logged out after a certain period of time
  - ideally the timeout is based on the user being idle in the app
- long-term, the token-based OAuth2 approach is ideal, but will require separate funding

**Comment by machristie** [comment]
merged
