### ISSUE TITLE
species list not resetting when toggle among notifications

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1103]
**Describe the bug**
When I click a notification from the list on the WHISPers banner, it jumps me to that event that I got a notification about but it carries over the species list of the event that I was previously on. 

**To Reproduce**
1. Log In
2. Go to any event details page (I started with 200948, which has a "unidentified cottontail rabbit" as species
3. Navigate mouse up to the "Notifications" button in the banner, click there, click on an "All Events" notification for 200974. 
4. 200974 should only have a raccoon listed but I see both the old cottontail rabbit AND the raccoon.
![image](https://user-images.githubusercontent.com/49287076/99975292-ac44bf00-2d67-11eb-9031-d7a086ef22d9.png)
5. Navigate back to "Notifications" in banner and click on 200970
6. Now I have the rabbit, the raccoon, and a bat (when I should have just the bat for 200970)
![image](https://user-images.githubusercontent.com/49287076/99975499-ed3cd380-2d67-11eb-92dd-23b46477cb8b.png)
7. If I refresh my browser, I get just the bat when looking at 200970

**Expected behavior**
Need only the species relevant to that event to be displayed on the event details page

**Desktop (please complete the following information):**
happened in both chrome and firefox and for multiple users

**Comment by BlakeDraper** [comment]
Fixed in v2.15.12.
