### ISSUE TITLE
Prevent unnecessary scroll zooming in the map

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1111]
Scrolling to zoom can get in the way of the user trying to scroll the page. It can also result in zooming very far out or in too much.

One idea I investigated was only activating scrollWheelZoom when the map has focus, as given in the StackOverflow answer: https://gis.stackexchange.com/a/260340

I didn't see good performance with that but I need to do more testing.

Also, there are other scroll wheel zoom options that should be explored:
- https://leafletjs.com/reference-1.6.0.html#map-wheeldebouncetime
- https://leafletjs.com/reference-1.6.0.html#map-wheelpxperzoomlevel

**Comment by machristie** [comment]
This issue has some interesting ideas too: https://github.com/Leaflet/Leaflet/issues/2076

**Comment by machristie** [comment]
Today I demoed the GestureHandling Leaflet plugin which adds a Ctrl/Cmd key modifier to activate zoom on scroll to the WHISPers group. They liked it so I'm going to go ahead with that solution.

https://github.com/elmarquis/Leaflet.GestureHandling

Still to do:
- [ ] integrate GestureHandling with the event details map

**Comment by BlakeDraper** [comment]
Published in v2.16.0.
