### ISSUE TITLE
base maps not displaying

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1118]
The home page and the event details page "Streets" and "Grayscale" base maps are not loading. The "Open Street Map" option seems to be working but it's not the default.

**Comment by JChipault** [comment]
All was fine last night; issue surfaced this morning

**Comment by BlakeDraper** [comment]
Replaced the deprecated mapbox basemaps with Esri equivalents.

**Comment by BlakeDraper** [comment]
Fixed in v2.16.1 In test) and also as a hotfix on production.

**Comment by JChipault** [comment]
@BlakeDraper New maps aren't loading on search results report or event details report. Hoping that's a quick fix?

**Comment by BlakeDraper** [comment]
It was. Released as a 2.16.2 on test.
