### ISSUE TITLE
Overlap in map pop-ups

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#1122]
@machristie 
Occasionally see overlap of "Event" and the number in the map pop-ups.  Reproducing error is inconsistent.
![image](https://user-images.githubusercontent.com/38669574/105404829-09d27c00-5bf0-11eb-9d9e-8c510fe5d9eb.png)
![image](https://user-images.githubusercontent.com/38669574/105404866-16ef6b00-5bf0-11eb-88ff-010497f3b79f.png)

**Comment by machristie** [comment]
I wasn't able to reproduce. Leaflet popups use some sort of dynamic sizing algorithm. I've added a minWidth of 200 which should prevent event links from overlapping.

**Comment by BlakeDraper** [comment]
Published in v2.16.4.
