### ISSUE TITLE
Legend cut-off in report

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#1129]
The legend on the home page pdf report is cut-off at the bottom.  @machristie I know we had the legend adjusted, is there anyway to make this fit?
![image](https://user-images.githubusercontent.com/38669574/106169269-ce3a3380-6154-11eb-8ee2-9ef3ee44c21e.png)

**Comment by machristie** [comment]
Hi @nbaertlein. I'm unable to reproduce this in either Firefox or Chrome.  One question, is the legend cut off in the popup dialog that creates the PDF report?

**Comment by nbaertlein** [comment]
@machristie   The popup dialog looks fine (see below), but gets cut-off in the pdf (attached). 
![image](https://user-images.githubusercontent.com/38669574/107056287-cd7a5080-6797-11eb-9424-8553d2aa9d5c.png)
[WHISPers_Search_Results_20210205.pdf](https://github.com/USGS-WiM/whispers/files/5933657/WHISPers_Search_Results_20210205.pdf)

**Comment by lprivette** [comment]
Might be a screen size issue when html2canvas is getting that image from the dialog. Getting Niels screen dimensions will probably help

**Comment by nbaertlein** [comment]
I see now.  I have my display set at the recommended and get the truncation
![image](https://user-images.githubusercontent.com/38669574/107059805-dd942f00-679b-11eb-936e-687636f93c35.png)

but I can reduce the browser to 75% and it fixes the pdf issue.
![image](https://user-images.githubusercontent.com/38669574/107059531-7f674c00-679b-11eb-9ff1-1a1123dddf4e.png)

Since the legend needs to resize with the rest of the app in the browser, I imagine making the legend static in the pdf report would likely be a bit of work?  Any other options?

**Comment by machristie** [comment]
@BlakeDraper not yet. My plan is to try to reproduce the issue by changing the resolution of my monitor, to match the above.

**Comment by JChipault** [comment]
I was able to reproduce this legend issue today in Chrome and Firefox.
![image](https://user-images.githubusercontent.com/49287076/109045771-995cc600-7699-11eb-914b-22d86dd16948.png)

Additionally, I noticed that the event dots on the home page map don't all transfer to my PDF report in Chrome and Firefox (see below). Like Neil indicated with the legend, it looks fine in the pop up dialog, but then some dots get lost when it creates the PDF. This report reflects a search for state=New Hampshire. Too many dots crammed along the east coast maybe? Not sure whether to make that a new ticket or tack it on here, so I put it here for now but feel free to flip it to a new ticket if unrelated issue. 

![image](https://user-images.githubusercontent.com/49287076/109046873-d8d7e200-769a-11eb-89e7-b6c48c92dd4d.png)

![image](https://user-images.githubusercontent.com/49287076/109046227-1ee07600-769a-11eb-9eb1-319a1f58e893.png)

**Comment by machristie** [comment]
I was able to reproduce this by making my browser window short enough to cause some scrolling in the legend.

I've fixed this by setting a fixed minimum height of the dialog window and removing the scrolling on the legend. I think it is the legend scrolling that is the cause of the cutoff in the report.  Locally it works. I can size my browser window such that I can reproduce the issue on whisperstest, but in a separate tab, with the same browser window dimensions, the legend isn't cutoff.

**Comment by JChipault** [comment]
Maybe I'm not following, but just wanted to point out that you can see in my last screenshot that I don't have to scroll to see the full legend when I'm on the home page. I have pretty big monitors.

**Comment by machristie** [comment]
@JChipault the markers disappearing seems like a separate issue

**Comment by machristie** [comment]
> Maybe I'm not following, but just wanted to point out that you can see in my last screenshot that I don't have to scroll to see the full legend when I'm on the home page. I have pretty big monitors.

@JChipault yeah that's a good point. Possibly there are multiple causes of the legend cutoff. Let's see if the PR I submitted fixes it. Also, I suspect that removing the possibility of scrolling the legend with fix cutoff issues, like maybe it displays fine in the popup on your monitor, but when it is generating the PDF the layout is different enough to introduce scrolling and hence cutoff.

**Comment by BlakeDraper** [comment]
Published in v2.16.5.
