### ISSUE TITLE
Generate Analytics Report

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/whispers#1132]
Please generate a simple analytics report for Whispers. On a bi-weekly basis (starting Thursday the 11th at 5am), send analytics report showing analytics information from the previous 2 weeks and for the previous year. Include in both of these reports:
-new users / total users counts
-most used pages
-users geographic information
-breakdown of configured events

ask away here in the issue for clarifications!

**Comment by lprivette** [comment]
Using the fancy new google dashboards. For the Behavior one I added "Most Popular Events by Event Label". For the Audience one I added a City Breakdown.

Scheduled to go out on 2/11 at 5:00 (Eastern) to Neil, I can edit so let me know if you want me to add anyone else @HansVraga

**Comment by HansVraga** [comment]
Thanks EL! There's still a URL for these? If so, we can park in our meeting agenda for now and that will do!
