### ISSUE TITLE
Forgot Password not working

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1137]
@machristie   If I type in my user name on the “Request Password Reset” subform and click “REQUEST PASSWORD RESET” button, nothing happens other than a quick glimpse of a load bar on the subform. Then when I went to login with my old/normal password, it worked just fine so apparently my password was not reset.

**Comment by machristie** [comment]
@aaronstephenson https://github.com/USGS-WiM/whispersservices/pull/444 fixes a bad import and that should hopefully fix this issue

**Comment by aaronstephenson** [comment]
@machristie thanks, I reviewed and approved the PR and merged it into the dev branch. Just waiting to hear that other issues can be closed before I merge it into the test branch and deploy it to the test server.

**Comment by BlakeDraper** [comment]
@machristie and/or @aaronstephenson just confirming - this issue has been handled or is being handled on the backend? Just trying to tie up any loose ends on the client-side repo.

**Comment by aaronstephenson** [comment]
I merged the back end dev branch into the test branch and deployed it to the test server, so I think this can be closed.

**Comment by JChipault** [comment]
Not quite working. 

This time I got the email and I clicked the link in that email and I got a reset password form so all that was good.

![image](https://user-images.githubusercontent.com/49287076/108892742-dd869280-75d5-11eb-9a22-77a17b606911.png)

but when I clicked "Reset Password" I got this error:

![image](https://user-images.githubusercontent.com/49287076/108892623-b760f280-75d5-11eb-8310-65ca311b27f2.png)

**Comment by JChipault** [comment]
More minor thing, but @machristie can we make the "Cancel" button on the reset password screen match the other cancel buttons?

**Comment by aaronstephenson** [comment]
In the Apache logs I see these errors:

>File "/www/htdocs/test/whispersservices/whispersapi/views.py", line 2177, in reset_password
>serializer = self.get_serializer_class()(user, data=data, partial=True, context={'request': request})
>AssertionError: 'UserViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.

Which is a little strange, because that ViewSet definitely has a serializer class set (line 2074):
```serializer_class = UserSerializer```

@machristie perhaps it has something to do with the extra parentheses on line 2177 (shown in excerpt above).

**Comment by machristie** [comment]
@aaronstephenson yes, that was it, or mostly it. For some reason I had the `@action` decorator set the serializer_class to None and that was causing this error. But I also wasn't constructing the serializer correctly: it needs some context to dynamically determine the fields available, like the action name. I've created a PR to fix these.

**Comment by aaronstephenson** [comment]
I merged your PR into dev and then test, and deployed it to the test server.

@JChipault give it another try now.

**Comment by JChipault** [comment]
The password change subform was super slow to load (both via clicking the link in the email and copying-and-pasting the url from the email; both in chrome and firefox... I had time to try out all these options while it was loading). Browser tried to load for a long time (I saw the loading indicator in the browser tab), then I got the message below, then I saw the throbbing WHISPers "W" on a black background for a while, then finally the reset password subform.

![image](https://user-images.githubusercontent.com/49287076/109061597-7982cd80-76ac-11eb-9654-1fc2083ff714.png)

When got to password subform, I tried using my same password to see if it would tell me not to do that and got this
![image](https://user-images.githubusercontent.com/49287076/109061657-8bfd0700-76ac-11eb-9c53-8f80db0aa659.png)

So I did as instructed and hit the "Forgot Password" button again and put in my user name and got another email.

Still took forever to load. I counted this time - 40 seconds. But I did not get the times out message this time... most of those 40 seconds was just watching the loading indicator in the browser tab chugging along.

I entered a new password this time and still got the same Fail message.

**Comment by aaronstephenson** [comment]
I looked at all the logs and didn't see any errors aside from several simple `Forbidden: /api/auth/` lines and one each of `Bad Request: /api/users/166/` and `Not Found: /api/users/166/`. So maybe the client's POST for the new password failed (bad request), which the client didn't expect to happen, and so it never reset the waiting gif despite the failure.

@JChipault try it one more time, but this time make sure the browser's dev tools are open with the Network tab visible, then let us know if any errors appear there (I'm hoping the Bad Request response will have more details about what went wrong than what's in the log file).

@machristie any ideas?

**Comment by JChipault** [comment]
Now seems to not be sending me the emails at all.

**Comment by JChipault** [comment]
@aaronstephenson  emails just came through

**Comment by JChipault** [comment]
I have no idea what this means, but this is what I see in that network tab:
![image](https://user-images.githubusercontent.com/49287076/109071586-8659ee00-76b9-11eb-9a79-74e44359f02c.png)

**Comment by JChipault** [comment]
I should clarify, this is what I see when it throws the "Password Reset Failed" message.  I'm noticing that I'm actually logged in when I see this "Password Reset Failed" message so I'll try a different sequence now (click password reset email link, log out, try resetting password)

**Comment by aaronstephenson** [comment]
@JChipault can you click on that error line of the Network tab, then click on the Response (or Preview) tab, and show us what's there?

**Comment by JChipault** [comment]
I don't see a Response or Preview tab... not sure where to click.

**Comment by JChipault** [comment]
I just tried right-clicking my mouse and selected "open in new tab" and see this:
![image](https://user-images.githubusercontent.com/49287076/109073969-b5be2a00-76bc-11eb-8550-8051cc47f069.png)

**Comment by machristie** [comment]
@JChipault when you said you are actually logged in when you see the "Password Reset Failed" message, that could be what is causing that failure. The password reset token is designed to be invalidated after it is used and the way it does this is it is based, partly, on when the the user last logged in. The assumption being that after you reset your password you're likely to log in and then that would then invalidate the token (in case the token leaks somehow, so another user can't use it to reset your password). So when you log in, that updates the last logged in date on your user record, and effectively invalidates your reset password token.

I hope that makes sense. Bottom line, to test this, you should first log out of WHISPers and remained logged out through the testing. Once you reset your password you will be automatically logged in again.

**Comment by JChipault** [comment]
@machristie and @aaronstephenson This time I was logged out and still got same error message: 
![image](https://user-images.githubusercontent.com/49287076/109074384-544a8b00-76bd-11eb-9ef9-9a8a02f2b994.png)

**Comment by JChipault** [comment]
@machristie  Per @aaronstephenson 's suggestion, I tried it with a different user (jennypartner1) and it seemed to work just fine!!! That's an account I don't think I've used yet today. So maybe even though I was logged out when recently testing my user name=jchipault account, there was still some sort of tracking of my login going on in the background (I dunno what I'm talking about technically-speaking, I just know I've been in my jchipault account in various browsers multiple times today)

**Comment by JChipault** [comment]
@machristie I tried resetting the password onmy jchipault account this morning (after my computer had been off overnight and before logging into the live site or test site or APIs this morning) and it worked really smoothly! This was the account that was problematic yesterday. So perhaps it's just that my old password was being cached (or remembered somehow) on my computer as I was trying to reset? Maybe we're all good now?

**Comment by machristie** [comment]
@JChipault That's great to hear Jenny. Yes, if you were logged in another tab or window, that could definitely invalidate the token. It would be tricky I think to try to code for that particular scenario, a scenario which seems unlikely in practice. The main reason for a user to reset their password is because they've forgotten it and hence they're not logged in at all.

So yes I think we're all good now.

**Comment by BlakeDraper** [comment]
Published in v2.16.5.
