### ISSUE TITLE
error TS2307: Cannot find module 'pdfmake/build/pdfMake'

### ISSUE THREAD

**Issue by machristie** [USGS-WiM/whispers#1141]
On a Linux system, `npm install` and `npm start` give the following error

```
ERROR in src/app/event-details/event-details.component.ts(12,21): error TS2307: Cannot find module 'pdfmake/build/pdfMake'.
src/app/event-public-report/event-public-report.component.ts(3,21): error TS2307: Cannot find module 'pdfmake/build/pdfMake'.
src/app/search-results-summary-report/search-results-summary-report.component.ts(3,21): error TS2307: Cannot find module 'pdfmake/build/pdfMake'.
```

The name of the file being imported is `pdfmake/build/pdfmake.js`, all lowercase. This seems to be a situation where on filesystems that are case-insensitive, the import works, but on case-sensitive filesystem, the import fails.

I'll submit a PR with the fix.

**Comment by BlakeDraper** [comment]
Published in v2.16.4.
