### ISSUE TITLE
Public accounts are available as collaborators (should be affiliates and up)

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1143]
**Describe the bug**
On both the live and the test site, one is able to add a public user as a collaborator. 

**To Reproduce**
1. Go to any event details page
2. Click on "Add Individual"
3. Enter this email address: nbaertlein+id15@usgs.gov
4. Click "search"
5. Click "add as collaborator"
6. Note that this worked for a public account (user ID=15) when it should only work for affiliates or higher

**Screenshots**
![image](https://user-images.githubusercontent.com/49287076/106960194-572b0f00-6701-11eb-8f7f-5b924d1e1295.png)

**Additional context**
This has happened on both the live and test site and at least two users were able to reproduce. I believe this is a reversion and that the site used to tell you that there were no WHISPers users with that email. (although maybe we should change that wording to be a bit more accurate and say "No WHISPers user with email address xxxx is eligible to collaborate.")

**Comment by aaronstephenson** [comment]
Step 4 (search) is handled by the API. I just altered it to only return matching users with roles of affiliate and above. I'll push the change soon.

**Comment by JChipault** [comment]
@aaronstephenson looks like this one is fixed on the test site and can be closed, you agree?
