### ISSUE TITLE
No emails being sent during registration process

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1144]
@machristie 

**Describe the bug**
It appears that no emails are being sent out as part of the email verification step in the registration process on the test site. Kim created an account (user ID 161) using her personal email address and never got an email. 

Jenny tried too but was either 1) using the addition of + within an email address (user ID 158 or 159) and did not get emails or 2) was too lazy to hunt down password to an old email account (user ID 157).

Neil thinks the + might be an issue, but the fact that Kim's email should have gone right to her personal inbox makes us think these emails aren't issuing at all, hence this github ticket.

**Comment by aaronstephenson** [comment]
I've been looking into this. There's something wrong with the celery daemon. The celery logs are full of errors about unregistered tasks. Except nothing with the celery configuration has changed in months, to my knowledge. Additionally, when I run celery in interactive mode and not as a daemon, everything works fine.

Still investigating.

**Comment by aaronstephenson** [comment]
@JChipault this is related to #1155 and should be fixed now. Let me know if this issue can be closed.

**Comment by JChipault** [comment]
Yup, fixed
