### ISSUE TITLE
condense toggles when run a search

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1145]
@machristie 

**If Possible, Describe a Solution**
Would it be easy to have all the toggles in the search pane get condensed after you run a search? Currently, the last data field that was messed with stays expanded and focused on, which makes it a little harder to easily assess what criteria are actively associated with the data on the map and table.

Condensing all the toggles would happen when you hit the "search" button, but also same would go for if you play around with the search criteria but then hit "default" or click on a popular search. 

**Screenshots**
Currently, when I select "American avocet" from the species list in the search and then hit the "Search" button, I get this: 
![image](https://user-images.githubusercontent.com/49287076/107262941-c73ddb80-6a06-11eb-9310-be5a9a2abfa1.png)

Can we tighten it up a bit so that it looks like this and the criteria visually pop out more:
![image](https://user-images.githubusercontent.com/49287076/107263036-e2a8e680-6a06-11eb-8051-b6b33532f74d.png)

**Comment by BlakeDraper** [comment]
Published in v2.16.5.
