### ISSUE TITLE
changes to registration page with 3 buttons

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1146]
@machristie 

**Undesired or Confusing behavior**
1) On smaller computer screens, the blue buttons aren't visible unless you scroll down. 
2) We decided to stick with "search" instead of call the search a "filter"

**If Possible, Describe a Solution**
1) Would it be possible to move the blue buttons down into the space where the cancel button currently is so that the blue buttons always show but it's still clear which column they go with?
2) Switch 3 instances of "filters" (one per column) to "searches"

**Screenshots**
![image](https://user-images.githubusercontent.com/49287076/107264047-18020400-6a08-11eb-8fe4-6d43a5e65143.png)

**Comment by BlakeDraper** [comment]
Published in v2.16.5.
