### ISSUE TITLE
run search before "save search criteria" finalized

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1147]
@machristie 

**Undesired Design or Confusing behavior**
Example - if I select "Alabama beach mouse" from the species list in the search pane, then click the "search" button, then select "mortality/morbidity" in the search pane, then click "save search criteria", then the saved search only reflects the beach mouse and NOT the mortality/morbidity. What I'm saving doesn't match the search criteria that I see displayed in the left search pane.

**If Possible, Describe a Solution**
When someone clicks "save search criteria" can it run the search first?

**Screenshots**
![image](https://user-images.githubusercontent.com/49287076/107270152-34a23a00-6a10-11eb-8c93-b77f022dd818.png)

**Comment by machristie** [comment]
@JChipault I've submitted a PR to fix this. Now if the user changes the search form but hasn't run the search, the Save Search Criteria button is disabled until they run the search. I also updated the tooltip on the Save Search button when it is disabled to explain that the search needs to be run before it can be saved.

**Comment by BlakeDraper** [comment]
Published in v2.16.4.
