### ISSUE TITLE
Showing "Event ID" label in my saved searches even if no Event ID selected

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1148]
@machristie 

**Describe the bug**
Showing "Event ID" label in my saved searches even if no Event ID selected
![image](https://user-images.githubusercontent.com/49287076/107270928-256fbc00-6a11-11eb-8038-ae9de627ef72.png)

**Comment by BlakeDraper** [comment]
Published in v2.16.4.
