### ISSUE TITLE
button inconsistency on login and password reset

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1150]
@machristie 

There's some inconsistency in buttons on the login and forgot password subforms. Now that you've put together the button style guide, perhaps revisit these subforms? We were thinking the "Forgot Password?" button would be outlined in blue?? And the "cancel" button is outlined on one of the subforms and not on the other (and not blue in either case, but maybe that's on purpose?). Also, the bottom of the "Forgot password?" button is clipped off on some screens (if that's not an easy fix then skip it).

**Screenshots**
![image](https://user-images.githubusercontent.com/49287076/107273628-ec394b00-6a14-11eb-8ffc-14a870049f51.png)
![image](https://user-images.githubusercontent.com/49287076/107273638-ef343b80-6a14-11eb-8075-d9b3d7df0823.png)

**Comment by JChipault** [comment]
Additionally, should the "LOGIN" button be changed to "LOG IN" (two words) because it's an action? It's two words in the banner on the home page.

And on the login subform, can we remove the asterisks from the password line? Both user name and password are required, but we are thinking neither need an asterisks since other short subforms (like the reset password one) do not have asterisks.

**Comment by machristie** [comment]
@JChipault yes to all of these, good catches. I've submitted a PR.

**Comment by BlakeDraper** [comment]
Published in v2.16.4.
