### ISSUE TITLE
disconnect between criteria in search pane and what's on map/in table

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1151]
**Undesired Design or Confusing behavior**
If I have search criteria that result in too big of a data set to display (e.g., event diagnosis = botulism type C) or I clear all search criteria, I see the red warning message in the search pane telling me that I need to narrow my search, but the map and the table are still displaying the data from my previous search. 

**If Possible, Describe a Solution**
If search results are too large, do not display any data on the map or table.

**Screenshots**
![image](https://user-images.githubusercontent.com/49287076/107281523-6969bd80-6a1f-11eb-9ed6-66d7044974c9.png)

![image](https://user-images.githubusercontent.com/49287076/107281503-6242af80-6a1f-11eb-9891-20a13cdf3c7c.png)

**Comment by BlakeDraper** [comment]
Published in v2.16.4.

**Comment by JChipault** [comment]
It's working great when your search results are too large. Doesn't seem to work if you hit the "Clear" button (still shows data from my previous search). Of the two scenarios (search results too large and cleared criteria), the more important of the two has been fixed so that's awesome. If the cleared criteria scenario is a quick tweak, awesome. If it's a harder fix, I can just demote it to our future wish list

**Comment by machristie** [comment]
@JChipault I thought I had done that, but I guess not. Yeah it's a quick fix. I'll submit a PR soon.

**Comment by BlakeDraper** [comment]
Published in v2.16.5.
