### ISSUE TITLE
Make new "home" button bigger

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1153]
@machristie 

**If Possible, Describe a Solution**
The logo is now the “home” button if you're not logged in … if it's easy and quick, can we extend the button-ness of it to include the words to the right of the acronym?

**Screenshots**
![image](https://user-images.githubusercontent.com/49287076/107283078-83a49b00-6a21-11eb-97cb-7f7da735e68b.png)

**Comment by BlakeDraper** [comment]
Published in v2.16.4.
