### ISSUE TITLE
re-center map?

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1154]
@machristie 

**Undesired or Confusing behavior**
Now that the legend defaults to expanded on the home page map (yay!), we're wondering if it'd be easy to re-center how the map sits in order to account for that lost real estate on the right side of the map. If this is complicated, skip it. 

**Screenshots**
How the map loads: 
![image](https://user-images.githubusercontent.com/49287076/107283600-35dc6280-6a22-11eb-880c-07676022a60d.png)

If I shift it over a bit, it feels less scrunched... any chance it's easy to default to this sort of view:
![image](https://user-images.githubusercontent.com/49287076/107283732-64f2d400-6a22-11eb-9406-7caeff475beb.png)

**Comment by BlakeDraper** [comment]
Published in v2.16.4.
