### ISSUE TITLE
notification bug on test site - overnight notification not issuing/alert collaborator emails not sending

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1155]
Tagging @aaronstephenson because this might be a backend issue (?)

**Describe the bug**
I made a couple of changes to event 170895 in the test site on Feb 8 that should have issued custom and standard notifications to the jchipault account and abilenetest account and no notifications came through (not via email nor on dashboard). Looks like notifications haven't been issued since Jan 14... that said, I've been testing the search and registration more lately so maybe haven't been making many changes to events that would trigger notifications.

Another sign that things are off with notifications... I logged in as abilenetest this morning and went to event 170944, added jchipault as a collaborator, and issued a collaborator alert to jchipault. I got the toast message that said that my alert was sent. And I can see the collaborator alert in the comment timeline for the event. But I never got an email at my jchipault account.

**Comment by aaronstephenson** [comment]
@JChipault this should also be working now. Let me know if this issue can be closed.

**Comment by JChipault** [comment]
Yes, this is working now.
