### ISSUE TITLE
make column headers on tables lower case

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1156]
@machristie 

**Undesired Design or Confusing behavior**
Column headers that are associated with sort arrows got transitioned to all capital letters when all buttons were set to all caps. This is a bit confusing because it's the arrows that are a button, not really the column header itself.

**If Possible, Describe a Solution**
Can we make an exception to the rule for these column headers so that only the first letter of each word is capitalized? 

In this screen shot, the columns associated with arrows are all caps but the other columns are not - would prefer they all matched. Thanks
![image](https://user-images.githubusercontent.com/49287076/107535889-c7fd7b80-6b86-11eb-839b-b09a508690b7.png)

**Comment by BlakeDraper** [comment]
Published in v2.16.4.
