### ISSUE TITLE
can't verify email for new account

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1157]
@machristie   @aaronstephenson

The email asking me to verify my email address is coming through now (awesome!) but when I click the "verification link" or copy the url that's provided to me in the email (see below), I get taken to the WIM home page.

https://test.wim.usgs.gov/whispers/?user-id=164&email-token=5o3-2379b5dda3b5000ad88d

I tried logging in on the test site after clicking the verification link (thinking maybe getting dropped at the WIM home page is what is supposed to happen?), but I get this message:
![image](https://user-images.githubusercontent.com/49287076/107821604-5ec26780-6d42-11eb-8ccd-7eacc8b866aa.png)

This is all in connection with user ID 164. I did not get an email for user ID 163 but I think that's because usgs doesn't like us using the +@usgs.gov as an email variation.

**Comment by machristie** [comment]
@aaronstephenson I used `settings.APP_WHISPERS_URL` to create a link back to the frontend. Is there a better setting or Configuration to use?  Or is this just a matter of APP_WHISPERS_URL needing to be set to "https://whisperstest.wim.usgs.gov" on the test api server?

**Comment by aaronstephenson** [comment]
Sorry, yes, the value for that setting had the wrong URL. I have now corrected it.

**Comment by JChipault** [comment]
Working!  Thanks!
![image](https://user-images.githubusercontent.com/49287076/107831982-eadd8a80-6d54-11eb-8021-9d94a14d0156.png)
