### ISSUE TITLE
not able to create event on test site

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1158]
@aaronstephenson @machristie  - I'm guessing this one is more for Aaron, but copied Marcus here as FYI.

Created an event with multiple locations in the test site just now. Got a couple of appropriate toast messages when I tried to save that informed me of what business rules I was breaking. Fixed those things but then got this error message in a toast:
Error. Event not Submitted. Error message: SyntaxError: JSON.parse:unexpected character at line 1 column 1 of the JSON data.

I hit F12 and took a screen shot:
![image](https://user-images.githubusercontent.com/49287076/107824923-de066a00-6d47-11eb-8e86-44abc73ee129.png)

Sometimes when we get a toast message saying that the event did not save, it actually has saved. But I did not see this event when I searched for it so I don't think it committed.

This event DID have a service request and since that has caused a problem before (and involves emails, which have been a bit problematic lately), I tried again without a service request. 

Got same error message second time, even when no service request. Copied Form data this time. See below. But did not get F12 network data screen shot on second attempt of creating an event because it wouldn't display so I hit "reload" and that seems to have just taken me back to a blank create event page.

Form Status: VALID

 {
  "event_reference": "",
  "event_type": "1",
  "complete": false,
  "public": true,
  "staff": "5",
  "event_status": "1",
  "legal_status": 1,
  "legal_number": "6546103",
  "new_organizations": [
    2
  ],
  "new_service_request": {
    "request_type": 0,
    "new_comments": []
  },
  "new_event_diagnoses": [
    {
      "diagnosis": "4"
    }
  ],
  "new_comments": [
    {
      "comment": "adfadfasdf",
      "comment_type": 5
    }
  ],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "",
      "start_date": "2021-02-11",
      "end_date": null,
      "country": "30",
      "administrative_level_one": 3,
      "administrative_level_two": 135,
      "latitude": null,
      "longitude": null,
      "land_ownership": "6",
      "gnis_name": "",
      "gnis_id": "",
      "site_description": "",
      "history": "sdfgsdfgsdrfg",
      "environmental_factors": "",
      "clinical_signs": "",
      "comment": "",
      "new_location_species": [
        {
          "species": 1305,
          "population_count": null,
          "sick_count": null,
          "dead_count": null,
          "sick_count_estimated": null,
          "dead_count_estimated": 50,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": []
        }
      ],
      "new_location_contacts": []
    },
    {
      "name": "",
      "start_date": "2021-02-11",
      "end_date": null,
      "country": "30",
      "administrative_level_one": 5,
      "administrative_level_two": 229,
      "latitude": null,
      "longitude": null,
      "land_ownership": "7",
      "gnis_name": "",
      "gnis_id": "",
      "site_description": "",
      "history": "afasdf",
      "environmental_factors": "",
      "clinical_signs": "",
      "comment": "",
      "new_location_species": [
        {
          "species": 151,
          "population_count": null,
          "sick_count": null,
          "dead_count": null,
          "sick_count_estimated": null,
          "dead_count_estimated": 2,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": [
            {
              "diagnosis": 4,
              "cause": 2,
              "basis": 2,
              "suspect": true,
              "tested_count": 1,
              "diagnosis_count": 1,
              "positive_count": null,
              "suspect_count": null,
              "pooled": false,
              "new_species_diagnosis_organizations": [
                3
              ]
            }
          ]
        }
      ],
      "new_location_contacts": [
        {
          "contact": 5136,
          "contact_type": 1
        }
      ]
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": [],
  "quality_check": null
}

**Comment by aaronstephenson** [comment]
Ugh, sorry, this was caused by a missing file. I've been troubleshooting the larger notifications problem the last two days and doing some experimenting, looks like I forgot to restore a file I had moved. This should work now tho.

**Comment by JChipault** [comment]
Works!! And got high impact notification and service request notification when event was saved!

**Comment by BlakeDraper** [comment]
@JChipault Just so you aware, (Neil has been in the loop already) Aaron has employed a stopgap measure for now to make this work and is still investigating the long term solution. To spare you the technical details - we are essentially the notifications stuff in a mode in which it does work, but which is not stable long term for production. We'll need to achieve success in that stable mode before we can truly call it a success. Aaron may be able to provide more detail, but just wanted to give you quick dirty rundown.

**Comment by aaronstephenson** [comment]
@JChipault this should be working now. Let me know if this issue can be closed.

**Comment by JChipault** [comment]
We are able to create events on the test site now so this ticket can be closed
