### ISSUE TITLE
source for registration notifications

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1160]
@aaronstephenson 

This is the notification dashboard of the new account that I just set up, which is jennypartner1. I wouldn't expect jennypartner1 (the new partner user) to be the "source" for these system notifications.
![image](https://user-images.githubusercontent.com/49287076/107833101-d51d9480-6d57-11eb-82a4-1aa1ae692af3.png)

**Comment by aaronstephenson** [comment]
This is from Marcus' new code. He may not have had access to the Notifications Reference spreadsheet that specifies what values should populate each field. It looks like the new ones are set to use "user that made the request" as the source.

I just took another look at that spreadsheet, and it is still incomplete (and may be out of date, considering the new features Marcus has implemented).  Could you review the 4 "user  request" items and complete that spreadsheet? Once that's done we can update the code.

**Comment by JChipault** [comment]
Got it. Yes, looks like our interpretation of "source or initiator" column was a bit more toward the "initiator" end of the spectrum. The "user that made the request" initiates things by performing an action that then makes the system send that same user a message back. I updated the spreadsheet, but here's a summary:
User Request - fine as it was in the spreadsheet (user that requests an account upgrade or requesting an account above public)
User Request Response - fine as it was in the spreadsheet (WHISPers Admin or Org Admin who assigns a WHISPers role) - this is currently showing as the "user that made the request" in the dashboard.
User Request Pending - changed in spreadsheet to "system" 
User Request Response Public accounts - changed in spreadsheet to "system"
2-factor Authentication - added "system" to spreadsheet

**Comment by machristie** [comment]
@JChipault Just want to make sure I understand this. I added two email notifications (*Password Reset* and *User Email Verification*) and they should both have source=system, correct?

**Comment by JChipault** [comment]
@machristie Yes, set both of those to source=system when someone looks at their notification list in their dashboard. Thanks for reminding me about the Password Reset email. I will add that to the table. User Email Verification = 2-factor Authentication in our table that Aaron is referring to.

**Comment by machristie** [comment]
Thanks @JChipault, I've submitted a PR

**Comment by BlakeDraper** [comment]
@machristie and/or @aaronstephenson just confirming - this issue has been handled or is being handled on the backend? Just trying to tie up any loose ends on the client-side repo.

**Comment by aaronstephenson** [comment]
I merged the PR into the dev branch, and then into the test branch, and deployed that to the test server. This can closed I think.
