### ISSUE TITLE
county options not resetting when change state in search

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1161]
@machristie 

**Describe the bug**
If I select a state in the search, then navigate to the counties dropdown, I get counties that match the state I've selected. This is good. However, if I clear out the state, then navigate back to the counties dropdown, I still get the counties that pair with the state I used to have selected. 

Kim reports another variation on this theme:
I selected WI and Dane county as search criteria.  Then deleted WI and selected CA.  Dane stayed listed and it looked like a mix of WI and CA counties in the county drop down list.  So I added Alameda to Dane in the county search field and clicked search- Dane cleared out and just Alameda remained. The drop down list still appears to be a mix of both states.  I had to refresh the page to clear the WI counties from the drop down list.

**Expected behavior**
Expect county dropdown options to refresh when change state.

**Comment by BlakeDraper** [comment]
Published in v2.16.4.
