### ISSUE TITLE
Updates to FAQ text

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1179]
@machristie  Labeled this as a bug just to bring attention to it for Marcus because he's probably doing this this week.

![image](https://user-images.githubusercontent.com/49287076/109222755-6a208480-777f-11eb-8af3-4a1963465a18.png)

Lesser priority, but if easy enough while you're in this part of the code, adding this to the FAQs would be great:
![image](https://user-images.githubusercontent.com/49287076/109222987-9f2cd700-777f-11eb-9bca-65796e781c2e.png)

**Comment by machristie** [comment]
@JChipault Hi Jenny, I've made a PR for these changes. One thing I noticed is that a couple of the URLs gave me a "503 Not Authorized" error, which is maybe because I don't have the necessary privileges:
- https://www.oie.int/wahis_2/public/wahiswild.php/
- https://www.oie.int/wahis_2/public/wahidwild.php/Diseaseinformation/popup/diseaselist

Can you confirm that those are the correct URLs? Thanks.

**Comment by JChipault** [comment]
@machristie Thank you for checking those! They don't work for me either and I saw this on the OIE home page: 
![image](https://user-images.githubusercontent.com/49287076/109828079-ee508d00-7c01-11eb-9bf7-5845acb644c8.png)
Looks like that system is undergoing an overhaul and is down currently. I'm going to ask around and see if anyone here knows how long it might be down. Will be back in touch

**Comment by JChipault** [comment]
Ok, sounds like the system will be back up in a couple of weeks. Someone is asking them if the urls will remain the same but I'm not sure how fast we'll get an answer on that. If you want to cross this off your list, feel free to put in those broken urls for now and it'll be on my radar to get them updated if we need to change them after their system is back up.

**Comment by machristie** [comment]
@JChipault Thanks Jenny. I have those URLs in the pull request. If you get the updated URLs before the pull request gets merged, I can easily update them. Otherwise it may need to be changed later like you said.

**Comment by JChipault** [comment]
We heard back that those URLs will likely change when they launch the new WAHIS Wild system but we don't have new URLs yet so this is fine as is and we'll just circle back to fix those links later. THANK YOU!

**Comment by BlakeDraper** [comment]
Published in v2.16.6.
