### ISSUE TITLE
Event dots on map not all on PDF report

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1182]
See #1129 for description and screen shots. Problem with dots on the map persisted after Marcus fixed issue with legend clipping on the PDF.

**Comment by JChipault** [comment]
slightly different variation on the theme popped up today. search criteria are in the screen shot of the report.

![image](https://user-images.githubusercontent.com/49287076/111671646-27ceee00-87e7-11eb-9d05-1ce161a84f98.png)

![image](https://user-images.githubusercontent.com/49287076/111671715-35847380-87e7-11eb-846a-521a0917b5fe.png)

**Comment by JChipault** [comment]
Ran this again now that v2.16.6 has been released and it's better!
![image](https://user-images.githubusercontent.com/49287076/112229328-c81a7d80-8c00-11eb-9135-13c2ca8cd3e3.png)

**Comment by JChipault** [comment]
I ran the search for state=New Hampshire (reported in github #1129) in the live site and it worked well. However, the spread of the data that meet that search criteria are different in the live site than the test site and it's still missing dots on the test site.

Live (v2.16.6):
![image](https://user-images.githubusercontent.com/49287076/112229986-019fb880-8c02-11eb-854a-d82118f03f63.png)

Test (same version - v2.16.6 - but with slightly different data):
![image](https://user-images.githubusercontent.com/49287076/112230024-1f6d1d80-8c02-11eb-9942-00106909278d.png)

**Comment by BlakeDraper** [comment]
@JChipault test and production have completely separate databases so they would return different data. The version refers to the software that you use to view the data, not the data itself.

**Comment by JChipault** [comment]
@BlakeDraper Yup, totally get that. Just trying to point out that I can't quite reproduce in live the issue I'm seeing in test and perhaps it's because the issue is related to the spread of the data on the map. So the code (which is the same in both) works sometimes but not other times (and maybe it has something to do with the spread of the data on the map??? dunno). I'm not sure what scenario to run on the live site to reproduce the bug there but since it's the same software currently on test and live maybe that doesn't matter.

**Comment by BlakeDraper** [comment]
fixed in v2.16.7.

**Comment by JChipault** [comment]
@BlakeDraper 
On the test site (v2.16.7), if I search for state=New Hampshire, I still only get one dot on the report map even though there are 27 events that meet the search criteria.

![image](https://user-images.githubusercontent.com/49287076/115798161-3044b680-a39b-11eb-919d-33f20f11c6d8.png)

**Comment by BlakeDraper** [comment]
@JChipault sorry, I did not catch the problem of dots totally missing. I addressed the cut-off thing that was happening. I've been at this for a while, and I cannot find any other search that does this aside from New Hampshire. Have you happened to find any others? Trying to determine a pattern here.

**Comment by JChipault** [comment]
@BlakeDraper 
It took a while but I did find one other:
![image](https://user-images.githubusercontent.com/49287076/115903171-e5718000-a428-11eb-8a87-47515ec0913a.png)


But, yea, I tried other instances of east coast states (just Vermont, just Rhode Island) and those were fine. And I also tried instances where the data were clumped mostly in one area (botulism type e). And I tried searches where most of the data were clumped on the east coast but some was on the west coast (west nile virus in 7 eastern states and washington state).  All of these were fine. Not sure what the trend is....

**Comment by BlakeDraper** [comment]
@JChipault after a morning of digging and  banging my head against a wall, we have identified the likely problem, but still working on a fix. It's a tough one. Thanks for your input.

**Comment by BlakeDraper** [comment]
Lauren replaced html2canvas with dom-to-image to fix this finally. Done w/v2.16.8.

**Comment by BlakeDraper** [comment]
Published in release 2.16.8.

**Comment by JChipault** [comment]
Looks good
