### ISSUE TITLE
inconsistencies in selection-dependent dropdowns

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1199]
Lower priority fix but here's the issue:

If have diagnosis types of fungus and bacteria and then remove those by clicking the "x" on the pills, then when I try to select an event diagnosis I only get options that are fungus or bacteria (e.g., can't get any toxicosis to show up in the dropdown). If I click "Clear" at the bottom I still have the same a problem. 

Someone else has also mentioned having this same sort of issue earlier this month with regard to state and county but I haven't been able to reproduce that.

**Comment by BlakeDraper** [comment]
Need to ensure that all removals of options trigger a reset of the filtering on related parameters. Also consider visually indicating to the user when lists are limited by selections on other lists.

**Comment by BlakeDraper** [comment]
This is done, in dev branch for the diagnosis type/ event diagnosis linkage. Will create a future issue for the added visual indicator if desired.

**Comment by BlakeDraper** [comment]
Published in release 2.16.8.
