### ISSUE TITLE
switching species to "captive" on event details page to trigger popup message and subsequent visibility change 

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1234]
**Describe the bug**
When in create event and marking a species as "captive", it will show a pop up message and then switch event to private if user clicks "Ok" in pop up message. Same does NOT happen in event details page (when you switch to "captive", nothing special happens). Would like event details page to match create event page.

**Comment by BlakeDraper** [comment]
Internal WIM notes;
- Duplicate the `enforceCaptiveRule` from event-submission.component.ts, using Confirm Component to trigger a popup.
- If user accepts the event status change to Private, send an event update API call. The Event Details will reload later anyway when the species is updated.

**Comment by BlakeDraper** [comment]
@JChipault I have updated the WHISPers client to prompt the user about turning the event to 'Not Visible to Public' if they select 'Captive'. But what this does not do is prevent a qualified user from subsequently changing the event back to 'Visible to Public' while the location species maintains its 'Captive' status which violates the business rule. 

How would you like to handle this? We could
A) Prevent the user from marking an event as Visible to Public if there is a Captive location species associated with the event (with a prompt explaining why)
B) Allow the event visibility change, but prompt the user that the visibility for all associated location species will be changed.

I am assuming A is more what you would want, but also open to whatever other suggestions you have.

**Comment by JChipault** [comment]
Actually, what you've done so far is all I was expecting. And what you've done so far will make it match the performance on the create event page. 

It's not a hard business rule that all events with captive animals have to be private, so it's ok if they flip the visibility back to public

**Comment by BlakeDraper** [comment]
Published in v2.16.10.
