### ISSUE TITLE
org/species/location required fields not enforced on event details page

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1238]
**Describe the bug**
On create event, you have to have an event organization, a location, and at least one species. This is good, because these field are required. However, on the event details page, you can delete all the event orgs, you can delete all the species, and you can even delete all the locations and still mark an event complete.

**To Reproduce**
1. Go to the event details page of an incomplete event on the test site that has an org and a species (and thus a location as well)
2. Delete all event orgs
3. Delete all species
4. Switch event to complete. 
5. Note that there's no error message about missing an event org or species
6. Switch event back to incomplete
7. Delete location
8. Switch event to complete
9. Note that there's not error message about missing a location

**Expected behavior**
If you try to delete the last remaining org, species, or location on the event details page, you get a message that tells you that you have to add a new org/spec/loc before you can delete this only remaining one. Maybe after someone clicks "Yes, Delete Event Organization" in the "Delete Event Organization Confirm" popup for the last remaining org, then red text tells them something like "An event must have at least one event organization. Please enter another event organization before deleting."

Same goes for deleting the last species or the last location.

This would be similar to the red text message users get when they try to delete the only number associated with a species at a location (see below for what I get when I deleted "1" in the "known dead" field on the event details page):

![image](https://user-images.githubusercontent.com/49287076/130985021-aa79f50a-d248-4b13-ba21-b1108733a393.png)

**Comment by aaronstephenson** [comment]
Just seeing this now (returning from annual leave).

Re: #1, yes it would actually require a fair bit of work to change the web services, for the reasons Blake enumerated. The "child" objects don't have the same validations as the parent event, because they're being updated/deleted in isolation (not as a giant package of Event data + child object data). We can certainly change that behavior (and probably should, eventually) by looking up the parent and sibling objects and running the business rule validations against all the "recombined" related data.

**Comment by JChipault** [comment]
ok, let's hold on 1 then. Thanks!

**Comment by BlakeDraper** [comment]
@JChipault I added this check which prevents the deletion of the last species from an event location by disabling the delete button and informing the user why they cannot delete it. Let me know what different text you would like there, if any. 

![image](https://user-images.githubusercontent.com/6978380/173140370-499a1fab-b9fc-47df-a985-cce5ebe58d75.png)

**Comment by JChipault** [comment]
Would that "!" message show any time someone looks at a location that only has one species? Or does the "!" message only show up if someone tries to click "delete species" when there is only one species?

**Comment by BlakeDraper** [comment]
@JChipault As written it would show when they expand the location species record to look at it, so yes it is passive or 'just there', but also not visible without a click first. Do you want to lose it? Or just lose the exclamation icon?

**Comment by JChipault** [comment]
Is there a way to have that message show only if they try to click delete? Could we leave delete looking active when there's only one species, but then if they click delete then show this "!" and don't actually delete? Most of our locations only have one species so, if passive, this red text is likely going to feel like a warning on most viewings of the data, even though nothing is wrong with only have one species.

**Comment by JChipault** [comment]
I'm open to other workflows, but would prefer the "!" message (in it's entirety, not just talking about the exclamation point) only shows when a user tries to delete that last species, and does not show when they are just viewing a location that has one species in it (which is most locations)

**Comment by BlakeDraper** [comment]
@JChipault Is it ok to just have "Delete" disabled when only one species? Or do you want the explanation text too?

**Comment by JChipault** [comment]
For consistency in user experience, maybe we just follow what was done for event organization - the delete button is active and the user gets a pop-up with text.

And our text here could follow the text for event org:
At least one species is required for this location. You are attempting to delete the only associated species. Please add an additional species before deleting [fill in the blank species]. 

![image](https://user-images.githubusercontent.com/49287076/173153560-c963f7ee-7a1c-4195-95a9-3884d7dc393a.png)

**Comment by BlakeDraper** [comment]
Published in v2.17.0
