### ISSUE TITLE
Apply same business rules for event and location comments on completed events

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1239]
**Describe the bug**
After an event is marked complete, I can delete a comment at the location level but I can't delete a comment at the event level. 

**Expected behavior**
Allow deletion of comments at both event and location level after an event is marked "complete" (we already allow the addition of location comments and event comments after an event is "complete")

**Comment by BlakeDraper** [comment]
This was less-than-one-line fix. Just removed a check for event complete in the `disabled` property that was leftover from a previously discussed arrangement or perhaps previous iteration of the business rules.

**Comment by BlakeDraper** [comment]
Published in v2.16.10.
