### ISSUE TITLE
Change radio buttons in basemap selector to Material radio inputs

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/whispers#125]
https://material.angular.io/components/radio/overview

**Comment by mitch-wim** [comment]
I don't think we can because it's built into the Leaflet JS.

One option would be moving the basemap selector off the map. We'd just have to figure out where to put it.

**Comment by lprivette** [comment]
should we close this one?

**Comment by BlakeDraper** [comment]
Closing.
