### ISSUE TITLE
can't generate two event detail reports in a row

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1251]
**Describe the bug**
Got an email from a partner with: "I can download and print one event report, but when I try to download a second one it gets stuck on the attached screen."

![image](https://user-images.githubusercontent.com/49287076/148115185-86c8e8bd-81d8-4829-979b-c11344851d36.png)

I was able to reproduce this on the live site. One event details report opens up just fine but if I go to another event and try to download a report, then I can click on "Download Event Report" in the subscreen but that blue bar at the bottom just keeps running and running and no report is generated. 

If I refresh my web browser, then I'm able to download an event details report just fine.

**To Reproduce**
1. Go to any event
2. Click on "generate event report"
3. Click on "download event report"
4. Select either "open" or "save" options (bug seems to happen with either)
5. Note that report was generated
6. Click back button to get to home page
7. go to a different event
8. click on "generate event report"
9. Click on "download event report"
10. Note that the blue bar just keeps running and running
11. Click "Cancel"
11. Refresh web browser
10. repeat steps 8-9
11. Note that report opens or saves fine now

**Comment by BlakeDraper** [comment]
Fixed in v2.16.11. @JChipault please attempt your steps again on the test site (https://whisperstest.wim.usgs.gov/home) to confirm the behavior has been fixed. Thanks!

**Comment by JChipault** [comment]
Looks good! Thanks!

**Comment by BlakeDraper** [comment]
Published in v2.16.11
