### ISSUE TITLE
Circles tab in dashboard has weird pagination

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1267]
**Describe the bug**
NWHC now has more than 20 circles set up and it's hard to navigate the pagination in a way that allows you to just scroll through all the circles

**To Reproduce**
1. Log in as an NWHC user on the live site
2. From home page, go to dashboard.
3. Go to 'Circles' tab 
4. Note that 10 display, even though the bottom of the page says "Items per page: 20". Note that you're told you're on page 0 of 0 and can't scroll to another page.
5. Change to display 10
6. Change to display 20
7. Now you can see 20 on one page but that's not all of them and you still see that you're on page 0 of 0 and can't scroll to another page.

**Expected behavior**
Something similar to "Event Groups" tab would be nice with regard to items per page and ability to scroll through pages of content.

**Screenshots**
This what I see at the bottom when I first click in to the Circles tab:
![image](https://user-images.githubusercontent.com/49287076/169584344-e5be4534-ac1c-4715-9725-449605f0cd38.png)

**Desktop (please complete the following information):**
same issue in firefox and chrome

**Comment by JChipault** [comment]
looks good ton the test site

**Comment by BlakeDraper** [comment]
Published in v2.17.0

**Comment by JChipault** [comment]
@BlakeDraper Don't spend much time on this, but I noticed lately that when I first open the circles tab that it displays 10 rows of data but it says it's displaying 20 on the "Items per page" part at the bottom. It does indeed function as expected though if I toggle it from 20 to 10 or 20 to 5 and back again to 20.

**Comment by BlakeDraper** [comment]
@JChipault I don't seem to be able to re-create this one. This is behavior you are seeing on the test server?

**Comment by JChipault** [comment]
I see it on both test and live. I have more than 10 circles attached to my org's account on both sites so that might make a difference.

**Comment by JChipault** [comment]
Would role matter? I'm in WHISPers admin role in both test and live

**Comment by JChipault** [comment]
To be clear, I wouldn't expect that role would matter, just trying to troubleshoot. But orgs share circles so maybe you looking from a role with org of nwhc would do it?

**Comment by BlakeDraper** [comment]
@JChipault I finally both recreated this and figured out the fix. Will push that to test server soon.

**Comment by JChipault** [comment]
looks good! Thanks!

**Comment by BlakeDraper** [comment]
Done in v2.18.0.
