### ISSUE TITLE
type ahead for adding circles to an event doesn't work as expected

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1268]
**Describe the bug**
NWHC has a lot of circles now and wants to be able to easily select the right circle of collaborators while creating an event or on the event details page but the type ahead function doesn't work well.

**To Reproduce**
1. Log in as NWHC user on live site (or some other user that has access to a lot of circles)
2. Click on "create event"
3. Click "Add Circle" for either read only or read and write access
4. Start typing and note that you only get one option displayed
5. Click on the data entry line and note that now you see a variety of circles but you can't see a blank space to type
6. Start typing the start of the name of the circle you want to access from this pick list
7. Note that it seems to highlight only options that start the letter you're typing but you can't type more than one letter and have it narrow in on the option you want. 

**Expected behavior**
Looking for type ahead here to behave like it does in other areas of the website that have longer picklists (e.g., like species or event diagnosis in the search bar)

**Desktop (please complete the following information):**
same issue in firefox and chrome

**Comment by BlakeDraper** [comment]
@nbaertlein @JChipault 
This component has never had autocomplete ('type ahead' ) implemented. So it is not a bug - it _is_ working as expected. Would you like to add the autocomplete functionality to this component?

Background: WHISPers has two basic types of select drop-downs:
1. Traditional dropdown select which simply shows the list and requires used to scroll. Typing is not supported beyond the first letter. The vast majority of the dropdowns work this way. 
2. Autocomplete dropdown selects - what your team refers to as type-ahead: these allow a live filtering of the options based on user typing. It will continue to filter as the user adds characters. It can also be used as a traditional drop down to simply browse through the options in order.

**Comment by JChipault** [comment]
Got it. Yes, we're likely going to have 50+ circles so let's upgrade to the autocomplete to make this easier to navigate. Thanks

**Comment by JChipault** [comment]
looks good on the test site

**Comment by BlakeDraper** [comment]
Published in v2.17.0
