### ISSUE TITLE
surveillance icons off on home page table and map

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1269]
**Describe the bug**
Surveillance events are marked as diamonds on the home page map but circles on the home page table; should be diamonds all around. Also surveillance events with record status = complete are showing up as incomplete (white center) on the map.  

**To Reproduce**
Steps to reproduce the behavior (OR SEE SCREENSHOT BELOW):
1. Log in to admin account
2. Go to live home page
3. Search for event 200444
4. Note that event shows up as incomplete surveillance on map and complete morbidity/mortality by icon in the table. Should be complete surveillance icon on both map and table.

**Screenshots**
![image](https://user-images.githubusercontent.com/49287076/171682954-d58b34d6-10db-4ba5-903a-e1af67ea7bc5.png)

**Comment by JChipault** [comment]
Actually, you don't need to be logged in to see the bug. I was thinking that 200444 was a private event, but it is not.

**Comment by BlakeDraper** [comment]
Discovered one more bug with this _after_ publishing to test server 🤦‍♂️. Oh well, that's why they call it a test server!

Circle icons for Mortality/Morbidity events not sizing properly on event list table.

**Comment by JChipault** [comment]
Looks good now. Thanks!

**Comment by BlakeDraper** [comment]
Published in v2.17.0
