### ISSUE TITLE
text update in popup for "Request to collaborate"

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1280]
**Undesired Design or Confusing behavior**
We realized that the current text that pops up when someone requests to collaborate on an event assumes that the requester will indeed be added, but that won't always be the case. 

Can we change this text: 
![image](https://user-images.githubusercontent.com/49287076/174865385-873a55f3-f383-46a6-8c67-0b05dc1fc1d2.png)

to read:
You are requesting to collaborate on Event {event_id} and be granted access to non-public event information. This request will be sent to the Event Owner and their organization's administrators, who will consider whether to add you as a collaborator and the appropriate permission level if added (Ready Only or Read & Write). Please include a comment below to introduce yourself and explain why you would like to join this event.

**Comment by BlakeDraper** [comment]
Published in v.2.17.0
