### ISSUE TITLE
diagnosis/species too long to see in full in custom notification setup

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1290]
**Undesired Design or Confusing behavior**
For a diagnosis that is too long to display in full (e.g., the “avian influenza” options), need to add hover over option to see full name when setting up custom notification. This hover over function is in effect for the search pane on the home page but wasn't applied to the custom notification pick list. 

Same for the Species field within custom notification form. 

Would other dropdowns in this notification setup (e.g. state, land ownership) need this hover over feature added if someone is working on a smaller screen??? It's only diagnosis and species that get clipped for me on my laptop.

**Screenshots**
![image](https://user-images.githubusercontent.com/49287076/189191820-b3762093-5165-4536-9151-6a0d97369e09.png)

**Comment by BlakeDraper** [comment]
Implementation live on test server.

**Comment by JChipault** [comment]
looks good!

**Comment by BlakeDraper** [comment]
Done in v2.18.0.
