### ISSUE TITLE
Inactivate add collaborator button on complete events

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1291]
When an event is “complete” on the event details page, inactivate the add collaborator buttons. Currently, it appears that you can add a collaborator to a complete event, but if you try to do so then you get an error message saying that you can’t. 

This is what it looked like when I tried to add Neil as a collaborator on a complete event. For a bit, it looks like Neil has been added, but there's also this error message. 
![image](https://user-images.githubusercontent.com/49287076/189197249-12b107a9-f6d6-4c43-aa14-4072fa89ecd9.png)

When I refresh the browser and thus reload the event, Neil's name is gone.
![image](https://user-images.githubusercontent.com/49287076/189197540-fa34fa5b-5eab-4994-995f-01a006a897a2.png)

**Comment by BlakeDraper** [comment]
Implementation live on test server.

**Comment by BlakeDraper** [comment]
Done in v2.18.0.
