### ISSUE TITLE
add event owner as an option under the collaborator alert feature

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1292]
**Undesired Design or Confusing behavior**
Currently, cannot real-time message the event owner within the interface without putting it under “service request” section. 

**If Possible, Describe a Solution**
Maybe, automatically add event owner as an option in the collaborator alert interface? This would allow for a way to communicate with the event owner in real-time like one can with collaborators via the collaborator alert feature. 

There's likely a more user-friendly solution, but we're looking for "the simplest thing that works" at the moment just to get the functionality available. And then we can assess usability of real-time alerts holistically when we have a usability specialist on board and get feedback from users.

**Comment by BlakeDraper** [comment]
@JChipault In order to not break the expectation that a user manages the event collaborators on their own by adding something to the list they never did select, I suggest something more like depicted below where alerting the event owner is a separate checkbox option. 

![tempsnip](https://user-images.githubusercontent.com/6978380/192609224-cca32392-89fd-4bce-8e02-af9e6a66272d.png)

**Comment by JChipault** [comment]
Thanks for the mock up, @BlakeDraper! We were thinking more like this (though having the event owner at the top of the list is preferred, I just got lazy with my mock up). We talk about the event owner as just another collaborator in the space so it's ok to have them in the list to us, but I do like the idea of distinguishing them as the event owner. 

![image](https://user-images.githubusercontent.com/49287076/192874182-4882b6fe-af5f-4aaf-bc4b-43f66e806f7f.png)

**Comment by BlakeDraper** [comment]
Implementation live on test server.

**Comment by JChipault** [comment]
Looks good! Thanks!

**Comment by BlakeDraper** [comment]
Done in v2.18.0.
