### ISSUE TITLE
reroute users after they create an event

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1293]
**Undesired Design or Confusing behavior**
Currently, after a user creates a new event and clicks "ok" on the popup that gives the event number (screenshot below) they are looped back to another create event page that is empty, and this makes some folks think they have to re-enter their event. 

![image](https://user-images.githubusercontent.com/49287076/190470362-ac535c14-b3e8-4aff-a9bf-21406d2e5a4f.png)

It gets extra confusing if you scroll down to the bottom and see the red warnings... some folks think "wait, I'm being told I got something wrong on the event I just entered" when really the warnings are because there's no data entered for a non-existent subsequent event.

**If Possible, Describe a Solution**
Couple possibilities here and we're wondering what you think. Simple is ok. Maybe we just reroute users to the home page after they click "ok"? Then they'd just click "Create Event" again if they want to create another event. Maybe have that popup that currently has just the "ok" button ask the user if they want to return to the home page or enter a new event (or go to the event page for the event they just created?) and then have them click the option they want?

**Comment by BlakeDraper** [comment]
@JChipault for simplicity for now, I am redirecting the user to Home after completion. I like your idea of an array of choices in buttons, but that will require a bit more dedicated time. Implementation live on test server.

**Comment by JChipault** [comment]
Simple is good. However, I bumped in to an issue here (or maybe it's unrelated?). It's our old friend the JSON error message that tells you the event is not saved, so you click "Save event" button again and then it goes through fine... however, when you look at the home page map, you've got duplicate events (see 171095 and 171096). But then I tried it again and 171097 went without a hitch.

**Comment by BlakeDraper** [comment]
@JChipault That is unrelated. To address that, we'll need more info on what was being submitted. Seems like another case of a parsing error throwing back the error to the client while still proceeding with parsing and processing of the submission. CC @aaronstephenson for awareness.

**Comment by JChipault** [comment]
I tried entering the same event info and did not get the error again. I'll try to be better about getting more data about it if it happens again. 

So #1293 is probably ready for live then whenever we next bundle a push to live

**Comment by BlakeDraper** [comment]
Done in v2.18.0.
