### ISSUE TITLE
don't allow end date in the future

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1294]
**Undesired Design or Confusing behavior**
Currently, folks can enter a location end date that is in the future on both the create event page and  event details page. We initially purposefully allowed this but it's causing more problems than we predicted. 

**If Possible, Describe a Solution**
Don't allow location end dates that are in the future. 

Time zones could make this tricky. If that causes too big of a problem and this is actually a big lift, let us know.

**Comment by BlakeDraper** [comment]
Added validation to prevent end date in future. Implementation live on test server.

**Comment by JChipault** [comment]
Working well on create event and also works when I add a new location to an already existing event - can we apply it to the event details page when I'm editing a pre-existing location too? I was just able to save 10/12/22 as an end date on 171092.

**Comment by JChipault** [comment]
Looks good!

**Comment by BlakeDraper** [comment]
Done in v2.18.0.
