### ISSUE TITLE
Add link within suitable specimen criteria popup

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1317]
Can we add a blue link to this website (https://www.usgs.gov/centers/nwhc/science/diagnostic-case-submission-guidelines) within the "suitable specimen criteria" popup (mockup below) and have the NWHC website open in a separate tab when the user clicks on the link in WHISPers? I modeled this mockup after the link to the user guides and metadata in the "About" section (screenshot below).

![image](https://user-images.githubusercontent.com/49287076/204932151-b9380447-ed30-4778-8c57-96b24e5e946a.png)

![image](https://user-images.githubusercontent.com/49287076/204932343-2688e33e-9e45-4ca8-85e3-4003fd5c7788.png)

**Comment by BlakeDraper** [comment]
Note to self: ensure this covers both Create Event and Edit Event contexts

**Comment by JChipault** [comment]
@BlakeDraper  Within this popup, please remove this parenthetical from the text " (2-3 per species, usually no more than 5-6 total) "

**Comment by BlakeDraper** [comment]
implemented on test server

**Comment by JChipault** [comment]
Looks good on test site. Thank you!

**Comment by BlakeDraper** [comment]
Done in v2.18.1.
