### ISSUE TITLE
Search number affected

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#149]
Need to search range of number affected.   e.g. >500, 5-100, etc.

**Comment by BlakeDraper** [comment]
Do we need a full range selection, or just a `>=` search? Fairly easy to have the web service layer query events with affected number greater than or equal to the number provided. Providing full range options will be some additions to the backend and frontend code.

**Comment by nbaertlein** [comment]
We don't need between function (e.g. don't need 25-100), but we do need the option to use '>=' or '<='.  If we need a quick fix for now '>=' would probably be the most used.   I think the current WHISPers submits the operator and number as a single string (e.g. '>=100', '<=100') to the query.   Don't know if that approach would be worth investigating.

**Comment by BlakeDraper** [comment]
Done for  `>=` and `<=`
