### ISSUE TITLE
Search 'and' statements within event

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#172]
Search 'AND' statements need to be within event, as all 'AND' statements don't appear to yield any results.  Applies to diagnosis type, diagnosis, species, state, and county.  I'm guessing the 'and' statement is looking within record and not within an event as a whole.

**Comment by BlakeDraper** [comment]
@nbaertlein The search already does `AND` style query among parameters in the search. The AND/OR radio buttons are for choosing AND/OR style searching _within_ that parameter.

**Comment by nbaertlein** [comment]
A couple examples of what I'm trying to do:  I'm looking for an event with BOTH Wisconsin and Minnesota locations.  A search for 'Wisconsin' AND 'Minnesota' yields no results, however there are several events with both these states (e.g. event 160575).  Similarly, I'm looking for an event with BOTH mallards and Canada geese.  A search for 'Mallard' AND 'Canada Goose' yields no results, however event 160585 should pop up along with a few others.  From what I can tell, using the current AND within parameter will never yield any results.  Any thoughts on how to correct this?

**Comment by BlakeDraper** [comment]
This bug is now fixed with an update to the webs services.
