### ISSUE TITLE
Unclear meaning of comment in Critical Elements document

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#208]
@nbaertlein it is not clear to me what this comment/request is asking. Can you clarify?
>
![image](https://user-images.githubusercontent.com/6978380/46425969-c2fca780-c702-11e8-9898-673f62772064.png)

**Comment by nbaertlein** [comment]
At event creation there is a button that reads "Review Event Submission" which opens the "Event Submission Confirmation" window containing a summary of the event.  The 'Create event' button in that summary window was not working.
