### ISSUE TITLE
Ensure that dropdown fields can only pass selected value and not string typed by user

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#283]
Should not even allow the display of errant characters, regardless of actual submission value.

**Comment by BlakeDraper** [comment]
Implemented a whole new approach, a more appropriate search-select interface, which eliminates this problem, but waiting to close issue until after those changes applied to all forms across the app. Event submit only for the moment.

**Comment by JChipault** [comment]
@BlakeDraper Can this be applied to search form? Currently, even though there is a drop down list for each search category, the user is able to enter in free text. Since this seems to generate an error message about the search criteria being too big, is there a way to block the ability to enter free text?  Also the "clear selection" button does not clear out the free text

**Comment by JChipault** [comment]
Still wondering how easy it would be to take the code that was applied to create event and use it for the search fields. User can type in "bats" for species and feel like they are searching for only events with bats when really the system isn't acknowledging that free text at all.

**Comment by BlakeDraper** [comment]
Do we want to spend effort 2 money and time to implement this? A free text entry does not show up in the actual query values, which should give a hint to the user that it has not actually been selected for a query. 
![image](https://user-images.githubusercontent.com/6978380/61645827-3ad59780-ac6d-11e9-8cec-ad150c87f9b4.png)

If we did it to species, we would probably want to do it to all the fields on the search so that the experience there is consistent. This will take time to implement and test. I am just trying to be careful about these continuing improvements that don't get us close to Effort 2 goals.

**Comment by nbaertlein** [comment]
If it's not an easy plug and play from the other drop-downs, we should hold off.  We outline upgraded search capabilities in effort 2 so we can revisit then.
