### ISSUE TITLE
Fix legend

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#314]
Not sure when this happened because I have not visited the legend in a while, but I suspect the big set of style changes from last week may have accidentally broken the legend.

![image](https://user-images.githubusercontent.com/6978380/48571234-f9197380-e8cb-11e8-9395-299a90f16e27.png)

**Comment by BlakeDraper** [comment]
FYI, this is on the home page map only. Event details map legend seems fine.

**Comment by esmyers** [comment]
/*the inner scrollbar*/
.legend .mat-expansion-panel-body {
    max-height: 210px!important;
    **overflow: auto!important;**
}

**Comment by esmyers** [comment]
MIIIITCH!!!!!
