### ISSUE TITLE
Make the centroid explanation text more prominent

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#324]
Users have complained that the text is not easy to notice, could lead to misinterpretation. 

![image](https://user-images.githubusercontent.com/6978380/48739770-96511080-ec1a-11e8-9cf3-159b8f0a986d.png)
Suggestions include elsewhere on the map on on the map title bar.

**Comment by lprivette** [comment]
Took a stab at this.

I added it to the legend title as a mat warning icon with a tooltip containing "Map shows centroid of county where event occurred."

Might need some css work (positioning, removing the underline).

![image](https://user-images.githubusercontent.com/23640741/48858098-8fe0a700-ed88-11e8-8749-9d27602275d1.png)

**Comment by lprivette** [comment]
Maybe change to info icon.
![image](https://user-images.githubusercontent.com/23640741/48860828-00d78d00-ed90-11e8-8ad5-b402c65e152a.png)

Hans doesn't like it

**Comment by BlakeDraper** [comment]
This might qualify as less prominent, but its all in the cooperators opinion

**Comment by HansVraga** [comment]
I wonder if this information:
>Map shows centroid of county where event occured.
Should be with this information:
![image](https://user-images.githubusercontent.com/12058013/48862683-11d6cd00-ed95-11e8-83ae-5484c81f6354.png)

**Comment by lprivette** [comment]
Then they'll have to scroll to the bottom of the legend in order to find it. 

Maybe move that text to the top of the legend? or is it too much text?

**Comment by mitch-wim** [comment]
What about this? https://cl.ly/e9c80f3b7b04

**Comment by BlakeDraper** [comment]
I like it.  Please commit.

**Comment by BlakeDraper** [comment]
Done with PR #382
