### ISSUE TITLE
Display name of saved search to user

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#336]
how should we display the search name?

Keep field name left justified and value right justified like all the other fields and values? Is it important enough to keep it left justified with "NAME: {search.name}" or just "{search.name}?

Something else?

![image_170](https://user-images.githubusercontent.com/5325440/49035003-6220a700-f168-11e8-8528-42fad6d02448.png)

**Comment by BlakeDraper** [comment]
Home page and user dashboard

**Comment by njestes** [comment]
how should we display the search name?

Keep field name left justified and value right justified like all the other fields and values? Is it important enough to keep it left justified with "NAME: {search.name}" or just "{search.name}?

Something else?

**Comment by BlakeDraper** [comment]
@njestes  So I would actually leave out the word 'Name' - meant to be a minor extra convenience, and I think would be better displayed in a more implicit way. So maybe put it where you have it, but change the text style a bit to differentiate it. italics, maybe?

**Comment by BlakeDraper** [comment]
Done with PR #382
