### ISSUE TITLE
Event details page is loading at middle of page instead of top

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#350]

**Comment by BlakeDraper** [comment]
@mitch-wim maybe you can look at this one. It only happens when the user clicks to the event details page form the search results table, but doesn't happen if you just reload the page. Seems like it has something to do with # URL stuff. The actual "#" is hidden in WHISPers, but its using that basic method in the background to do the Angular routing stuff with the event detail ID in the URL. 

Possible lead: https://stackoverflow.com/questions/35471263/browser-jumps-to-middle-of-page-when-loading-html-file

**Comment by mitch-wim** [comment]
I have to fix this with every angular project I have and I can't believe it's not built in.

Anyway, I followed and modified this and it's working: https://blog.lysender.com/2018/07/angular-6-add-scroll-to-top-when-route-changes/
