### ISSUE TITLE
search for 2 diagnoses linked by AND operator results in service error 500

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/whispers#352]
![image](https://user-images.githubusercontent.com/2495167/48804232-ac71d600-ecd9-11e8-826a-013bcf59a37b.png)

the OR operator works even if it doesn't return data.  

https://whispersdev.wim.usgs.gov/whispersservices/eventsummaries/get_count/?no_page&start_date=2018-03-31&end_date=2018-07-31&start_date=2018-03-31&end_date=2018-07-31&diagnosis=435,277&and_params=diagnosis_type

as opposed to:

https://whispersdev.wim.usgs.gov/whispersservices/eventsummaries/?no_page&start_date=2018-03-31&end_date=2018-07-31&start_date=2018-03-31&end_date=2018-07-31&diagnosis=534,520

**Comment by esmyers** [comment]
Not 100% sure on this one, but it is worth a look.  I know some combinations of search will not return results, but I'm not sure about getting the 500 error.

**Comment by BlakeDraper** [comment]
There was a client-side error which was sending the `and_params`  as `diagnosis_type when a diagnosis AND was selected. I fixed that, but seeing a new error coming from the backend. 

Issued out here: https://github.com/USGS-WiM/whispersservices_django/issues/187

**Comment by BlakeDraper** [comment]
Fixed with backend update.
