### ISSUE TITLE
Whitespace below footer

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/whispers#360]
On a large monitor:
Smaller screenshot:
![image](https://user-images.githubusercontent.com/12058013/48844324-73804280-ed67-11e8-9009-45bd09c423f1.png)
Full screenshot:
![image](https://user-images.githubusercontent.com/12058013/48844342-901c7a80-ed67-11e8-97bb-e10cd97c336f.png)

**Comment by mitchas** [comment]
Oh, easy fix. Just have to set a min-height for the content. I'll get it.
