### ISSUE TITLE
Set a maximum zoom level for search results

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/whispers#364]
The below image is the result of a search, it zoomed into level 18. This is too close to really provide any context in the map. Suggest setting a maximum zoom level (from the result of a search) as 10, and let the user zoom in/out from there.

![image](https://user-images.githubusercontent.com/12058013/48857581-362bad00-ed87-11e8-8b42-27a90fea9900.png)

**Comment by BlakeDraper** [comment]
Done with PR #382
