### ISSUE TITLE
Create New Contact

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/whispers#376]
Entered the following info and got the 'contact created'! message. Person is not available to then add as a contact to the event.
![image](https://user-images.githubusercontent.com/12058013/49037333-f6e6cd00-f187-11e8-87ce-87212eead028.png)

**Comment by BlakeDraper** [comment]
Easy fix. Just applied to my working branch.

**Comment by BlakeDraper** [comment]
Done with PR #382

**Comment by BlakeDraper** [comment]
Accidentally marked as done.

**Comment by BlakeDraper** [comment]
Done in code

**Comment by BlakeDraper** [comment]
Done with PR #450
