### ISSUE TITLE
Easy to save duplicate events

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/whispers#379]
When someone is creating an event and they click "Save" they get a success screen with "OK" dialog. If you click outside of that screen you go back to the event screen where you can click "Save" again to create a duplicate. Can we do something to avoid duplicates in this way?

**Comment by HansVraga** [comment]
(see Events 170544 and 17055; also events 170546
170547
170548

**Comment by BlakeDraper** [comment]
good call - will need to clear the form after success.

**Comment by njestes** [comment]
Or we could route them to the event details page for that event where they can then edit it.

**Comment by HansVraga** [comment]
Really like Nicks idea. Logical workflow

**Comment by BlakeDraper** [comment]
And now I better understand exactly what you were saying Hans. I set the disableClose property on the dialog so user cannot leave it without clicking OK, which then triggers the form reset.
