### ISSUE TITLE
Event Creation - added 0.1 to number of known dead

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/whispers#380]
For Event 170546 (and duplicates 170547 and 170548) I was able to add "0.1" by typing into the "Known Dead" Event Location Field. I added no more values to the estimated dead/sick/estimated sick fields.
Event saved, JSON showed .1 for the value.

Value now reads as 0: https://test.wim.usgs.gov/whispersdev/event/170546

But we probably want to force positive integers?

**Comment by aaronstephenson** [comment]
Just some color commentary: All the "count" fields are defined as (nullable) integers in the web services, so 0.1 was rounded down to 0.

**Comment by BlakeDraper** [comment]
Ugh. Probably need to write a custom validator to check `isInteger`. Should be a built in validator. thanks Obama/angular dev team

**Comment by HansVraga** [comment]
By adding just 0.1 as a value am I circumventing any business rules when the event location now has 0 for known dead and blanks for those other values?

**Comment by BlakeDraper** [comment]
Done
