### ISSUE TITLE
Species slow to load

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/whispers#384]
I can't tell when it has loaded, and if I start typing too soon the filter doesn't work and I have to erase what I've typed to get it to work.
![image](https://user-images.githubusercontent.com/35497731/49042638-5051fa80-f18e-11e8-8b13-3e6f4ce4e7c3.png)

**Comment by njestes** [comment]
@BlakeDraper can we add a loading spinner and disable the input until species are loaded and then come back to this in the next effort?

**Comment by BlakeDraper** [comment]
@njestes  Yes, we should come up with a consistent solution for this whole component. I am using a basic spinner inside the form in other areas of the app, so will do that here too.
