### ISSUE TITLE
More Clearly Mark Incomplete Events

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/whispers#387]
Maybe say "[Start date] thru present" or something? There's nothing on this page that says it's incomplete/ongoing other than the lack of an end date unless you're a privileged user.
https://test.wim.usgs.gov/whispersdev/event/170442
![image](https://user-images.githubusercontent.com/35497731/49044014-34e8ee80-f192-11e8-8a0c-6d09cc8f2829.png)

**Comment by BlakeDraper** [comment]
Done
