### ISSUE TITLE
Can't See My Own Private Events

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/whispers#388]
Are we supposed to be able to see our own events in the main search? I created an event that is Not Visible to the Public, and tried to search for it. I was logged in, but it wouldn't show up until I changed it back to Visible to the Public.  I could still see to the page for it (e.g. https://test.wim.usgs.gov/whispersdev/event/ + [eventnumber])

**Comment by HansVraga** [comment]
Commenting to confirm this is the case for me as well.

**Comment by BlakeDraper** [comment]
By design
