### ISSUE TITLE
Create Event-Verify lat/long locations are in correct area?

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/whispers#396]
Might be too complicated to carry out, but it's possible they have the lat/long coordinates reversed, or wrong.

Otherwise, they can check the Event Details page to verify they had the coordinates correct.  Image from https://test.wim.usgs.gov/whispersdev/event/170557.  Event Location in Alaska but location coordinates in Minnesota.

![image](https://user-images.githubusercontent.com/35497731/49088940-087bb380-f220-11e8-9f24-10a309527064.png)

**Comment by BlakeDraper** [comment]
Yeah we may impose some sort of check eventually but definitely a wishlist-type thing for now.
