### ISSUE TITLE
Create Event - Species Diagnosis spacing

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/whispers#398]
Small issue, but spacing is off
![image](https://user-images.githubusercontent.com/35497731/49090276-fb13f880-f222-11e8-8354-1b31077b56b0.png)

**Comment by BlakeDraper** [comment]
Do you mean the width of the input?

**Comment by kjacobsen16** [comment]
The "Number Assessed" and "Number with this Diagnosis" are missing space to the left.  The others ("Basis of Diagnosis", etc.) are tabbed more. Hard to see in image

**Comment by BlakeDraper** [comment]
Ah gotcha. Yeah I think they  re just lacking the class that gives the other a 10px margin. Thanks!

**Comment by BlakeDraper** [comment]
done
