### ISSUE TITLE
Event Details - Age Basis/Sex Bias not showing up in Privileged Data

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/whispers#402]
Age Basis/Sex Bias showing up on event page (see Species Details- https://test.wim.usgs.gov/whispersdev/event/170561) but not in Privileged Data section (see "Species at this Location" for Location 1 in Event Location Details). It cannot be edited either.
![image](https://user-images.githubusercontent.com/35497731/49093397-9c05b200-f229-11e8-950c-189dc02ba3d2.png)

![image](https://user-images.githubusercontent.com/35497731/49093375-914b1d00-f229-11e8-8642-a030c4f9bb34.png)

**Comment by BlakeDraper** [comment]
done
