### ISSUE TITLE
Neet to trap auth failure 

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/whispers#423]
Failure to authenticate opens a secondary login popup
![image](https://user-images.githubusercontent.com/8713714/49251747-63a7d480-f3df-11e8-83d1-dd951c9b6e6b.png)

**Comment by BlakeDraper** [comment]
Also mentioned as a problem by Neil
> Incorrect login credentials.  If the wrong username and/or password is provided a new browser pop-up opens and asks for username and password (see attached).  Could we give an error message instead stating something like: "Username and/or password not recognized. Please try again or go to X to request new password"

**Comment by BlakeDraper** [comment]
Will need to be addressed at server level. Further discussion here: https://github.com/USGS-WiM/whispersservices_django/issues/217

**Comment by BlakeDraper** [comment]
Will work on addressing this by updating services to return a 403 error for auth failure.

**Comment by BlakeDraper** [comment]
Done on backend.
