### ISSUE TITLE
Event Location - Next Button not prominent enough

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/whispers#424]
After creating a few issues, I find myself 'hunting' for the next button, and as a group exercise we had to coach people to use the next button. We should make it more prominent, make it clear it's a button.
![image](https://user-images.githubusercontent.com/12058013/49251697-049e8b80-f3f0-11e8-8246-ca3a6b941498.png)

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by BlakeDraper** [comment]
Made button more prominent CSS class. Done in code.
