### ISSUE TITLE
Invalid username/password for some anonymous requests possibly due to empty Authorization header

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/whispers#427]
Getting 403 errors for some lookup table requests when not logged in (requests made as anonymous user). I'm only seeing this for the following endpoints, but it might be worth looking at others too:
- sexbiases
- contacts
- agebiases
- commenttypes

Through some testing with a REST client, this only seems to happen when an Authorization header is included in the request and the username and password values are blank. When the Authorization headers are not included, there are no errors.

Screen capture of the browser console:
![invalid_username_password](https://user-images.githubusercontent.com/8713712/49253269-d4ed8480-f3eb-11e8-8b8f-c6831f9a8cee.png)

**Comment by BlakeDraper** [comment]
AH, yup. A relic of some lazy copy/pasting of header config objects. Easy fix.
