### ISSUE TITLE
Add Basic Google Analytics functionality

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/whispers#445]
Please add the Basic f functionality to the whispers client.
Add events at your desecration, but the plan will be to more completely plan our click events at a future time.

**Comment by lprivette** [comment]
https://docs.google.com/spreadsheets/d/1yydLKTtr3qAGesSZZMlA3w8JOiZQBtjvCahwKi9QGKw/edit#gid=0

**Comment by BlakeDraper** [comment]
Done with PR #459
