### ISSUE TITLE
Reported: undetermined and suspect showing at same time

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#469]
This combo should never happen. Event 170611. Home page search results - eventsummaries endpoint. Also check eventdetails.

**Comment by BlakeDraper** [comment]
@aaronstephenson I just went and checked this event and I am not seeing this happen. Was this addressed by one of your recent pushes to whispersbeta?

**Comment by aaronstephenson** [comment]
Undetermined and Pending should never be suspect. That rule has been enforced for months and I haven't changed it. Just a guess, but perhaps the users were seeing a refresh inconsistency?

**Comment by BlakeDraper** [comment]
@nbaertlein any insight into this issue? I was unable to recreate it (i.e. see an event details page showing "Undetermined suspect") for an event diagnosis, even looking at the specific event ID that was reported to be showing it.

**Comment by nbaertlein** [comment]
We cannot seem to replicate either.  I've double checked the data and all records appeared to be fine as well.  I'm guessing there was a record or two that may have slipped through early on, but resolved themselves via the deployed business rules when edits were made.  Lets mark this resolved and I'll let you know if we ever see it again.

**Comment by BlakeDraper** [comment]
Thanks @nbaertlein
