### ISSUE TITLE
Frozen screen and error message on create event

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#487]
From Kim M:
1.  Screen froze when I saved a newly created event.  
Pop up that event  #170653 was saved concurrent with a red error message in the background that the event needs a start date".  The event had a 18 Dec 18 start date. (screenshot 1)

2.  Second try, create event
Drop down not working on add contact.  clicking on the add contact button opens to the text line being red and unresponsive to clicking on drop down or line for typing.

I was able to create a contact and then add that contact.

Pop up that event 170654 was saved but scrolled down and same error message re start date at the bottom of the screen.  (screenshot 2 and code for screenshot 2)

3.  Third try, create event
 Save event pop up - 170655 but then the screen froze. (screenshot 170655)

![frozen screen 18 dec 18](https://user-images.githubusercontent.com/38669574/50170328-4f0b7d80-02b5-11e9-8d43-7a4d36e0f8ad.PNG)
![screenshot 2 18 dec 18](https://user-images.githubusercontent.com/38669574/50170337-529f0480-02b5-11e9-8a4e-babbf504696c.PNG)
![code for screenshot 2 18 dec 18](https://user-images.githubusercontent.com/38669574/50170341-55015e80-02b5-11e9-845e-8100f3ab1bf5.PNG)
![screenshot frozen screen 170655 18 dec 18](https://user-images.githubusercontent.com/38669574/50170354-5d599980-02b5-11e9-9ac6-bc2bd5e433c1.PNG)

**Comment by BlakeDraper** [comment]
Addressed with refresh of page after submit.

**Comment by BlakeDraper** [comment]
Done with PR #490
