### ISSUE TITLE
Save event

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#499]
Unable to save event on LIVE beta (https://whispersbeta.wim.usgs.gov/whispers/eventsubmission)
Error message received: "Error. Event not Submitted. Error message: {"Log-Id":"168ce2a4367-d9f460d4","Request Time":"2019-02-08 17:31:42 GMT","Error":"The specified URL cannot be found "

**Data**: Attached
[Failed_save_data_20190208.txt](https://github.com/USGS-WiM/whispers/files/2846570/Failed_save_data_20190208.txt)

**Description:**
" I spent about 25 minutes entering it in chrome and then when I hit save I got the below error. I hit save again and got the error again. Then I left the site for 5-10 minutes and when I circled back to the site I hit save again and that time it started to process and the blue bar that goes along the bottom of the form got halfway through and then everything froze. I let it sit for 10+ minutes and still the blue bar was halfway across the screen. I then toggled the radio dial for services and then hit save again and again got the error message.

**Comment by BlakeDraper** [comment]
@nbaertlein This is the EROS error we were getting in December.  We'll need to reach out to them.

**Comment by BlakeDraper** [comment]
EROS is researching. It seems it had to do with the size of the request (the number of items in the JSON submission), and they are looking to increase that limit, or, ideally, exempt this application from the requirement.

**Comment by BlakeDraper** [comment]
They have increased the limit to 1000, we will see if we can lobby for a total exemption.
