### ISSUE TITLE
Save search

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#501]
Cannot no save search.  Getting the below error.  Was logged in as public user 'neilbpublic'.

Error. Search not saved. Error message: {"detail":"CSRF Failed: CSRF token missing or incorrect."}

**Comment by BlakeDraper** [comment]
We believe this was a result of some a firewall changes EROS was making at the time of the submission. Will keep issue open for a few days in case the same behavior occurs again.
