### ISSUE TITLE
Save event error

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#508]
Upon saving an event the application hung and an error popped up about the event not being submitted and not being 'trusted'.  HOWEVER event was eventually submitted (https://whispersbeta.wim.usgs.gov/whispers/event/200016).  
See narrative below:

"Went to save an event I just created and hit the save button, nothing changed for about a minute then an error message popped up from the bottom of the screen that read something like 'Error event not submitted, is trusted 'true'' or something along those lines, it stayed for about 15 seconds then disappeared.  The rest of the screen didn't change. No email had been received either. After I called you (Neil) a few seconds in an email came in notifying of the event and when I checked the event all the data I entered appeared to be there. "
(Bob Dusek 2/22/19)

**Comment by BlakeDraper** [comment]
Another case of the EROS - triggered error.

**Comment by BlakeDraper** [comment]
Closing this issue because it can only be remediated through continued reporting to EROS on their web server configuration issues, which we are doing.
