### ISSUE TITLE
Event organization CRUD

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#509]
Need ability to add, edit, delete event organization in edit event form.
Version 2.0.0-beta.9

**Comment by BlakeDraper** [comment]
@nbaertlein the ability to add and delete an event organization exists on the event details page. User can add and delete an event organization. We moved it out of the edit-event form for data schema reasons. 

![image](https://user-images.githubusercontent.com/6978380/53374183-41a9e980-391d-11e9-9fc3-bc1b634f4490.png)

**Comment by nbaertlein** [comment]
Ah got it.  Thanks.
