### ISSUE TITLE
Species count at completion

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#512]
Was allowed to mark an 200015 as complete even though there were not numbers for every species. This violates business rule:
"For morbidity/mortality events, there must be at least one number between sick, dead, estimated_sick, and estimated_dead per species at the time of event completion. (sick + dead + estimated_sick + estimated_dead >= 1)"

**Comment by BlakeDraper** [comment]
@nbaertlein I just tested this scenario on the dev DB (event 200015 only exists on the Production beta DB) and I received an error message and was prevented from updating the event to Complete:
<img width="302" alt="capture" src="https://user-images.githubusercontent.com/6978380/53431396-10c9c300-39b6-11e9-965f-75851cbd0c0e.PNG">

This was with a species with no numbers, like you describe:
![image](https://user-images.githubusercontent.com/6978380/53431449-2f2fbe80-39b6-11e9-9493-1c97a9df15fa.png)

When I attempted to mark that event 200015 as Complete on the Beta Prod client (and DB), I actually got a 500 error, which we are now looking into (but is probably yet another EROS anomaly). The point is, in no case was I permitted to violate the business rule. I may have to do a screenshare with you to see how this is happening for you while I cannot recreate it myself.

**Comment by nbaertlein** [comment]
I'll check with Jenny to see if she can recreate. Thanks.

**Comment by nbaertlein** [comment]
@BlakeDraper On a related note, in which you may be addressing already, we got the following error last week when toggling between complete to incomplete, then back again...
Error. Event not updated. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by nbaertlein** [comment]
@BlakeDraper 
"Complete" business rule violation was from event submission page upon submitting a complete event.  
Sample data below.  

"It's during create event that it's not being enforced. I just created 200017 in live beta. form values below.
Form Status: VALID

 {
  "event_reference": "2018-200",
  "event_type": "1",
  "complete": true,
  "public": true,
  "staff": "6",
  "event_status": "7",
  "quality_check": null,
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [
    {
      "org": "914"
    }
  ],
  "new_service_request": {
    "request_type": 0,
    "new_comments": []
  },
  "new_event_diagnoses": [
    {
      "diagnosis": "8"
    }
  ],
  "new_comments": [],
  "new_superevents": [],
  "new_event_locations": [
    {
      "name": "Panama City Beach",
      "start_date": "2018-09-06T05:00:00.000Z",
      "end_date": "2018-09-25T05:00:00.000Z",
      "country": "30",
      "administrative_level_one": 10,
      "administrative_level_two": 320,
      "latitude": null,
      "longitude": null,
      "land_ownership": "7",
      "gnis_name": "",
      "gnis_id": "",
      "site_description": "",
      "history": "Summary spreadsheet sent from SCWDS. CC18-427",
      "environmental_factors": "",
      "clinical_signs": "",
      "comment": "",
      "event_type": 1,
      "new_location_species": [
        {
          "species": 297,
          "population_count": null,
          "sick_count": null,
          "dead_count": 5,
          "sick_count_estimated": null,
          "dead_count_estimated": 21,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": [
            {
              "diagnosis": 8,
              "cause": 1,
              "basis": 3,
              "suspect": false,
              "tested_count": 1,
              "diagnosis_count": 1,
              "positive_count": null,
              "suspect_count": null,
              "pooled": false,
              "new_species_diagnosis_organizations": [
                914
              ]
            }
          ]
        },
        {
          "species": 301,
          "population_count": null,
          "sick_count": null,
          "dead_count": null,
          "sick_count_estimated": null,
          "dead_count_estimated": null,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": []
        }
      ],
      "new_location_contacts": [
        {
          "contact": 4308,
          "contact_type": 2
        }
      ]
    }
  ]
} "

**Comment by BlakeDraper** [comment]
Fixed on backend and validation added to client event submit form.

**Comment by BlakeDraper** [comment]
Done with #514
