### ISSUE TITLE
Tabbing through drop downs

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#513]
The behavior of the drop-down boxes on the submission form (e.g.,, county, state, species) differ when selected via tab vs click.  A mouse clicked field allows for the desired in-string search, however a tab selected field only allows a search of the first character.  Is there anyway to have a tab selected box behave the same as a box that has been clicked on?

**Comment by BlakeDraper** [comment]
@nbaertlein If a user is tabbing through the form, they will need to press Enter to open the search-select element. The `Enter` keystroke accomplishes the same thing as a mouse click. There is not a way to auto-open the search-select on focus .

So for users who prefer to tab and avoid the mouse, the keypress sequence is simply `Tab` >  `Enter` > *type in search term* > arrow key to selection > `Enter` to select > `Tab` to next field > `Enter` ...etc...

**Comment by nbaertlein** [comment]
Thank you.
