### ISSUE TITLE
LIVE event organization is not showing

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#521]
Event organization was added upon event creation, but is not displaying.  See event 200022.  I've confirmed the data are in the db, but just not displaying.
![200022_org](https://user-images.githubusercontent.com/38669574/53825580-3ddd1f00-3f3c-11e9-9241-d6f84989ea61.png)

**Comment by BlakeDraper** [comment]
Unclear what was happening but it no longer is happening at this time.
