### ISSUE TITLE
Edit/add location errors on LIVE v10

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#525]
Reference: https://whispersbeta.wim.usgs.gov/whispers/event/200023

1.) Tried to add a second location to 200023 and got this error:
"Error. Event location not created. Error message: {"error":"Server Error (500)"}   "

2) Tried to edit existing location on 200023 and subform hangs with no changes submitted.
Edit location functionality appears to work on other locations, just not 200023

**Comment by nbaertlein** [comment]
Follow up:
ADDing new location was allowed when eliminating lat-long, however the form still hangs when trying to edit.

**Comment by BlakeDraper** [comment]
This was a bug occurring only in the situation where an event location End Date was blank. The blank value was being interpreted by the datepicker in a way that caused an error on the date conversion logic.   Fixed in code.
