### ISSUE TITLE
Token error on edit event

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#527]
Was attempting to update event reference on https://whispersbeta.wim.usgs.gov/whispers/event/200030 and got the following error:

'Error. Event not updated. Error message: {"detail":"CSRF Failed: CSRF token missing or incorrect."}'

**Comment by BlakeDraper** [comment]
We are not exactly sure of this cause of this one and I cannot recreate it now, but we have a theory for a minor tweak to the web service response headers (explicitly including `Content-Type:application/json`) which we hope will prevent this seemingly intermittent problem in the future. Done in code.
