### ISSUE TITLE
Diagnosis unique combinations (no duplicates)

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#532]
No duplicates are allowed for:
Table event_diagnosis: event_id - diagnosis_id combination
Table species_diagnosis: location_species_id - diagnosis_id combination
Table diagnosis_organization: species_diagnosis_id - organization_id combination

Also apply on front end.

**Comment by JChipault** [comment]
currently, can have more than one "pending" in event diagnosis

**Comment by JChipault** [comment]
think species_diagnosis: location_species_id - diagnosis_id combination is working

**Comment by JChipault** [comment]
species_diagnosis_id - organization_id combination was set up as a silent fail deliberately. We can leave that for now and revisit during usability testing

**Comment by BlakeDraper** [comment]
- [ ] prevent duplicate event diagnoses

- [ ] prevent duplicate species diagnoses

- [ ] prevent duplicate diagnosis organization

**Comment by BlakeDraper** [comment]
Done in code

**Comment by JChipault** [comment]
You maybe did too good on the species diagnosis.... now if I enter a species diagnosis and save it, then go back to the subform via the edit button and try to change information (e.g., add a lab) I get a warning "The selected diagnosis has already been selected for this species at this location." and the save button is greyed out... probably because it thinks I'm trying to add a new species diagnosis record, but I'm just trying to edit the one already present.

**Comment by BlakeDraper** [comment]
@JChipault I see what you mean. The most expedient way to fix this is to remove the ability to change the diagnosis selection itself when editing a species diagnosis. The other fields would remain editable, but if a user added a specific diagnosis in error, to remove it, they would have to delete that instance and create a new one. This is how species diagnosis currently works on the event details page so it would actually be more consistent. 

There is a big cost to having all aspects of this very complex form infinitely editable, especially when they must intersect with a complex matrix of business rules logic. Are you all OK with removing the editability of the diagnosis selection within the species diagnosis subform in the event submission form?

**Comment by JChipault** [comment]
Yes, that sounds good. Trick is that currently I'm not trying to edit the actual diagnosis, I'm just trying to edit other things on that popup (e.g., number assessed) and the "save changes" button is grey and the "The selected diagnosis has already been selected for this species at this location." message is present. Making it like the event details page sounds good

**Comment by JChipault** [comment]
Version 16 - Getting two "undetermined"s in dropdown at event diagnosis level on event details page if "undetermined" is entered at the species level and event in "incomplete" status
![image](https://user-images.githubusercontent.com/49287076/58661274-13a5be00-82ed-11e9-84de-6e744be41619.png)

**Comment by JChipault** [comment]
still true in v2.2.0

**Comment by BlakeDraper** [comment]
Another edge case - now doing a check for undetermined already being a species diagnosis before adding to the possible event diagnoses list on load and on refresh. done in code.
