### ISSUE TITLE
Duplicate events created with error

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#534]
Similar to past error, getting an error of event not saved, but is creating an event. See: https://whispersbeta.wim.usgs.gov/whispers/event/200039

From reporter:
"The whispers beta is still giving the event not saved error, but then apparently creating the event.  Can you please delete event 200039?
I clicked save event twice and got the error each time, but then the auto email indicating the event creation was sent to nwhc-epi 5min later each time."

**Comment by BlakeDraper** [comment]
Relayed to #537

**Comment by BlakeDraper** [comment]
Also related to #542

**Comment by BlakeDraper** [comment]
Fixed with refactor.
