### ISSUE TITLE
old species & species diagnosis tab back --> JSON

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#540]
On 3/22/19 in test beta 10: Went to add second location to an event (170706) and it presented me with old flow where "species & species diagnosis" were one tab and comments came as second tab. Could not save because got this error: Error. Event location not created. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by BlakeDraper** [comment]
It isn't that this reverted, its that the new flow was never added to the Add Event Location component. Has been done now though. Error also fixed.
