### ISSUE TITLE
Confused authorization

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#551]
Logged into test site (https://whispersbeta.wim.usgs.gov/test/whispers/home) and when opening the live beta site (https://whispersbeta.wim.usgs.gov/whispers/home) on another tab, user appeared to be logged in as the user info showed on home page and dashboard.  

Despite the appearance of being logged in, user could not access event data and as "Event 1234 not found in the WHISPers database" was shown across the top of the event detail page.  No publicly available data could be seen.

**Comment by BlakeDraper** [comment]
@nbaertlein This is not an issue we are going to pursue fixing. The existence of two parallel applications is a temporary state of affairs which will not be the case in production, so this is entirely moot once WHISPers v2 is released. It is also difficult to determine the accuracy of the User's report. The login details are cached per URL by the browser's rules, so it is not possible for the credentials to be somehow partially shared between two fully separate applications. This sounds like possible user error/confusion between states of login between the two applications.
