### ISSUE TITLE
Event location review incorrectly marking a Location complete && Form Status is incorrectly marked as VALID

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#555]
![image](https://user-images.githubusercontent.com/23640741/57199952-2974cd00-6f53-11e9-8874-3871cd2a5452.png)

I noticed that the Form Status was `valid`, ~so maybe the "one comment field must have a value" requirement is old?~ tried submitting it anyways but the one comment thing is def required 
![image](https://user-images.githubusercontent.com/23640741/57200103-385c7f00-6f55-11e9-8601-c9fe591155a7.png)

**Location Details - what was entered**: 
![image](https://user-images.githubusercontent.com/23640741/57199980-840e2900-6f53-11e9-9e9f-e32ba37fc525.png)
**Species - what was entered**:
![image](https://user-images.githubusercontent.com/23640741/57199986-99835300-6f53-11e9-9f07-8912249f1e4a.png)

**Comment by lprivette** [comment]
Unable to recreate this bug now. Maybe close @BlakeDraper ?

**Comment by BlakeDraper** [comment]
Yes, I think I may have actually fixed this one and neglected to circle back to the issue since it was not in the Kanban board.
