### ISSUE TITLE
v12 froze

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#556]
On Create Event, selected "add individual" (I think) from read and write access and site froze with funky subform with two "cancel"s on it and a couple of the floating black rectangles. Screen shot.
![image](https://user-images.githubusercontent.com/49287076/57249539-d5c5ba80-700a-11e9-804e-34d7caafbc03.png)

**Comment by JChipault** [comment]
Was able to recreate later in the day by clicking add individual under read and write access, then add circle, then add individual again

**Comment by BlakeDraper** [comment]
Fixed with PR #558
