### ISSUE TITLE
Event group - floating boxes

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#559]
Bug report #697
having trouble clicking selecting and deselecting event groups in Event Groups tab. Have to click on checkboxes a lot to activate or inactivate. Sometimes works smoothly and sometimes clogs up. Also had random floating black rectangle appear for a bit (similar to what we used to see when had "wonky" event details screen)

**Comment by BlakeDraper** [comment]
This was the result of the same problem described in #560, which was bad data. Fixed now with the removal of offending records.
