### ISSUE TITLE
Event Group - dashboard error

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#561]
Bug report #694
Created Event Group G11 with justification of "new test text", then deleted G11 in Event Groups tab, then went to Events tab and at the top it said "Current Event Group Selection: G11 new test text" even though I have deleted G11 and when I toggle back to Event Groups tab, there is no G11 there. Even if I make a new group (G12), I still have G11 showing on at the top of the Events tab, regardless of whether or not I have events selected. When I try to "Add Selection to Event Group G11" I get an toast message that says: Error. Event Group not updated. Error message: {"detail":"Not found."}.  screen shots

**Comment by BlakeDraper** [comment]
Fixed in code
