### ISSUE TITLE
Event Group - NWHC viewability

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#562]
Bug Report #693
Do not show the "Event Groups" tab in dashboard to anyone outside of NWHC as per requirements: "Event group pane to manage data and view groups and all associated event IDs for NWHC only". Will need functionality of dashboard tabs only viewable to NWHC for NWHC only fields anyway

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by JChipault** [comment]
"Events" tab still has buttons that make someone outside of NWHC think that they can create an event group even though they cannot. If I try to create an event group from neilpartner account (non-NWHC), I do get a toast message saying that I don't have permissions to do this, but it's still a bit confusing to see the buttons and not be able to commit any groups. How hard would it be to hide from non-NWHC people the buttons on the "Events" tab that have to do with creating event groups? Sorry... forgot on initial bug report that event group functions were split between two tabs.

**Comment by BlakeDraper** [comment]
Good point @JChipault. Look for this change in the next release.
