### ISSUE TITLE
Comments - hide event group category

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#564]
Bug Report 703
"Biologically Equivalent (Public)" is in the comment type dropdown for location comments AND event comments. Two issues: 1) the category should be "Event Group" per comments in requirements doc (https://docs.google.com/document/d/1UUCNV235dtK4Hy2aHfwvkAeoJydwLZns_GeISYLzC5o/edit) and 2) the comment type of "Event Group" shouldn't be selected from location comments or event comments, but instead assigned as the comment category for any grouping justifaction text

**Comment by BlakeDraper** [comment]
@nbaertlein there was some confusion between the requirement as written vs the comment. I agree though, and we have updated the `comment_type` for the event group Justification to be 'Event Group'. I will need to go through and superficially remove all the 'special' comment types from the general comment type selection, not just this one - was just waiting to do that until that landscape stabilized a bit but it feels like we are close to that now.
