### ISSUE TITLE
Map - dx display

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#565]
bug report 691
If more than one event diagnoses, should all be listed on popup, even if only the first diagnosis is what determines dot color. See test even id 170625

**Comment by BlakeDraper** [comment]
Made a quick fix that addresses this.

**Comment by JChipault** [comment]
Added second event diagnosis of aflatoxicosis to event 170626 and now only aflatoxicosis shows up on pop up on map (though home page table, home page data export, and event details page have 2 event diagnoses). Added second event diagnosis of pending suspect (see github #535) to 170692 but that does not show up on map (though home page table, home page data export, and event details page have 2 event diagnoses).

**Comment by BlakeDraper** [comment]
Fixed (again) in code. Failed to replace the line doing it the old way for the multi-event popup constructor.
