### ISSUE TITLE
Event details - complete edits

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#566]
bug report 690
When an event is marked "complete" can still add location comments and create new contacts. I think business rules indicated that we wanted the ability to add comments after an event has been marked complete but currently we can add location comments but not event comments, which seems odd. And I'm not sure what good it does to enable "create new contacts" when can't add contacts to a complete event

**Comment by BlakeDraper** [comment]
@nbaertlein do you wish to prevent event location comment additions and allow event comments?

**Comment by JChipault** [comment]
Prefer to allow the addition of comments at both the location and the event level after an event is "complete" if that's easy enough to code.

**Comment by BlakeDraper** [comment]
Yes, I have just set it that way, so look for that update in next release.

**Comment by JChipault** [comment]
From business rules: "When the record is marked as "Complete" then lock the data (except the comments and ability to attach artifacts)."
