### ISSUE TITLE
Remove all 'special' comment types from the general comment selection

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#568]
- Event Group
- History
- Environmental Factors
- Clinical Signs
- Site Description

**Comment by BlakeDraper** [comment]
Done in code

**Comment by JChipault** [comment]
@BlakeDraper Can we not include "event group" as an option at the location level on the event details page?

**Comment by BlakeDraper** [comment]
@JChipault the "Event Group" comment type was intended as the type for the Event Group justification (which is actually just a comment, in the system). We were not aware of the need to use "Event Group" as a comment type for a general event location comment. I can easily add it back as an option, but unsure that is really what we want to do.

**Comment by JChipault** [comment]
@BlakeDraper Right, we do NOT want it there. (I probably should have capitalized "NOT" in my earlier comment). Event Group currently is available on the front end and we don't want it there.

**Comment by BlakeDraper** [comment]
Got it.

**Comment by JChipault** [comment]
@BlakeDraper "Event Group" is still an option in v.2.3.0. Just want to keep this on the radar

**Comment by lprivette** [comment]
@JChipault is this the "Event Group" comment type that you're referencing? 
![image](https://user-images.githubusercontent.com/23640741/62719043-0f74db80-b9d5-11e9-804a-b537bf91376c.png)

I went to event details > expanded "Location 1" > expanded "View Location Comments" > clicked "Add Comment"

**Comment by JChipault** [comment]
yes, that's the one.

**Comment by JChipault** [comment]
@BlakeDraper @lprivette Still have

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by BlakeDraper** [comment]
done 2.13.2
