### ISSUE TITLE
dashboard data not loading

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#570]
Data are loading on the main home page this afternoon (this morning they were not, probably due to EROS work as we discussed at our 10am meeting) but data continue to not load to the dashboard (no matter how long I wait, I don't get any "your events" or "contacts" etc.).

**Comment by JChipault** [comment]
seems to work in Chrome, just not Firefox.

**Comment by BlakeDraper** [comment]
@JChipault which user account is in use when you see this behavior?

**Comment by JChipault** [comment]
suspect JChipault since that's almost always the one that I use.

**Comment by JChipault** [comment]
Working today

**Comment by JChipault** [comment]
Neil and I played with this for a bit yesterday... looks like it might be related to toggling too much between test and live sites, like you brought up at yesterday's meeting. Sometimes the site will indicate that I'm logged in, but I'm not getting dashboard data. Then if I log out and log back in, I do get dashboard data. So site is telling me I'm logged in but I'm not really.

**Comment by BlakeDraper** [comment]
Ok, good to know. Yes, I hope it does not sound dismissive, but we don't want to try to chase down a solution for that problem because 1) it may be feasibly unsolvable and 2) it will be completely moot once WHISPers v2 is being used for real.

**Comment by JChipault** [comment]
get it. sounds good.
