### ISSUE TITLE
One Service Request - multiple entries

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#572]
"I entered another one today and again forgot to request diagnostics. When I went back to do that it hung up on the screen below for 2 or 3 minutes and then finally pushed through. Again, when I got the email, it was just like yesterdays, there were two, one with the original text and one like a forward of that one. Same subject line.
…and then a minute later a third email was sent looking identical to the second email."

Multiple entries for 1 button push. See service request for event IDs: 200077 & 200082

![unnamed](https://user-images.githubusercontent.com/38669574/57948990-bd765b00-78a8-11e9-80bc-b215ccc9e495.png)

**Comment by BlakeDraper** [comment]
No recent reports of this.  Believe this to have been fixed by other work.
