### ISSUE TITLE
v15 test JSON error

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#578]
Trying to enter events into v15 test site and get "Error. Event not Submitted. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**Comment by JChipault** [comment]
Was able to save some events today but then hit on this JSON error again. (I was trying to save an event with both pending and undetermined as event diagnoses, so perhaps that complicated things?)

Form Status: VALID

 {
  "event_reference": "",
  "event_type": "2",
  "complete": false,
  "public": true,
  "staff": null,
  "event_status": "1",
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [
    2
  ],
  "new_service_request": {
    "request_type": 0,
    "new_comments": []
  },
  "new_event_diagnoses": [
    {
      "diagnosis": "469"
    },
    {
      "diagnosis": "104"
    }
  ],
  "new_comments": [],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "",
      "start_date": "2019-05-15",
      "end_date": null,
      "country": "30",
      "administrative_level_one": 3,
      "administrative_level_two": 111,
      "latitude": null,
      "longitude": null,
      "land_ownership": "4",
      "gnis_name": "",
      "gnis_id": "",
      "site_description": "",
      "history": "asdfas",
      "environmental_factors": "",
      "clinical_signs": "",
      "comment": "",
      "new_location_species": [
        {
          "species": 1477,
          "population_count": null,
          "sick_count": null,
          "dead_count": 1,
          "sick_count_estimated": null,
          "dead_count_estimated": null,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": [
            {
              "diagnosis": 104,
              "cause": null,
              "basis": null,
              "suspect": false,
              "tested_count": null,
              "diagnosis_count": null,
              "positive_count": null,
              "suspect_count": null,
              "pooled": false,
              "new_species_diagnosis_organizations": []
            },
            {
              "diagnosis": 469,
              "cause": null,
              "basis": null,
              "suspect": false,
              "tested_count": null,
              "diagnosis_count": null,
              "positive_count": null,
              "suspect_count": null,
              "pooled": false,
              "new_species_diagnosis_organizations": []
            }
          ]
        }
      ],
      "new_location_contacts": []
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": [],
  "quality_check": null
}

**Comment by BlakeDraper** [comment]
@JChipault it does seem like the combination of Pending and Undetrmined was causing the error here, however that is now impossible with the new rules we laid out in our last meeting, so this is effectively fixed by those other changes.
