### ISSUE TITLE
species diagnosis type ahead dropdown

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#579]
For species diagnosis on create event form, if I start typing when the subform opens up, the diagnosis drop down is not displaying the typing, just filling in a diagnosis based on the letter typed.  I can click on term it entered and then the popup appears with a space for typing.

(this problem was previously resolved 12/18 but seems to be back with v15)

**Comment by BlakeDraper** [comment]
There is no way to trigger the search-select component without a click or an ENTER keystroke. I could not find it to cite (may have been a phone call), but this is an issue we already covered with Neil a few months ago.

**Comment by JChipault** [comment]
ah, ok, I thought this got fixed before by not automatically making that first line blue (i.e., active) so that you had to click on it before you started typing.
