### ISSUE TITLE
autofilling "Undetermined" at event level

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#586]
On the Create Event Form, if "Undetermined" is entered at the species level, then it becomes what autofills on the line when I click "Add Event Diagnosis", Would like line to be blank when click "Add Event Diagnosis", with "Undetermined" as an option when viewing dropdown list. 

![image](https://user-images.githubusercontent.com/49287076/58662024-dc381100-82ee-11e9-9b02-c61098720b5f.png)

**Comment by JChipault** [comment]
Also, it seems that these autofilled "undetermined"s don't commit because, even if I only have one "undetermined" at event level, when I look at event details page after saving event, that "undetermined" is not there. If I had "undetermined" and "aflatoxicosis" at event level in create event, then it's only "aflatoxicosis" in event details. If I had "undetermined" at event level in create event (even if only listed once, unlike screen shot above where it's listed 3 times), then it becomes "pending" when I look at event details.

**Comment by JChipault** [comment]
#736 in Neil bug report spreadsheet

**Comment by BlakeDraper** [comment]
Fixed in code. Also added a visual warning for why the Event Diagnosis selection options are empty when there is no species diagnosis selected.
