### ISSUE TITLE
clear selection of number affected in search form

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#589]
If I put in a number affected, then "clear selection" button at bottom doesn't clear that field

**Comment by JChipault** [comment]
happens in both firefox and chrome

**Comment by JChipault** [comment]
Neil bug report #640

**Comment by lprivette** [comment]
@BlakeDraper I used `this.form.reset()`. I noticed that you're using from.reset() in other places, but not there, maybe on purpose? Lmk know if I shouldn't have used it. I did some light testing and saw no issues.

I also added a tool tip to the clear dates button. I hadn't seen that symbol before and so thought it might be helpful for others.

**Comment by BlakeDraper** [comment]
looks good
