### ISSUE TITLE
publicTest account dashboard showing non-accessible components

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#592]
publicTest account dashboard has tab for "Your Events" which shouldn't exist for the public user. Same for "Contacts" and "Circles"

Neil report 240

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by JChipault** [comment]
@BlakeDraper Looks like public account can now see "Create Event" button again... can we remove that button? I feel like it was gone in some previous versions of WHISPers so hopefully that code exists to hide it?

**Comment by JChipault** [comment]
@BlakeDraper same for "request new species, organization, or diagnosis" on the dashboard, can that be hidden for public accounts?

**Comment by BlakeDraper** [comment]
Look for both in next release.
