### ISSUE TITLE
data layer sources referenced

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#596]
need credits/sources provided for data layers, including publication dates

**Comment by BlakeDraper** [comment]
@JChipault Where would you like to see these credits placed?

**Comment by JChipault** [comment]
I don't have a vision, was hoping maybe you knew a good spot to tuck them based on previous applications. Do you have options to suggest? Or should NWHC talk about it more to come up with options?

**Comment by BlakeDraper** [comment]
If you have no strong opinion, we will probably place it in the About component within a new credits tab.

**Comment by JChipault** [comment]
@nbaertlein what do you think?

**Comment by lprivette** [comment]
Did you want specific text for this? Or is there a document listing the sources?

**Comment by BlakeDraper** [comment]
@lprivette I will compile the credit text and put it here

**Comment by nbaertlein** [comment]
@BlakeDraper & @lprivette 
I'm looking at the layer credits on the map.  I'm wondering if the dynamically displayed details in the lower right hand corner would be sufficient?  Would just need dates (if available) and something for the flyways layer?

**Comment by lprivette** [comment]
I know we can remove those credits on the map with CSS, but I don't think setting the content with CSS will work to add the dates. I could be wrong though.

It's not really in the way on the map there, but another option would be to remove it and put the credits (including the dates) in the about tab.

**Comment by nbaertlein** [comment]
I'd like the minimum amount of work on this.  If there is no additional information that can be easily added to the map credits, what if we just keep what we have on the map as-is and refer people to the "About" if it's not sufficient?   ....(I'm guessing that was your current course anyway?)

**Comment by BlakeDraper** [comment]
@lprivette here is the credit text for the layers. Please place these under a "Credits" subheading in the Credit, User Guides, Metadata tab of the About component.

**Flyways Layer**
U.S. Fish and Wildlife Service, Natural Resource Program Center. 2017. USFWS Administrative Waterfowl Flyway Boundaries.

URL: https://services.arcgis.com/QVENGdaPbd4LUkLV/ArcGIS/rest/services/FWS_HQ_MB_Waterfowl_Flyway_Boundaries/FeatureServer


**Watersheds Layer**
The National Map, 2017. Watershed Boundary Dataset. The data is a seamless National representation of HU boundaries from 2 to 14 digits compiled from U.S. Geological Survey (USGS) National Hydrography Dataset (NHD) and U.S. Department of Agriculture (USDA) National Resources Conservation Service (NRCS) Watershed Boundary Dataset (WBD) sources. 

URL: https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer

**Landuse Layer**
US Geological Survey, Gap Analysis Program (GAP). August 2011. National Land Cover, Version 2. The GAP national land cover data version 2 provides detailed information on the vegetation of the United States using consistent satellite base data and classification systems. This allows data users to make conservation or land use planning decisions for the entire range of a habitat type across administrative boundaries. Access the full FGDC metadata record here: https://gapanalysis.usgs.gov/gaplandcover/data/land-cover-metadata/

URL: https://gis1.usgs.gov/arcgis/rest/services/gap/GAP_Land_Cover_NVC_Class_Landuse/MapServer

**Comment by lprivette** [comment]
Done in code.

**Comment by BlakeDraper** [comment]
looks good
