### ISSUE TITLE
user and user org noted for service request comments

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#600]
not listing user and user org when commenting on service request

neil bug report 536

**Comment by BlakeDraper** [comment]
@JChipault  Need clarification on this. Are you referring to the email that is generated?

**Comment by JChipault** [comment]
![image](https://user-images.githubusercontent.com/49287076/58735870-884a2c80-83c1-11e9-97b0-0f52f87d20b2.png)

**Comment by BlakeDraper** [comment]
Thanks!

**Comment by BlakeDraper** [comment]
fix underway. temporarily suspended for fix of backend bug with service request POST: https://github.com/USGS-WiM/whispersservices_django/issues/258

**Comment by BlakeDraper** [comment]
done in code.
