### ISSUE TITLE
county polygon loading on home page map

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#603]
If I click on an event in the home page table and then hit my browsers back button, I sometimes get the county polygon loading on the home page map. Had this happen multiple times hours apart. Using Firefox. Goes back to normal dots on a map if I hit browser refresh.   

![image](https://user-images.githubusercontent.com/49287076/58729641-955e2000-83af-11e9-8711-457f3f62e308.png)

**Comment by BlakeDraper** [comment]
I have seen this happen. Gonna be a fun one to debug.

**Comment by BlakeDraper** [comment]
I believe this has been addressed by some other changes we have made to the home page initial loading logic, but feel free to reopen if you see this happening again persistently.
