### ISSUE TITLE
Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#607]
two external testers using the test site v16 ran into this error on 6/3/19. Two different contexts...

1) New user (samantha_gibbs@fws.gov) trying to register under "Natural Resource Mangement Professional" gets "Error. User registration failed. Error message: SyntaxError: Unexpected token T in JSON at position 0". She tried it again on 6/419 and got same error.

2) different user (lisa.shender@myfwc.com) got "Error. Collaborator list not updated. Error message: SyntaxError: Unexpected token T in JSON at position 0.” when trying to add a circle to an event on the event details page.

**Comment by BlakeDraper** [comment]
This was fixed with a backend update a few weeks ago.
