### ISSUE TITLE
Prevent the "Location Data Absent" box on map when the user is actually just not allowed to see the location lat/long

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#609]
![image](https://user-images.githubusercontent.com/6978380/59121969-b629f680-8916-11e9-8120-a46cb509fa1e.png)
This should only show when user is logged in, with a role that allows them to see privileged data AND the lat/long does data does not exist. If the user is Public, they are not allowed to see the Lat/Long specific location, so that is the reason it does not show, not that the data is absent.

**Comment by lprivette** [comment]
So only roles 1-5 should see this?

**Comment by BlakeDraper** [comment]
Roles 1-6, actually. So can just do a check for if role !== 7 (public)
