### ISSUE TITLE
dropping location and species information, variety of error messages

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#610]
first hit this bug today in live site (v13) but replicated on test site (v16).

On the test site, I created a new event and entered data very similar to what I had earlier seen an epi enter into the live site. Got this error message: Error. Event not Submitted. Error message: {"isTrusted":true}. Never was told via the pop up message that event was saved but did get an email announcing the service request. But when I went to home page and then navigated to 170752 by adjusting the number in the URL, I found the event I had created... but it was missing a lot of information that I had entered (all location and species information was gone.) Form values and screen shot below.

Then I tried again on the test site and just entered the bare minimum information needed to create an event (versus entering GNIS and a few other fields that I had entered when I created 170752) and this time I got this error message: Error. Event not Submitted. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data. And, again, no pop up telling me that the event was saved. But I again was able to find that this event was saved (170753), but again without the location and species information. Form values and screen shot below.

The epi staff member (Barb Bodenstein) that ran into the issue on the live site also says that she got the server error 500 message today before it saved an event without location and species information (200104). And then she hit save again (because she wasn't told that it saved the first time) and created 200105 that seems to have also have dropped the event organization, in addition to having dropped location and species information. 

So that's three different error messages bumped into today and the dropping of various data when an event saves. 

See events 200103-200106 in the live site. I have the form values for some of those if it would be helpful. 

![image](https://user-images.githubusercontent.com/49287076/59703108-cc5d6f80-91be-11e9-88b9-73575db81de8.png)

Form Status: VALID

 {
  "event_reference": "",
  "event_type": "1",
  "complete": false,
  "public": true,
  "staff": "4",
  "event_status": "2",
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [
    2
  ],
  "new_service_request": {
    "request_type": 1,
    "new_comments": []
  },
  "new_event_diagnoses": [],
  "new_comments": [],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "Big Bend",
      "start_date": "2019-06-14",
      "end_date": null,
      "country": "30",
      "administrative_level_one": 46,
      "administrative_level_two": 2708,
      "latitude": null,
      "longitude": null,
      "land_ownership": "2",
      "gnis_name": "Big Bend Ranch State Park",
      "gnis_id": "2028786",
      "site_description": "",
      "history": "bats found dead",
      "environmental_factors": "",
      "clinical_signs": "",
      "comment": "",
      "new_location_species": [
        {
          "species": 858,
          "population_count": null,
          "sick_count": null,
          "dead_count": 6,
          "sick_count_estimated": null,
          "dead_count_estimated": 10,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": []
        }
      ],
      "new_location_contacts": []
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": [],
  "quality_check": null
} 

![image](https://user-images.githubusercontent.com/49287076/59704160-19424580-91c1-11e9-9dc4-b5974cb28dcb.png)
Form Status: VALID

 {
  "event_reference": "",
  "event_type": "1",
  "complete": false,
  "public": true,
  "staff": null,
  "event_status": "1",
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [
    2
  ],
  "new_service_request": {
    "request_type": 0,
    "new_comments": []
  },
  "new_event_diagnoses": [],
  "new_comments": [],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "",
      "start_date": "2019-06-18",
      "end_date": null,
      "country": "30",
      "administrative_level_one": 3,
      "administrative_level_two": 113,
      "latitude": null,
      "longitude": null,
      "land_ownership": "1",
      "gnis_name": "",
      "gnis_id": "",
      "site_description": "",
      "history": "asdf",
      "environmental_factors": "",
      "clinical_signs": "",
      "comment": "",
      "new_location_species": [
        {
          "species": 1084,
          "population_count": null,
          "sick_count": null,
          "dead_count": 1,
          "sick_count_estimated": null,
          "dead_count_estimated": null,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": []
        }
      ],
      "new_location_contacts": []
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": [],
  "quality_check": null

**Comment by JChipault** [comment]
actually, issues started yesterday on live site (200103 was created 6/17)

**Comment by BlakeDraper** [comment]
We have addressed the root cause of the problems the user was seeing here with a total refactor of the server-side code that processes the event submission. I know this technical explanation is not very compelling, and totally immaterial to the experience of the user, but no records were ever being dropped, they just were not created in the first place because of some fault in the process.

 We now know that fault was most likely the flyways service failure. In addition to writing a protection against the process breaking on the failure of that 3rd-party service, Aaron has also written the code in such a way that if the process does have a fault, it 'cleans up' be removing the event record it had created to be a parent to all the other records. That means you will not have an event created with the appearance of everything else having been 'dropped' from it.
