### ISSUE TITLE
Text to direct users to dashboard to create Circles

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#612]
Lots of testers had trouble figuring out where to go to create Circles. They were trying to do it from the Collaborators heading section on the create event or event details page. One user suggested an easy aid:  "To make this more obvious, when the “Choose Circle” subwindow pops up, you could change the heading to “Choose Circle from your Dashboard List.” This way people will know that they have to go to the Dashboard first to create the circle."

**Comment by BlakeDraper** [comment]
Added text "Circles can be created from your User Dashboard." Done in code.
