### ISSUE TITLE
organizations truncated

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#613]
There's been a few tickets on this before and I know NWHC might need to decrease the character count on some organizations, but I'm wondering if these fields have been widened as much as possible on the front end:
1) create event - contact organization
2) create event - lab (this subform is wider on the event details page than on the create event page)
3) WHISPers Registration for Natural Resources Management Professionals

**Comment by BlakeDraper** [comment]
widened for User Reg. Width is maximized for others. We may need to rethink the design of several elements if this is going to be an issue ongoing. Future dev.
