### ISSUE TITLE
Delete age bias and sex bias entries

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#614]
If I select something under age bias or sex bias, I can't make those fields blank again. Maybe add "--" as an option?

**Comment by BlakeDraper** [comment]
Done in code

**Comment by JChipault** [comment]
@BlakeDraper I see it's changed on the event details page... can we get that same fix to the create event page?

**Comment by JChipault** [comment]
@BlakeDraper  I'm not sure what supposed to go under "event group"? On event 170680 in the test site that is assigned to G12, "event group" is blank under the privileged data even if I'm logged in as whispers admin. If it's supposed to have G12 there, then Event Group would be a public/partner field if grouping category is "Biologically equivalent (public)" but it'd be an NWHC only field if "Other (NWHC only)".... so might be easiest to just remove it altogether for now?
