### ISSUE TITLE
NWHC only headers hidden

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#616]
On the event details page, do not display headers for data that only NWHC can see for users not within NWHC (e.g., legal status)

**Comment by BlakeDraper** [comment]
It was our understanding that partners could see this data, just not edit it. Updated according to this issue. Done in code.

**Comment by JChipault** [comment]
@BlakeDraper Please put Event Owner back in (that can be viewable by partners) but remove Process Status (this is an NWHC only field)

**Comment by JChipault** [comment]
@BlakeDraper I'm not sure what supposed to go under "event group"? On event 170680 in the test site that is assigned to G12, "event group" is blank under the privileged data even if I'm logged in as whispers admin. If it's supposed to have G12 there, then Event Group would be a public/partner field if grouping category is "Biologically equivalent (public)" but it'd be an NWHC only field if "Other (NWHC only)".... so might be easiest to just remove it altogether for now?

**Comment by JChipault** [comment]
By "remove it altogether for now" I mean to remove the data heading of "event group" from the privileged data section instead of trying to figure out how to populate it. Users can see event group ID at the top of the page

**Comment by JChipault** [comment]
@BlakeDraper Just want to keep this one on the radar... don't see above tweaks in v2.3.0

**Comment by lprivette** [comment]
Done in branch `616`.

Changes made:
1. `Event Owner` view-able to roles 1,2,3,4,5 ( admin and partner roles)
2. `Process Status` field only visible to admins (roles 1,2)
3. Removed `Event Group` from the privileged data section

**Comment by BlakeDraper** [comment]
Merged in my local dev branch
