### ISSUE TITLE
species diagnosis text clipped

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#620]
Sometimes the species diagnosis text gets clipped on the event details page. Here's 170737 from the test site v16: 

![image](https://user-images.githubusercontent.com/49287076/59863308-10c94680-934a-11e9-9a07-5d64d56ce6a6.png)

**Comment by BlakeDraper** [comment]
@mitchas been having issues with the table display generally. Please help us to make this next work better.
