### ISSUE TITLE
associated events as obvious links

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#630]
make event ID number text blue to show that it's a link for event numbers listed under "associated events" on event details page.
![image](https://user-images.githubusercontent.com/49287076/60120604-d1826780-9746-11e9-868a-7c462f3d317b.png)

**Comment by BlakeDraper** [comment]
@mitchas these are actually buttons and not links (was hard to style as text links) but we can either just make them faux links with blue and underlining, or some other indication that they are clickable.
