### ISSUE TITLE
Set a max height and scroll for the Saved Searches panel of the home page

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#631]
I need to improve on the fact that the list scrolls forever currently, but we can at least prevent it from extending the length of the whole page indefinitely.  Log in as admin to see what happens with a large list of Saved Searches.

**Comment by JChipault** [comment]
Can we have most recent on the top of the list instead of on the bottom? Maybe that was already part of this plan

**Comment by BlakeDraper** [comment]
I've gone ahead and done that order reverse in code, so look for it in next release @JChipault
