### ISSUE TITLE
event details preview on home page map gets clipped

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#632]
Clicking on the map dot with multiple events puts the event info off the page and have to move the map to see the info.

I think this was fixed before but seems to be a problem again with v17. 

![image](https://user-images.githubusercontent.com/49287076/60196215-3cdd3f80-9802-11e9-864a-5440138e1fd5.png)

**Comment by JChipault** [comment]
still an issue with v2.2.0

**Comment by BlakeDraper** [comment]
This is a surprisingly difficult issue to solve, with a lot of imperfect sort of half-measure solutions. The map element is fairly complex . I am going to confer with the wider WIM team on this during our dev call this week to attempt to build a consensus on a workable solution.

**Comment by JChipault** [comment]
Neil and I think it's ok to hold on this if it's complicated.

**Comment by lprivette** [comment]
Done in branch `632`.

I've done two things to fix this: 
1. added `maxHeight`, `autoPanPadding`, and `keepInView`options to the popup. There will be a scroll for multiple event points that have 7 or more
2. Opening the first event in the accordion by default. This ensures that there is always enough space for the popup when the point is first clicked.

**Comment by BlakeDraper** [comment]
Strong work @lprivette - works great. Merged in my local dev branch.

**Comment by JChipault** [comment]
looks good on 2.4.0
