### ISSUE TITLE
can't register new users - server error (500)

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#633]
NWHC staff tried to register on live v17 and got server error (500). Emails and passwords matched and met minimum requirements.

![image](https://user-images.githubusercontent.com/49287076/60197386-e1f91780-9804-11e9-802c-d0e51f2c5921.png)

**Comment by JChipault** [comment]
Had another staff member try to create a login and she got same error message

**Comment by aaronstephenson** [comment]
Fixed in 0.137.2 26bc273
