### ISSUE TITLE
link for user guides and metadata

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#638]
Here's the link for where the metadata and user guides will reside. It's not active yet but will be made active on July 1. https://www.usgs.gov/centers/nwhc/science/whispers

This link should be what people land on when they click the "Metadata" button between the map and the table on the home page.

And I'd like to add this link to the "About" section somehow. What do you think is best? Maybe another tab that says "User Guides and Metadata" and then that tab has this link?

As an FYI, here's a screen shot of what the website will look like: 
![image](https://user-images.githubusercontent.com/49287076/60302325-3f6e9080-98f9-11e9-8ebf-1539d7c97cb0.png)

**Comment by BlakeDraper** [comment]
Added a new tab to the About with this link. Will also add the map credits stuff to this soon. Donce in code, look for in next release.
![image](https://user-images.githubusercontent.com/6978380/60303521-37fcb680-98fc-11e9-8940-dc09e1c2bb71.png)
