### ISSUE TITLE
partners are able to see event details on events outside their org

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#639]
We noticed that when we logged in as neilpartner (associated with Woods Hole) that we were able to see privileged data for historic NWHC events on the event details page. Neilpartner should only see privileged data for events in his org or events he's a collaborator on

**Comment by BlakeDraper** [comment]
Do you have both test and live open at the same time?

**Comment by JChipault** [comment]
I only had test open when I noticed this.

**Comment by BlakeDraper** [comment]
Conversation in chat revealed this to be a false alarm.
