### ISSUE TITLE
Updates to FAQs

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#641]
Under "What does it mean to be an authenticated agency partner?" change end of first sentence from "... update event information for their agency, a communication interface with the USGS National Wildlife Health Center and other agencies, and a robust collection of visualization and analytical tools designed for wildlife disease professionals." to "... update event information for their agency, and a communication interface with the USGS National Wildlife Health Center and other agencies."

Under "What do the colors and shapes on the map mean?" change last sentence from "The map on the homepage displays the 20 most recent disease and surveillance events reported in WHISPers." to "The map on the homepage displays disease and surveillance events that started over the previous 4 weeks."

Under "Where is the information in WHISPers from?" change "Surveillance information is planned to be added in the next version of WHISPers." to "More surveillance information is planned to be added in a future version of WHISPers."

Change "What is a diagnostic or epidemiologic assistance request?" to "What is a diagnostic or consultative services request?"

Under "What is a diagnostic or consultative services request?" change last parenthetical from "(epidemiologic assistance request)" to "(consultative services request)"

Change "How do I submit a carcass to the USGS National Wildlife Health Center or request epidemiology assistance?" to "How do I submit a carcass to the USGS National Wildlife Health Center or request a consult?"

Under "How do I submit a carcass to the USGS National Wildlife Health Center or request a consult?" change the end of the first sentence from "... user from their WHISPers dashboard." to "... users from the event details page."

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by BlakeDraper** [comment]
Done

**Comment by JChipault** [comment]
Looks like we still need this change....
Under "Where is the information in WHISPers from?" change "Surveillance information is planned to be added in the next version of WHISPers." to "More surveillance information is planned to be added in a future version of WHISPers."

**Comment by BlakeDraper** [comment]
done in code
