### ISSUE TITLE
JSON error when changing event to "Complete"

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#644]
In the production WHISPers (https://whispers.wim.usgs.gov/event/200119), I went to change this event from "incomplete" to "complete" and got this message

Error. Event not updated. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data

**Comment by BlakeDraper** [comment]
event 200119 does not exist in the production database, which would explain the error.

**Comment by BlakeDraper** [comment]
This is on ongoing server configuration issue we are back and forth on with EROS. Thought it was solved, but apparently not for the PUT method which that event save uses.

**Comment by BlakeDraper** [comment]
@JChipault got EROS to update their server config to allow all the methods we need. That was the problem- blocked requests. I confirmed that this is working again. Please try for yourself and confirm for me and if it works, I'll close this issue.

**Comment by JChipault** [comment]
worked! Thanks!
