### ISSUE TITLE
Map line and polygon tools

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#656]
There is some potential confusion when using the new edit/delete layer buttions as they only apply to the polyline and polygon tools.  Would it be possible to group these somehow to demonstrate the 4 buttons are a package deal?  
Something like:
![map1](https://user-images.githubusercontent.com/38669574/61158448-8db98d00-a4be-11e9-84b6-e2fc711aba83.png)
or 
![map2](https://user-images.githubusercontent.com/38669574/61158456-927e4100-a4be-11e9-8a26-9cfc946ac939.png)

**Comment by BlakeDraper** [comment]
@lprivette this one in your court. I am not sure exactly how configurable that package is, but seems like we pull something off here fairly easily.

**Comment by lprivette** [comment]
Did the first one: 
![image](https://user-images.githubusercontent.com/23640741/61229658-91375900-a6f6-11e9-806d-c8bdea493e9b.png)

Done in code.
