### ISSUE TITLE
hover over not working in Firefox

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#657]
Black question mark symbol after "Current Event Group Selection:...." in dashboard doesn't do anything in Firefox, but does work in Chrome. Maybe this is a quick fix, maybe it just won't work in Firefox...?

**Comment by BlakeDraper** [comment]
@JChipault That symbol is actually not a hover-over at all. It's a icon button, which requires a click from the user to open a small dialog telling them how to select/update an event group selection. I just tested in Firefox version 68 and it works fine. Are you clicking it, or just hovering it?

At any rate, I don't think it is wise to take a lot of time pursuing this one.

**Comment by BlakeDraper** [comment]
I am changing the icon to an information "i" to avoid confusion with the "?" hover icons located elsewhere.
![image](https://user-images.githubusercontent.com/6978380/61474756-e5d51100-a94e-11e9-8ada-fbb2fd51f62a.png)

**Comment by JChipault** [comment]
changing to "i" is a good idea. it doesn't do anything when I click it on my firefox version (which looks to be 60.7.0esr). I'll talk to IT here again about updating my firefox. sorry.

**Comment by JChipault** [comment]
IT here says (again) that this is the most up-to-date version of firefox I can have so I'm stuck. hopefully there aren't too many things that I flag that are just due to my inability to have a newer version. sorry for being behind the times

**Comment by JChipault** [comment]
actually, looks like they'll bump me to 60.8esr next week so maybe that will help

**Comment by BlakeDraper** [comment]
@JChipault this should really not even be a version issue as the code being used for this is dead simple and long supported by every browser. I can't explain why this does not work on your environment without deeper testing. Can you ask some of your NWHC colleagues to try this and confirm the same behavior on their own system using Firefox?

**Comment by JChipault** [comment]
Did not work on Kim's v60.7.0esr. Working now in my v68 and coworker's v67.04 of firefox. We can just hope that not many people have the old esr version.
