### ISSUE TITLE
remove "Review Event Submission" button for now

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#658]
The popup that comes up when you click the "Review Event Submission" button doesn't have all the event information (e.g., it says "species" but doesn't list the species entered) and the formatting is funny (e.g., has long time stamp connected with the date) so we suggest just removing this button altogether for now instead of spending the time to clean that up. Removing the button is also supported by some user feedback in that users think this is a step they have to do before submitting or even that this step IS the submitting step so it'll just be less confusing if we remove the button for now. We might revisit under reports in Effort 2. Work for you?

**Comment by BlakeDraper** [comment]
Yes, I can remove that for now, no problem.

**Comment by BlakeDraper** [comment]
Done in code
