### ISSUE TITLE
Add hover over text

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#660]
Follow the spreadsheet provided by Jenny via email.

**Comment by BlakeDraper** [comment]
@lprivette let's put this text content into a config file. They indicated a desire to be able to edit the text easily and I think we can accomplish that with a simple config file. I was originally going to say to add it to the app.setting.ts, but I think this deserves its own file. You can follow the same pattern used for `app.settings.ts` and `app.utilties.ts` to make the variables available to different components.

**Comment by BlakeDraper** [comment]
`app.field-help-text.ts`, perhaps.

**Comment by lprivette** [comment]
Got it, will do.

**Comment by lprivette** [comment]
Done in code. 

I stuck to the ? icon and the 'hint' field for text that was short.

The config file `app.field-help-text.ts` contains all the text definitions.

@JChipault When this change makes it into the test environment you may want to review them. I did double check each one, but there's a lot of components involved (especially with the Edit Event tips).

**Comment by BlakeDraper** [comment]
juts missing on the add-event-location component
