### ISSUE TITLE
Improve UX for user navigation to User Dashboard

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#661]
@mitchas Asking you to use your keen eye for design to tweak the UI of the User Dashboard navigation on WHISPers. Currently, the Dashboard, which is a fairly important part of the user's workflow, is somewhat buried behind the User's logged-in identification button at top right. It is not exactly intuitive to click there to get the button that takes a person to the User Dash, and it is currently the only way to get there. It may be as simple as seperating that button out on its own on the header bar. I tried that as a first pass but hit some CSS and real estate/space issues.  I'd like you to take a look and see what you can come up with, thanks!

![image](https://user-images.githubusercontent.com/6978380/61314207-b513a100-a7c1-11e9-84fe-d66a9764713c.png)

![image](https://user-images.githubusercontent.com/6978380/61314143-8dbcd400-a7c1-11e9-9bcf-ecf0bda0f8f2.png)

**Comment by JChipault** [comment]
for what it's worth, we've also heard from a user that he repeatedly accidentally logs out when trying to get to the dashboard because those options are so close together.

**Comment by lprivette** [comment]
Took a stab at this in branch `661`. 

Changes I made:
1. login button now opens the authentication dialog directly (no mat-menu to hit login again on)
2. added the User dashboard button to the right of the home button. So as a public user:
![image](https://user-images.githubusercontent.com/23640741/62799289-69959f80-baae-11e9-8e5d-9759424c3b9d.png)
and as a partner user:
![image](https://user-images.githubusercontent.com/23640741/62799336-8c27b880-baae-11e9-965d-b82d7e5271c5.png)
3. I added a logout button/icon next to the user's name that clicking on will log them out
![image](https://user-images.githubusercontent.com/23640741/62799391-a95c8700-baae-11e9-8fce-6f67074c7b9f.png)

**Comment by BlakeDraper** [comment]
My only tweak: added a "Logout" tooltip to the logout button for clarity. Let's see how NWHC likes this in practice. @JChipault also feel free to comment on it now with screenshots Lauren shared above.

**Comment by JChipault** [comment]
Definitely better! My OCD-like tendencies would add "Home" next to the home graphic just for consistency, but maybe that's overkill? Also, is the spacing the same between buttons?... again, minor detail and maybe something that just gets polished up later if it is even off. Thanks!
