### ISSUE TITLE
Round lat/long to fit within max decimal places

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#662]
User input: Get Invalid warning for lat/long if too many decimal places are entered and then it doesn't accept/save the entry. 

Neil's suggestion: there is a decimal limit that had to be imposed (max 6 I think).  6 decimal places accurate to 11 cm and less.  Suggest auto-round

**Comment by BlakeDraper** [comment]
@JChipault  This raises some UX  (user experience) questions. How/when would it auto-round? If it auto-rounds right in the field as soon as a user enters a digit beyond the max, I am sure that will also cause confusion. If we just auto-round on the backend, what do we do about the validity status and message on the front end? Is it better to just tell the user that the value entered is too long?

**Comment by nbaertlein** [comment]
Concerning UX in terms of minimizing clicks, I think we should inform the user that lat/longs will be limited to 6 decimal places.  The message could be a hover over or simple form text "lat/long will be limited to 6 decimal places".  Rounding could then happen on the front end.  Rounding could be round down/truncate to avoid confusion of changing numbers.   I'm thinking the fewer clicks and decisions for the user at this point, the better.

**Comment by BlakeDraper** [comment]
Done in code

**Comment by BlakeDraper** [comment]
The lat and long fields will truncate to maximum 6 digits after the decimal. User will be unable to enter more digits than 6 after the decimal.
