### ISSUE TITLE
can't group events

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#664]
dropdown for event group category isn't working. I don't get anything in the dropdown. Tried firefox and chrome. using jchipault account

![image](https://user-images.githubusercontent.com/49287076/61468315-aacce080-a942-11e9-9ec7-3bc50d0a7435.png)

**Comment by BlakeDraper** [comment]
@JChipault this is data issue. The event group categories table is empty on the production database, so there is nothing there to choose from. @nbaertlein can you please re-populate that table? I am thinking it was accidentally wiped recently.

**Comment by nbaertlein** [comment]
@JChipault Please take another look.  I just added two group categories.

@astephenson@usgs.gov I was able to add event group categories via the live API, but I'm attempting to access via the pgSQL server and am getting a permission denied notification.  Can you see anything different with these tables (whispers_eventgroupcategory, whispers_eventgroup, whispers_eventeventgroup)?

**Comment by JChipault** [comment]
working on front end now
