### ISSUE TITLE
search not fully described in dashboard tab

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#665]
home page search is this
![image](https://user-images.githubusercontent.com/49287076/61473448-06e83280-a94c-11e9-8cbd-ea2395e3a56a.png)
on dashboard "events" tab it doesn't tell me that search is also based on state of alaska
![image](https://user-images.githubusercontent.com/49287076/61473517-28491e80-a94c-11e9-89f0-e054bc95ce4f.png)

**Comment by BlakeDraper** [comment]
Done in code
