### ISSUE TITLE
Implement an Event Edit interface

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#67]
Will leverage the existing event submit form for all the form bits. Will also have additional parts only seen in edit 'mode', such as Add Event Diagnosis button and Add Species Diagnosis button (per species, per event location). Will need to implement angular router trickery, so that edit mode includes the event ID in the URL at top, whereas event submit remains just 'eventsubmission'.

**Comment by njestes** [comment]
changed methods on this. Going with editing via the event details component.
