### ISSUE TITLE
pk value error when editing species diagnosis

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#670]
v2.2.0
When I hit save changes on this:
![image](https://user-images.githubusercontent.com/49287076/61565516-df25c700-aa3e-11e9-8bfe-80c80bf1bc97.png)
I got this toast message: 
Error. Species diagnosis not created. Error message: {"diagnosis":["Incorrect type. Expected pk value, received list."]}
Hit save changes again and it commited.

**Comment by BlakeDraper** [comment]
@JChipault I cannot recreate this. Did this only happen one time or has it been persistent? And can you provide the event ID this happened with?

**Comment by JChipault** [comment]
Event 170761. 

I just tried doing the same thing for 170764 to see if I can recreate it, and got this one: Error. Species Diagnosis not created. Error message: {"Log-Id":"16c1af30367-26d1deb0","Request Time":"2019-07-22 18:30:29 GMT","Error":"The specified URL cannot be found "}

**Comment by JChipault** [comment]
tried a few other events and it worked (no url or pk value errors)... but it sometimes wasn't adding the species diagnosis on the main event details screen unless I hit the refresh button on my browser. Do we have that as a different github ticket? I couldn't find it but felt like we've talked about ti.

**Comment by BlakeDraper** [comment]
>but it sometimes wasn't adding the species diagnosis on the main event details screen unless I hit the refresh button on my browser.

Do you mean, it was taking your species diagnosis addition, giving you a success message, but then not refreshing the page to show the just-added diagnosis? If so, I am not aware of a ticket for that issue specifically.

**Comment by JChipault** [comment]
Yes, that's what's happening. Not every time, but sporadically. It was doing that last week too. I must have been talking to someone internally about it and hadn't put it into github yet.

**Comment by JChipault** [comment]
Ah, looks like it was buried in my second comment on what is now in Aaron's queue (Django #272)

**Comment by JChipault** [comment]
I'll start a new github ticket for this issue

**Comment by BlakeDraper** [comment]
@JChipault I am going to defer this issue for the moment (the pk value error) until we have more data points. I cannot recreate it myself and there is little I can do to debug until I do. The URL error is the EROS thing, which you have rightfully logged into our document for that specifically. The non-refresh error is in a separate issue now, so the the titular pk error is all that remains as an unknown on this issue. I am not closing, but I am putting in a deferred state until it happens again and we can try to pinpoint more details.

**Comment by JChipault** [comment]
sounds good

**Comment by JChipault** [comment]
Just tried the same thing again and it worked fine.

**Comment by JChipault** [comment]
Hit on different event. Purposefully in firefox 60.7.0esr. 170761 on test site. Just trying to change number assessed and number with this diagnosis and got pk value error
![image](https://user-images.githubusercontent.com/49287076/61745209-9b90cd00-ad5e-11e9-88ba-f4cd169888fb.png)

**Comment by BlakeDraper** [comment]
@JChipault any recent experience of this problem?

**Comment by JChipault** [comment]
@BlakeDraper nope

**Comment by BlakeDraper** [comment]
Closing as stale and almost certainly fixed.
