### ISSUE TITLE
Can't save search - token error

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#671]
Trying to save search but I'm getting a missing token error:
Error. Search not saved. Error message: {"detail":"SCRF Failed: CSRF toekn missing or incorrect."}

![image](https://user-images.githubusercontent.com/38669574/61567119-059a3100-aa44-11e9-91dc-02de1a5b4ed4.png)

**Comment by BlakeDraper** [comment]
@nbaertlein were you/are you logged in to the browseable API? that is what causes this error.

**Comment by nbaertlein** [comment]
No.  I just tried again now and am getting the same error.  Browseable API has not been opened yet today.

**Comment by BlakeDraper** [comment]
@nbaertlein  even if you have not opened it, the login is stored locally in your browser. Can you be sure to open the API for the same environment you are using (whispers or whisperstest) and actively log out? Sorry to be insistent, but this is the only scenario we have ever observed that triggers the CSRF token error.

**Comment by nbaertlein** [comment]
@BlakeDraper Your assessment is correct.  The login was stored so I logged out of the API and was able to save my search successfully.  Sorry about that.  Thanks for you help.
