### ISSUE TITLE
changes not displaying until refresh browser

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#672]
July 18 - 
Anne Ballmann tried to update number with this diagnosis for a location she already had on event 200136 in the live site and she changed it from 1 to 2 and then hit submit and got message saying that the species diagnosis was updated but the 1 stayed a 1... until she hit refresh on her browser and then that 1 became a 2. (no error message happened with updating the "number with this diagnosis" but the data didn't update on the event details page until browser was refreshed)

July 22 -
Jenny was trying to add species diagnoses to various events in the test site and it sometimes wasn't adding the species diagnosis on the main event details screen unless I hit the refresh button on my browser.
Blake's summary of Jenny's July 22 comment-
Do you mean, it sometimes taking your species diagnosis addition, giving you a success message, but then not refreshing the page to show the just-added diagnosis?

**Comment by lprivette** [comment]
In Test, I've been unable to recreate this. I tried 1) adding and deleting a species diagnosis, and 2) changing value on species diagnosis. For both the species diagnosis on the main event details page refreshed and reflected the change.

Tested in Chrome Version 75.0.3770.90 & Firefox 68.0

**Comment by BlakeDraper** [comment]
@JChipault I also had no luck observing this after many attempts. Is it possible that there is confusion over how the species diagnosis table reloads after the auto page refresh? The table containing the species diagnosis does collapse on refresh and needs to be manually re-expanded. I did notice that the numbers displaying may get confused and could have given the impression the changes did not display?

I'm generally not quick to assume User's reports are wrong but I just cannot seem to recreate and observe the behavior described.

**Comment by JChipault** [comment]
I'm in firefox 68.0 now. I think Anne was in chrome when it happened to her. 

I'm familiar with the fact that the page will shift when you're updating using a subform and that you have to go back and manually expand the area you were updating to see the change. It is not doing that shifting/collapsing step on the main page. I get a success toast message and the main page just stays still after the subform disappears. It does not happen every time. I just took a video that I'm trying to figure out how to get off my phone and to you.

**Comment by JChipault** [comment]
Just emailed the video because couldn't attach it here.

**Comment by JChipault** [comment]
try editing number assessed and number with this diagnosis

**Comment by BlakeDraper** [comment]
@JChipault thanks for sending the video. I see what you are saying. Still cannot get it to happen that way for us but will keep up the investigation.

**Comment by JChipault** [comment]
looks like I lied... I was on firefox 60.7.0esr actually when I recorded the video. Firefox 68.0.1 installed in parallel with 60.7.0esr. Colleague who had issue on July 18 usually uses chrome but if she was on firefox it would have been v67.04 of firefox. Working now to recreate this refresh problem in firefox 68.0.1

**Comment by BlakeDraper** [comment]
@JChipault Is this issue ongoing still?

**Comment by JChipault** [comment]
@BlakeDraper I haven't seen this for a while.

**Comment by BlakeDraper** [comment]
Closing for lack of recent evidence.
