### ISSUE TITLE
Can't toggle event from complete to incomplete to edit it

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#673]
From Macy (NWHC staff):
I am trying to edit event 170342 in WHISPers of Custer Co, South Dakota. If I understand correctly, I need to change to the "WHISPers Record Status" to "Incomplete" to be able to make changes. When I do that, I receive the error message shown in the screenshot below which inhibits me from saving and moving forward.

Jenny tried it and got the same thing. 

![image](https://user-images.githubusercontent.com/49287076/61723715-37f0aa80-ad32-11e9-86b3-895330fb9912.png)

**Comment by JChipault** [comment]
Looks like it's flagging it because this legacy data has the dungeon room location (da-da-daaaaaa) with a report of 500 live myotis without listing any sick or dead, so that violates the business rules. But you should be able to edit it and just get this warning when you try to mark it as complete again, right?

**Comment by BlakeDraper** [comment]
Legacy data edge case! I made a tweak in the code that ensures the rule is only checked when changing _to_ complete and not when changing to incomplete. Did the same for the basis and cause violation ("The event may not be marked complete until all of its location species diagnoses have a basis of diagnosis and significance of diagnosis selected."). Look for update in next release.
