### ISSUE TITLE
Start date warning displayed at bottom of event submission page

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#675]
![image](https://user-images.githubusercontent.com/23640741/61913794-34b11680-af0c-11e9-9852-83da1f6375f1.png)
Check the edit event > add location section as well.

**Comment by lprivette** [comment]
Actually maybe this placement is intentional? Since there only has to be one event location with a start date. What if we display the warning in each event location until one has a start date?

Feel free to close this issue if it's not necessary and we don't want to spend time on this.

**Comment by BlakeDraper** [comment]
Yes, the placement is intentional because it is an event-level rule, so to speak. I am open to duplicating the message at each event location though. It would really just be a copy/paste of that into those areas, the variable hiding and showing it is already functioning.

**Comment by BlakeDraper** [comment]
I can start this one

**Comment by BlakeDraper** [comment]
done in code

**Comment by JChipault** [comment]
see my comment from today on #674
