### ISSUE TITLE
Empty contacts left in the form causing event location to fail

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#676]
See https://github.com/USGS-WiM/whispers/issues/674 for more history.

Users who add a contact person to an event location, but do not actually select anyone in the dropdown, encounter an error when attempting to submit a new event or save a new event location to an existing event. 

In the `lauren-dev` branch, for the add-event-location component (used when editing an existing event) I have it stripping out any null contact objects on the submit. Does that sound good to you @BlakeDraper or is there another way you'd prefer to handle this?

**Comment by BlakeDraper** [comment]
@lprivette I think that sounds ok. Let's just be sure we test that thoroughly because the server gets cranky if the submission JSON is not just right.

**Comment by lprivette** [comment]
Done in branch `676`

**Comment by BlakeDraper** [comment]
Tested and works, Merged with my local dev branch.

**Comment by JChipault** [comment]
works in 2.4.0
