### ISSUE TITLE
hover over updates

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#677]
1) "Diagnosis" at the top public section of the event details page should have the event diagnosis hover over text (currently has species diagnosis hover over text)
![image](https://user-images.githubusercontent.com/49287076/61966637-b64e8600-af98-11e9-9129-e5e8b8a8be9a.png)

2) "Locations" in the event details table at the top public section of the event details page could have same hover over as "Locations" on home page table (home page table has hover over text WIM wrote and it's good for the combo of information provided, but you won't find it in hover over table I sent).
![image](https://user-images.githubusercontent.com/49287076/61966663-c36b7500-af98-11e9-923b-6cb97eee02d4.png)

3) "Location" in the species details table at the top public section of the event details page needs to change from the "Location Name" hover over text to the same hover over as "Locations" on home page table.
![image](https://user-images.githubusercontent.com/49287076/61966733-ff063f00-af98-11e9-99f9-0359434990ec.png)

4) "Sick Estimate" in the species details table at the top public section of the event details page needs to change; it's currently set to the known dead text
![image](https://user-images.githubusercontent.com/49287076/61966740-03caf300-af99-11e9-9cd2-37719b0846e9.png)

5) missing hover over on event organization in "add event organization" subform in privileged event data
![image](https://user-images.githubusercontent.com/49287076/61966772-1513ff80-af99-11e9-8fd3-b4860b72f394.png)

6) missing hover over for species on "Add species to this location" subform in privileged event data
![image](https://user-images.githubusercontent.com/49287076/61966789-2bba5680-af99-11e9-94b3-06fdd9031836.png)

7) change hover overs on "add comment to event location" subform from the hover overs that apply to event comments to the hover overs that apply to location comments
![image](https://user-images.githubusercontent.com/49287076/61966864-6d4b0180-af99-11e9-8c9a-21a7c4f0cbd5.png)

8a) hover overs for location contacts aren't the same between the create event form and the event details page - use hover overs in create event form
![image](https://user-images.githubusercontent.com/49287076/61966946-b26f3380-af99-11e9-9270-98c3d7f17788.png)

8b) also add these hover overs to this section when on event details page and trying to "add new event location"
![image](https://user-images.githubusercontent.com/49287076/61967015-e3e7ff00-af99-11e9-8e72-0be46cf83408.png)

below are spelling errors on my part- sorry - I forgot Google Sheets doesn't spellcheck! Corrected in spreadsheet now (https://docs.google.com/spreadsheets/d/1Ioe48r2ge7I6FV0UP9wq4rqrfzANwh1eXfQB8YnFngE/edit#gid=0)
9) "Role" had a spelling error in organization
10) "County or equivalent" had a spelling error in borough
11) "Age Bias" had a spelling error in noticeable
12) "Sex Bias" had a spelling error in noticeable
13) "Collaborators - Add Circle" had a spelling error in management
14) "Flyway"had a spelling error in United States
15) "NWHC Carcass Submission Approval" had an extra "has"
16) "Email Address" on the registration form had a spelling error in resources
17) "Terms of Use" had a spelling error in acknowledging

**Comment by lprivette** [comment]
Thanks @JChipault !

Done in branch `677`.

**Comment by JChipault** [comment]
Looks great! Thanks! Only one small thing - regarding 8a, the hover over for "Add Contact" is missing a line of space that "Create New Contact" has.
