### ISSUE TITLE
hover overs for column headers in tables

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#681]
We like the "Location" hover over on the home page table (not having the question mark is nice in that it's less clutter). Can we add similar hover overs for other column headers in that table? Leave "Locations" as is but refer to "Hover Over Text for Edit Event and Data Tables (Public focused)" in hover over spreadsheet (https://docs.google.com/spreadsheets/d/1Ioe48r2ge7I6FV0UP9wq4rqrfzANwh1eXfQB8YnFngE/edit#gid=0) for other columns. 

Same applies to column headers on the dashboard tables.

**Comment by lprivette** [comment]
Done in branch `677`

**Comment by JChipault** [comment]
Would it be easy to add hover overs to the table column headers in "Events" and "Your Events" in dashboard?

**Comment by lprivette** [comment]
Yep! Just pass over the text and I'll add it

**Comment by JChipault** [comment]
Awesome. You can use the same text as the column headers on the home page. However, can we change the species hover over on all three tables (home page, events tab on dashboard, and your events tab on dashboard) to "Species affected in event."? Also, for Permission Source in the dashboard, use:

Your connection to this event. 

Options are: "user" - you created this event; "organization" - someone in your organization created this event; "collaborator" - you were invited to be a read or read/write collaborator on this event.

**Comment by JChipault** [comment]
Sorry.... change to Permission Source hover over:
Your connection to this event.

Options are: "user" - you created this event; "organization" - someone in your organization created this event; "collaborator" - you were invited to be a read or write collaborator on this event. If blank, then someone outside of your organization created this event and you have not been invited to be a collaborator.

**Comment by lprivette** [comment]
Done in branch `686`.

**Comment by BlakeDraper** [comment]
Merged in my local dev branch.
