### ISSUE TITLE
Error on saving edited event due to quality_check being undefined

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#684]
![image](https://user-images.githubusercontent.com/23640741/62314876-15613e80-b462-11e9-9043-cc20e96fd6fc.png)

It is failing on line 394 of the edit-event-component. formValue.quality_check is undefined 

**Steps to reproduce (I was logged in as WHISPers Tester)**: 
1. Navigate to an existing incomplete event
2. Click the "Edit Event" button
3. Enter a value for the "Event Reference" field.
4. Click "Save" and note the error in the console.

To fix I'll put a check in for `formValue.quality_check` being undefined

**Comment by lprivette** [comment]
Done in branch `685,684`

**Comment by BlakeDraper** [comment]
Merged in my local dev branch.
