### ISSUE TITLE
Add required asterisks on create event

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#686]
To try to make it easy for people to see the information that they need to add to create an event, can we add an asterisks in the following 3 spots:
1) to "Location Start Date" (I know it's only needed at one location, but I don't think it's worth adding extra text to the front end to indicate that. Users can guess a date and change it later. No need to change the already programmed business rules that only require one start date if there are multiple locations in an event.)
2) before this text "Text in at least one of the comment categories below is required. Please be as thorough as possible to aid interpretation of data and to potentially guide cause of death determination and management actions."
3) can we add text to the top of the "Species" tab that says "* A number in at least one of the sick or dead categories below is required for at least one species for at least one location."

**Comment by lprivette** [comment]
For #1 Just to be sure I understand correctly -- I'll add the "*" (and it will show with the start date on each event location) but the requirement that only one event location needs a start date will still be unchanged.

**Comment by JChipault** [comment]
you've got it. thanks.

**Comment by lprivette** [comment]
Done in branch `686`.

**Comment by BlakeDraper** [comment]
Merged in my local dev branch and also added to Add Event Location component.
