### ISSUE TITLE
sort events tab by most recent start date

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#687]
related to Django github ticket 270. Can we sort the "Events" tab on the dashboard with the most recent start date at the top so that it mirrors what is on the home page?

**Comment by lprivette** [comment]
Would you like "Your Events" on the the dashboard to be sorted that way as well? @JChipault

**Comment by lprivette** [comment]
I made the change to just the Events table on the dashboard in branch `687`.

**Comment by BlakeDraper** [comment]
Slight change to default sorting method, but issue is effectively merged.
