### ISSUE TITLE
wrong user name or password message

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#688]
message user gets when they enter the wrong password is the cryptic message below. Making this message to the user decipherable isn't a critical fix but would make for a better ux.

Error. Failed to login. Error message: Response with status: 403 Forbidden for URL: https://whispers.wim.usgs.gov/whispersservices/auth/

**Comment by lprivette** [comment]
Waiting for Blake's return before making any decisions on this issue.

**Comment by BlakeDraper** [comment]
Done in code.
