### ISSUE TITLE
Add warning to event location review for number affected having at least one value

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#689]
Created this ticket based on a comment in https://github.com/USGS-WiM/whispers/issues/674

> If the system is giving you this message at the location review: "An event must have a start date provided for at least one location" then logically something like this should also be on the location review pain: "An event must have a number affected (known sick, estimated sick, known dead, or estimated dead) for at least one species for at least one location." For these two warnings, I think it's fine to have the checkmark and the warning simultaneously at the location review tab, like it's working now for start date.

**Comment by lprivette** [comment]
Done in branch 689.

Blake - I also added the `Validators.min(0)` to the known sick, estimated sick, known dead, and estimated dead in the event submission form. I noticed that it was in the already implemented in the add-event-location component so thought I'd go ahead and add it.

**Comment by BlakeDraper** [comment]
Merged in local dev branch.
