### ISSUE TITLE
JSON error when trying to request new species

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#690]
Just tried to request a new species via the dashboard button labeled "request new species, organization, or diagnosis" and got the error below. I was on the LIVE site (v 2.0.0) when it first happened so I tried the test site (v2.3.0) and got same error.

Error. Species addition request not sent. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data

**Comment by lprivette** [comment]
I tested in Test and had the same error. The POST itself at whispersservices/species/request_new/ has a 404 status code.

**Comment by lprivette** [comment]
Aaron tracked this issue down to it being the WAF blocking it because the body is `text/plain` instead of JSON. He's sent an email to EROS asking them to allow it.

**Comment by lprivette** [comment]
Should be working in test and live now @JChipault
