### ISSUE TITLE
fields that you skip on accident getting highlighted in red

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#693]
since we've been working on asterisks and warning messages, figured I'd throw this one up here but it's lower priority.

Not every required field that you accidentally skip over gets highlighted in red when you scroll back to it.

Fields that DO NOT go red:
- event type - this one is tricky because you could fill in everything else that is required to start an event and get to the bottom and have the "save event" button greyed out and have no idea why. users get frustrated because they can't tell what field they've missed but i get that it's different than the fields in the location tabs in that there's not a clear indication when a user has moved on from this section of the form. thoughts on how to make this stick out to the user if they skip it and are trying to save an event?
- location comment - maybe just the text by the asterisks goes red?

**Comment by BlakeDraper** [comment]
Figured out a solution! Angular did not make this easy - basically have to focus the field and _then_ manually call the change detector to detect that change. Dumb, but it works.

```
 this.eventTypeRef.focus();
 this.cd.detectChanges();

```

Anyway, what that means @JChipault is the form will load with the Event Type field in 'focus' so when someone skips it, the red highlight will be triggered.  Done in code.
