### ISSUE TITLE
date and sick/dead number warnings in two places

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#694]
since we've been working on asterisks and warning messages, figured I'd throw this one up here but it's lower priority.

I like these messages at the location review step:
![image](https://user-images.githubusercontent.com/49287076/63378040-f108cb80-c356-11e9-941a-0c3548952ed3.png)

But not everyone clicks on that review tab so can we put both of them down by the save event button so that people see them there too. Right now, only one of those messages is by save event.
![image](https://user-images.githubusercontent.com/49287076/63378167-3c22de80-c357-11e9-8fa0-031f8ec98283.png)

**Comment by BlakeDraper** [comment]
Done in code.
