### ISSUE TITLE
flyway not populating

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#695]
There's no flyway listed for 200129 in the production site (https://whispers.wim.usgs.gov/event/200129) even though there's a state, county, and a lat/long

**Comment by JChipault** [comment]
ah, maybe this happened during the time when the FWS external site was down? perhaps we just manually add in flyway for any older events that are missing a Flyway via the backend table because they are populating now?

**Comment by JChipault** [comment]
@nbaertlein are you able to see which events are missing Flyway?

**Comment by nbaertlein** [comment]
Flyway assignment seems to be working fine.  Only 4 events are missing flyway (200070, 200124, 200129, 200136), who's locations were created between 7/10 and 7/18.  7 locations in total.  I will update these and let you know.

**Comment by nbaertlein** [comment]
@JChipault I added flyways for these 4 events.  Please verify on your end.  Applies to new events only (200000+).  Will have to discuss strategy to apply to legacy data.

**Comment by JChipault** [comment]
looks good now! thanks!
