### ISSUE TITLE
Add scroll to legend when in the top of screen orientation (wide screens)

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#697]

**Comment by lprivette** [comment]
This is actually already working in chrome, but not in firefox. Looking into it.

**Comment by lprivette** [comment]
Wasn't a firefox thing. I had the dev tools open which changed the size of the div and activated the overscroll. 

Done in branch 697.

**Comment by BlakeDraper** [comment]
done with v2.6.0
