### ISSUE TITLE
known and est business rules acting weird

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#702]
In test 2.4.2, I created an event with a species with 1 estimated dead (170773). I then went into event details and was able to make it 1 known dead and 1 estimated dead (which violates business rules). Then I tried to edit it to 1 known dead and nothing in the field for estimated dead and I got toast message  "Error. Species not updated. Error message: {"non_field_errors":["Estimated dead count must always be more than known dead count."]}" which is the error I should have gotten when I tried to make it 1 known and 1 estimated but just 1 known and nothing for estimated should be fine.

This happened on the live site too but I wanted to recreate it before reporting it.

**Comment by lprivette** [comment]
Started looking into this one. It's not displaying the error until you touch the "Estimated Dead" field.

It is getting into the estimatedDead AC and returning the error as it should without touching the "Estimated Dead" field. So I'm a little lost as to why it's not displaying that error until "Estimated Dead" is touched. Going to give my brain some time to reset and then come back to this.

**Comment by lprivette** [comment]
Done in branch `702`.

@BlakeDraper I didn't actually figure out why the validators are not working until the `dead_count_estimated` or `sick_count_estimated` fields were `touched`.

I fixed it by marking those fields as `touched` when the edit dialog is loaded. I also added the disabled attribute to the save button so that a user can only submit it if the form is valid.

**Comment by BlakeDraper** [comment]
Great fix Lauren. Merged locally.

**Comment by JChipault** [comment]
@lprivette Working pretty good! I did notice though that if you're adding a new species on the event details page (or entering the first species on the create event page) and you enter 1 known and 1 estimated, that it doesn't add the red text under the "estimated" field until after you click somewhere. Any way to get it to show you the red text right away? Otherwise, it's hard to know why the submit button is greyed out.
![image](https://user-images.githubusercontent.com/49287076/67240103-6277ff80-f416-11e9-8061-df3155fccf05.png)

**Comment by BlakeDraper** [comment]
I applied a fix, look for that in next release.
