### ISSUE TITLE
jumping to an event details url not working

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#709]
I used to be able to click on any event from the home page, and then when I got the event details page I would just change the last numbers on the url to be able to jump to the event I was really interested in. Since changed to whispers.usgs.gov, this sometimes doesn't work and I get a screen like this after I change the numbers at the end of an event details url.
![image](https://user-images.githubusercontent.com/49287076/65523971-a678f280-deb2-11e9-8750-8d1d654c3842.png)

**Comment by JChipault** [comment]
refreshing the page didn't help today. I had to go back to the home page and then I tried doing the same maneuver again (click on any home page event and then change url to 200112) and it worked this time.

**Comment by JChipault** [comment]
This might be user error... it happened again and I noticed that my url was invalid so perhaps I'm just typing in a 5 digit or 7 digit number and that's pushing me to this type of empty site. It used to be that if I typed a nonsensical url that I'd see text in black that said the event did not exists

**Comment by JChipault** [comment]
Happens also if I go to a 6 digit event that doesn't exist yet (e.g., 200500). Let's mark this as a usability thing... landing on this screen that looks broken doesn't feel like the best UX but most people will be clicking links instead of manually typing numbers into the url

**Comment by BlakeDraper** [comment]
This is a server config issue (EROS). But instead of trying to fight that fight on the heels on the last one, I made a small update to my code that should make that irrelevant.
