### ISSUE TITLE
grouped events - event details maps not updating

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#710]
200112 and 200130 are grouped events and if I'm on one and toggle to the other via the event link under "Associated Events" the data changes but the map does not.

![image](https://user-images.githubusercontent.com/49287076/65525384-0a9cb600-deb5-11e9-9ee7-aa60f4147e85.png)

![image](https://user-images.githubusercontent.com/49287076/65525417-17b9a500-deb5-11e9-9c51-ac3158f59523.png)

Same for toggling between 200123 and 200124

**Comment by BlakeDraper** [comment]
looks good. merged to my local dev branch.
