### ISSUE TITLE
can't add comment

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#715]
a partner user attempted to add the comment below to event 200203 at 10:30a today and got this error.

9/30/19: all carcasses removed from the area; all sick birds (cormorants) euthanized; follow up includes twice weekly surveillance and clean up of carcasses until cormorants migrate, probably within the next couple weeks; then weekly checks and removal until no more found

![image](https://user-images.githubusercontent.com/49287076/66065452-0869d580-e50d-11e9-8dbb-cea45687368c.png)

I tried to add it from my account closer to noon and got a slightly different error.
![image](https://user-images.githubusercontent.com/49287076/66065445-043db800-e50d-11e9-99ba-8869ce380bf9.png)

EROS issue again? Or maybe it doesn't like colons or semicolons?

**Comment by BlakeDraper** [comment]
@JChipault I just used this exact comment text and added that comment on that event, two times (I then deleted it, just to not confuse things). Are you still unable?

**Comment by JChipault** [comment]
I tried adding a diagnosis to this event and also got a JSON error. 
![image](https://user-images.githubusercontent.com/49287076/66066578-6a2b3f00-e50f-11e9-8746-9f4aaa5ffb77.png)

AND then I logged out of the API and was able to add the comment and the species diagnosis just fine.

I'll check back with the submitter and see if she's still getting an error

**Comment by JChipault** [comment]
@BlakeDraper partner user (nancy businga) still can't add comment. I tried it in edge (which looks like is what nancy is using) and still was able to add the comment. Does her error message give you an insight?

**Comment by BlakeDraper** [comment]
Does she continue to receive the bad character message? We expect any unicode character (any normal character you could enter with your keyboard) to be accepted. Maybe she is pasting in the text from somewhere that is introducing a strange character.

**Comment by JChipault** [comment]
To partner: "Do you continue to receive the bad character message? One thought is that maybe there's some strange character or formatting that we can't see that's lurking under the text.  Any normal character you could enter with your keyboard (e.g., colons and semicolons) should be accepted. 

I was able to copy what you put in the Word doc you sent via email and paste it into WHISPers and have it commit; could you try copying it right from that Word doc? Alternatively, copying into Notepad should remove any weird characters or formatting lurking."

From partner: "Yep, tried that: copied from the Word doc I sent you. Still getting the invalid character message. Attached.  I also just tried to type in  the word testing.  Same error message.  It doesn’t like me!"
![image](https://user-images.githubusercontent.com/49287076/66079145-1decf880-e529-11e9-9733-0f51175ccaae.png)

**Comment by aaronstephenson** [comment]
This should now be fixed. It was a bug in the permissions testing for Comments for user roles below Admin.

@JChipault could you have the user try again?

**Comment by JChipault** [comment]
she said she'd try again tomorrow

**Comment by JChipault** [comment]
@aaronstephenson external user says it works! Do not delete the "Whispers admin" comment that was inserted while we were testing this out because user entered a different comment to test it and now it's nice to keep the chronological.  Thanks!

**Comment by BlakeDraper** [comment]
Closing this as fixed by the backend updates.
