### ISSUE TITLE
can't submit new event

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#722]
Anne Ballmann got this message when trying to submit a new event on the production site.

![image](https://user-images.githubusercontent.com/49287076/66216506-35dc8d80-e68b-11e9-8832-0dffcf1f1f38.png)

I tried submitting the same event (though what I tried to submit might have been a bit different than what Anne tried to submit because I didn't look up all the id's for data she entered), and I got a slightly different error message

![image](https://user-images.githubusercontent.com/49287076/66216731-9a97e800-e68b-11e9-8a9e-3ffd6797e035.png)

here's Anne's JSON form data

Form Status: VALID

 {
  "event_reference": "",
  "event_type": "1",
  "complete": false,
  "public": true,
  "staff": "3",
  "event_status": "1",
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [],
  "new_service_request": {
    "request_type": 1,
    "new_comments": [
      {
        "comment": "4 euthanized green-winged teal (1 gun shot, 3 thoracic compression); frozen  "
      }
    ]
  },
  "new_event_diagnoses": [],
  "new_comments": [],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "Lake Broadview/Comanche Flat",
      "start_date": "2019-09-30",
      "end_date": null,
      "country": "30",
      "administrative_level_one": 29,
      "administrative_level_two": 1649,
      "latitude": "45.042839",
      "longitude": "-108.830481",
      "land_ownership": "2",
      "gnis_name": "Broadview Pond",
      "gnis_id": "805558",
      "site_description": "This wetland is sometimes dry, but it currently, due to the wet year it has been, covers probably 2,500 acres.  It has a transmission line running across it.  Past history of large scale (1000s) avian botulism die-off.",
      "history": "4 sick green-winged teal collected on 10/3/19 along Hwy 3 (5 miles SSE of Broadview). One euthanized by gun-shot, 3 euthanized by thoracic compression. Approx. 170 dead ducks, most of which have been dead for a while.  This is perhaps ¾ of a mile from the transmission lines.  Some duck hunters saw many dead ducks on September 28 out in the middle of this large wetland.  It seems likely that the dead birds will number in the thousands. ",
      "environmental_factors": "very wet fall, lots of standing water",
      "clinical_signs": "",
      "comment": "Wants advice on proper PPE and precautions for collection; recommendations for hunters on bird consumption since hunting season is open",
      "new_location_species": [
        {
          "species": 174,
          "population_count": null,
          "sick_count": 4,
          "dead_count": null,
          "sick_count_estimated": null,
          "dead_count_estimated": 170,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": []
        }
      ],
      "new_location_contacts": [
        {
          "contact": 1672,
          "contact_type": 1
        },
        {
          "contact": 5049,
          "contact_type": 2
        }
      ]
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": [],
  "quality_check": null
} 

Here's my JSON form data in case it's slightly different than Anne's
Form Status: VALID

 {
  "event_reference": "",
  "event_type": "1",
  "complete": false,
  "public": true,
  "staff": "3",
  "event_status": "1",
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [
    null
  ],
  "new_service_request": {
    "request_type": 1,
    "new_comments": [
      {
        "comment": "4 euthanized green-winged teal (1 gun shot, 3 thoracic compression); frozen "
      }
    ]
  },
  "new_event_diagnoses": [],
  "new_comments": [],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "Lake Broadview/Comanche Flat",
      "start_date": "2019-09-30",
      "end_date": null,
      "country": "30",
      "administrative_level_one": 29,
      "administrative_level_two": 1649,
      "latitude": null,
      "longitude": null,
      "land_ownership": "1",
      "gnis_name": "Broadview Pond",
      "gnis_id": "805558",
      "site_description": "This wetland is sometimes dry, but it currently, due to the wet year it has been, covers probably 2,500 acres.  It has a transmission line running across it.  Past history of large scale (1000s) avian botulism die-off.",
      "history": "4 sick green-winged teal collected on 10/3/19 along Hwy 3 (5 miles SSE of Broadview). One euthanized by gun-shot, 3 euthanized by thoracic compression. Approx. 170 dead ducks, most of which have been dead for a while.  This is perhaps ¾ of a mile from the transmission lines.  Some duck hunters saw many dead ducks on September 28 out in the middle of this large wetland.  It seems likely that the dead birds will number in the thousands.",
      "environmental_factors": "very wet fall, lots of standing water",
      "clinical_signs": "",
      "comment": "Wants advice on proper PPE and precautions for collection; recommendations for hunters on bird consumption since hunting season is open",
      "new_location_species": [
        {
          "species": 174,
          "population_count": null,
          "sick_count": 4,
          "dead_count": null,
          "sick_count_estimated": null,
          "dead_count_estimated": 170,
          "priority": null,
          "captive": false,
          "age_bias": null,
          "sex_bias": null,
          "new_species_diagnoses": []
        }
      ],
      "new_location_contacts": [
        {
          "contact": 1672,
          "contact_type": 1
        }
      ]
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": [],
  "quality_check": null
}

**Comment by aaronstephenson** [comment]
I tested both of those JSON docs in my local dev environment (which is the same version as prod) and they both succeeded. I'll look in the logs on the prod server to see if something different is happening there.

**Comment by JChipault** [comment]
thank you!

**Comment by aaronstephenson** [comment]
Oh, when did you and Anne encounter those errors? Before or after I pushed the latest bug fix this morning (9:20 AM)?

**Comment by JChipault** [comment]
both. Looks like Anne ran into problems around 8a. I tried it right before submitting this ticket

**Comment by JChipault** [comment]
Neil notes that 200214-200218 on the front end are all repeats... so looks like we're back at that situation wherein the user gets an error message and is told the event didn't submit but it actually did submit. we've run into this before

**Comment by aaronstephenson** [comment]
That particular situation, where there's an error but the event isn't deleted, should not be happening anymore. I wonder if people are just mashing the Save button.

**Comment by JChipault** [comment]
I did it myself and I watched over Anne's shoulder and she tried to submit and you click it and immediately get the popup toast message. We aren't clicking on it multiple times at once. We click once, get toast message, say "oh yea, we should grab a screen shot", click submit again, get toast message, grab screen shot.

**Comment by aaronstephenson** [comment]
OK.

It appears to be a data problem, not a code problem. I should have it figured out shortly.

**Comment by aaronstephenson** [comment]
Alright this should be fixed now. I tested it on the test server and it's working.

The problem was that the new 'Pending' value was not yet added to the servicerequestresponse table, and because the error was happening in the database and not in the web services, the parent objects were not getting deleted. I think I have a solution for that, though.

**Comment by JChipault** [comment]
thanks!

**Comment by aaronstephenson** [comment]
Ok, I put in a protection for this situation, we shouldn't see this happen any more.

**Comment by BlakeDraper** [comment]
I am closing this since it seems to be resolved, but reopen if necessary @JChipault .
