### ISSUE TITLE
Add User name and Org on Service Request view on event details page

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#725]
> would be good to see name and organization of the user who created the service request (i.e. who requested to submit a carcass?) on the event details page

**Comment by lprivette** [comment]
Looks like this is already completed? 

![image](https://user-images.githubusercontent.com/23640741/67590415-fc96bb00-f728-11e9-8848-8ceb2dfae16c.png)

**Comment by BlakeDraper** [comment]
@lprivette That is the name and org of the comment. We will need the backend to return the `created_by`, `created_by_string`, `created_by_first_name`, `created_by_last_name`, `created_by_organization`, `created_by_organization_string` for the service request record itself as part of the event details response.
