### ISSUE TITLE
Comment table sort not working properly

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#729]
Per Neils email

>  the column sorting feature doesn't seem to work consistently... can you play around with this on the front end to see if you can make sense of it? Maybe some things are sorting by id number instead of alphabetically?

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by JChipault** [comment]
still a bit confused by the sort of the "comment" column.... see screenshots from 170786... I was expecting alphabetical, but maybe there's some other logic at play? maybe capital letters are sorting separately?

![image](https://user-images.githubusercontent.com/49287076/68225215-b4438c80-ffb5-11e9-84c4-4ce6095a9e74.png)

![image](https://user-images.githubusercontent.com/49287076/68225242-c1f91200-ffb5-11e9-9b5c-4086d798aa71.png)

**Comment by lprivette** [comment]
@JChipault This is likely because the default sorting of characters is by their ascii number, and all capitals come before any lowecase in the ascii list.

I suggest that we disable sort on the 'comment' field. What does sorting alphabetically by comment tell the user in this scenario? It doesn't seem like it would aid in the story telling. What do you think?

**Comment by JChipault** [comment]
@lprivette removing the sort feature from the comment column works for me.

**Comment by lprivette** [comment]
Done in branch `729`.
