### ISSUE TITLE
Style issues with comments table

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#730]
From Neil's email:
> the "full" view displays funny on some computer screens, though works fine on others. There is a scroll bar (see below for scrolled left and scrolled right), but the background colors on the table aren't present in the two right-most columns
![image](https://user-images.githubusercontent.com/23640741/67125807-90b1d100-f1c3-11e9-8169-d42b105d5a2c.png)

**Comment by JChipault** [comment]
@lprivette this is still how I see comments, even now working with my laptop screen instead of my big screen at my office. Is this still on your to-fix list?

**Comment by lprivette** [comment]
@JChipault Mitch has just fixed this locally and it will go into the next release

**Comment by BlakeDraper** [comment]
Published in v2.14.0.

**Comment by JChipault** [comment]
@BlakeDraper and @lprivette This one seems to still be happening. Today is the first day I checked it and I saw this for event 170352 on v2.14.1 on Firefox:
 
![image](https://user-images.githubusercontent.com/49287076/78378354-73689780-7596-11ea-855e-8317c64f5270.png)

Looks good on edge and chrome though so if fixing on firefox not easy then we're probably fine: 
![image](https://user-images.githubusercontent.com/49287076/78378667-ec67ef00-7596-11ea-8b9c-1fe4c3f884a9.png)
