### ISSUE TITLE
order of text on natural resource mgt reg form and typo

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#732]
Can we move some text on the natural resource management professional registration form? Some people are not seeing the org and role fields and that is making getting people enrolled confusing. Let's move the disclaimer down below "(Optional) Provide any additonal comment or explanation for your request" and then the Terms of Use (with it's associated checkbox) below the Disclaimer.

(Also, in "(Optional) Provide any additonal comment or explanation for your request", I see that "additional" is spelled wrong. Can we update that?)

**Comment by JChipault** [comment]
is it tricky to move the terms of use down after the disclaimer? They have to click that checkbox before the "submit" button becomes active so I'm looking for that checkbox not to be so buried. But this is definitely an improvement if it's hard to switch the order of terms of use and disclaimer.

**Comment by lprivette** [comment]
Ah of course! How's this: 

![image](https://user-images.githubusercontent.com/23640741/67783991-75578900-fa41-11e9-87ad-b662cab88d7a.png)

**Comment by lprivette** [comment]
Done in Branch `732`

**Comment by JChipault** [comment]
@lprivette The Natural Resource Mgt Prof registration looks great but it seems we lost the Disclaimer text from the General User form. The NRMP reg should have both the Disclaimer AND the Terms of Use with checkbox, while the General User just gets the Disclaimer (no checkbox). Thanks!

**Comment by lprivette** [comment]
doh! Thanks for finding.

Done in branch `732_fix`
