### ISSUE TITLE
org list going off the screen to the left

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#733]
If this isn't an easy fix, we can skip it for now because this function works if you start it's use on a full view browser... But if you try to "create new contact" while your screen is condensed, the organization pick list goes off the screen to the left. 
![image](https://user-images.githubusercontent.com/49287076/67779694-ff4c2580-fa32-11e9-8b6f-18887ef793e2.png)

And if I expand to full view screen with the org list open, it still goes off to the left.
![image](https://user-images.githubusercontent.com/49287076/67780042-84cfd580-fa33-11e9-8feb-3128a39de4a5.png)

If I do "add contact" on the same condensed view, it centers the dropdown and I can see it fine so maybe there's some code for the "add contact" that could be applied to the "create new contact" to make the "create new contact" more functional?
![image](https://user-images.githubusercontent.com/49287076/67779843-3c181c80-fa33-11e9-925c-fcaa26f544f8.png)

**Comment by lprivette** [comment]
Done in branch `733`
