### ISSUE TITLE
light color text on buttons on test site

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#735]
Looks like we've had some changes in color schema for buttons on the test site and I wanted to see if it's possible to revert back to the bolder colors. Initially when I saw the "search" and "save search" and "export data" and "metadata" buttons greyed out (but still active) on the home page of the test site, I thought it was a bug, but then I looked at my dashboard and I see that the active button of "add" in the screen shot below is the available button, while "edit" and "delete" are truly greyed out and inactive. 
![image](https://user-images.githubusercontent.com/49287076/68221061-7131eb00-ffae-11e9-858f-5bd6127bc980.png)

We prefer the more drastic difference in text color that we used to have when the active buttons were bold blue (screen shot from live site with bold blue button).

![image](https://user-images.githubusercontent.com/49287076/68221163-a2aab680-ffae-11e9-8585-410c484a05d6.png)

**Comment by lprivette** [comment]
Fixed in release v2.8.0
