### ISSUE TITLE
Add Private icon to home page search results table, map popup and event details page

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#740]

**Comment by BlakeDraper** [comment]
Done and published in v2.9.0 to test

**Comment by nbaertlein** [comment]
@BlakeDraper   I'm not sure if this is the correct thread, but we seem to have an issue with the home page display of private events.  Our home page indicators for private events only show when logged in as an admin and not in a regular partner role (partner admin, partner manager, partner).  See below.  I think this was to be consistent regardless of role.  

This also impacts the reports.  See attached reports.  201546 and 201516 are private events

Logged in as an 'Admin' (user: nbaertlein) 
![image](https://user-images.githubusercontent.com/38669574/137040672-64c274d8-00c7-44af-887d-4b94dd7be1cf.png)

Logged in as a 'PartnerAdmin','PartnerManager', or 'Partner' (users: whisperstester, nwhcPartnerManager, nwhcPartnerUser)
![image](https://user-images.githubusercontent.com/38669574/137040724-37fccaad-276c-47a7-96ea-cd1a4db0c782.png)
[WHISPers_Search_Results_20211012 (2) admin.pdf](https://github.com/USGS-WiM/whispers/files/7333598/WHISPers_Search_Results_20211012.2.admin.pdf)
[WHISPers_Search_Results_20211012 (3) manager.pdf](https://github.com/USGS-WiM/whispers/files/7333599/WHISPers_Search_Results_20211012.3.manager.pdf)

**Comment by BlakeDraper** [comment]
This was addressed on the backend here: https://github.com/USGS-WiM/whispersservices/issues/521

**Comment by BlakeDraper** [comment]
@nbaertlein please confirm this looks good on the production app when you get a chance.

**Comment by nbaertlein** [comment]
All roles were tested on the production site and all looks good - private events highlighted in pink with eye icon in table and map pop-up.  thanks.
