### ISSUE TITLE
jchipault can't log in to test site

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#750]
When I tried to log into the test site to check v2.9.0 yesterday afternoon, I got a toast message that said: Error. Failed to login. Error message: Response with status: 0 for URL: null

I can log into the test API just fine. Neil can log into the test site under his log in just fine. Neil tried resetting the password for user name jchipault but that still didn't allow me to log into the test site in firefox and chrome; and neil tried logging in as jchipault on his computer on the test site with the reset password and also got the error message.

**Comment by BlakeDraper** [comment]
@JChipault  I applied a fix -  please do a hard refresh and try again. My apologies - we changed up a process recently and this was a casualty of that.

**Comment by JChipault** [comment]
@BlakeDraper that fixed it! thanks!
