### ISSUE TITLE
Assigned Epi field not working

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#751]
Report from epidemiologist on Friday - The 'Assigned NWHC Epidemiologist' field does not seem to be working this morning. When I click on it the field turns blue but no drop down menu drops and you can't type characters in the field.

I (Jenny) checked the test site this morning (Monday) and see the same thing on the create event and event details pages.

**Comment by BlakeDraper** [comment]
@JChipault on it. We actually discovered this anomaly on Wednesday and just have not gotten to the fix yet. But thanks for passing the report!
https://github.com/USGS-WiM/whispersservices_django/issues/322

**Comment by BlakeDraper** [comment]
Done with patch on backend repo Nov 27th
