### ISSUE TITLE
Add new hover tips

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#754]
See spreadsheet for new additions

**Comment by BlakeDraper** [comment]
Partially done in 2.10.0 release

**Comment by BlakeDraper** [comment]
Spoke to Jenny:

> ok, did a review, and the answer is "no" we don't need those other things on the front end. The advantage of putting them into the hover over table though is that we have all our fields explained in one spot so when we update things (e.g., we incorporate surveillance better during Effort 3) we can easily update the metadata on the reports as well

So the two added with release 2.10.0 are all we needed to add.

**Comment by BlakeDraper** [comment]
Published 2.10.0.
