### ISSUE TITLE
Prevent test data from populating google analytics

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#755]
To solve this, we'll first ask if they want to have a 'test' analytics. 

If no, then we'll see if we can pull that out into a config file and be read into index. Having no ID in the script does not appear to break anything. So in test environments the id would be ''. We'd release this into test and see if any weirdness happens.

If that no work, then we create a new property for test and put that in the config.

**Comment by BlakeDraper** [comment]
Discovered that absence of the gtag script block on index page causes gtag-dependent functions to fail.  Will reinsert the  block with empty string for UA ID for dev/test configurations.

**Comment by BlakeDraper** [comment]
Published with v2.11.2
