### ISSUE TITLE
Create color inverted whispers header image for use on printed reports

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#763]
Need to have black text instead of white on black field. It would be ideal to have a transparent background PNG with black letters. Here is current image in use (captured  from the WHISPers application header):

![logo](https://user-images.githubusercontent.com/6978380/71183317-6620da80-223d-11ea-9698-d633e86c3a65.png)

**Comment by BlakeDraper** [comment]
If needed, you can find the image file in the reports branch at: https://github.com/USGS-WiM/whispers/blob/reports/src/app/event-public-report/logo.png

**Comment by lprivette** [comment]
Thanks Mitch! Done.
