### ISSUE TITLE
Bulk upload: update the two buttons to point to a single page with instructions and guidance docs.

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#774]
Webpage link to be provided by NWHC.

**Comment by BlakeDraper** [comment]
@nbaertlein @JChipault Please provide web address of where those instructions and docs will reside.

**Comment by JChipault** [comment]
@BlakeDraper https://www.usgs.gov/centers/nwhc/science/whispers?qt-science_center_objects=0#qt-science_center_objects

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by BlakeDraper** [comment]
Released in v2.11.1

**Comment by BlakeDraper** [comment]
Confirmed functional by NWHC
