### ISSUE TITLE
Icons shifting on second consecutive summary report print

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#797]
**Steps to reproduce**:
With an active search that has results on the map:
1. Click "Generate Results Summary Report"
2. Click "Download Results Summary Report"
3. Note that the image is correct and displays all icons
4. Repeat steps 1 and 2
5. Note that the icons have shifted (see below image)

![image](https://user-images.githubusercontent.com/23640741/72382827-1a503c80-36e8-11ea-991f-2c03ca5a72d9.png)

**Comment by BlakeDraper** [comment]
Published in v2.12.2
