### ISSUE TITLE
User Notifications Setting Interface (Informational)

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#801]
Note this is just an informational issue to compile notes/instructions/thoughts for how to arrange the notifications settings interface. 

Preferences for the standard notifications (which are a thing every user has) are done via the `users` endpoint. Example below for notificationcuestandards but same shape/format of request. 

For the standard notification cues - each user needs to have each of the 4 types. 

1. Own
2. Org
3. Collborating
4. All

Instead of needing to look up the `notificationcuepreferences` record for each user via a query, client can simply PATCH directly to the `users` endpoint with the format below (sub-ing in the `users` endpoint) and the user ID

![image (5)](https://user-images.githubusercontent.com/6978380/72557572-a8eac800-3866-11ea-97aa-d3822ff4d8e1.png)
![image (6)](https://user-images.githubusercontent.com/6978380/72557601-b738e400-3866-11ea-90e6-8afe8ef7ae9e.png)

**Comment by BlakeDraper** [comment]
Spoke to Aaron and learned there was a miscommunication here - this can not yet be done via the `users` endpoint, only via `notificationcuestandards` as shown in the image. However, making this a feature of the `users` endpoint is a development priority for the api repository.

**Comment by BlakeDraper** [comment]
@aaronstephenson reports this as done, so we can proceed with building out on client. @lprivette I'll work on this for now.

**Comment by aaronstephenson** [comment]
![image](https://user-images.githubusercontent.com/8713712/72927668-4e48e480-3d1c-11ea-8067-faca520fb069.png)


Notes:

- No one, not even admins, can create notification preferences (they are automatically generated when a notification cue is created).
- Only admins or the creator or the creator's org admin can update notification preferences.
- Updating the preferences via the notification cue (as shown previously) still works.
- All notification preferences (standard and custom) are automatically deactivated when a user's `is_active` value is set to `False` (but not reactivated when `is_active` is set to `True`), and automatically deleted when a user is deleted.

**Comment by BlakeDraper** [comment]
@aaronstephenson Thanks for the update. A few questions:

1. what does the field `id` refer to in your request JSON body? Is that the standard_type or the actual `notificationcuestandards` record unique ID? If its the latter, there would need to be a way to query that per user, which is not ideal. Better if it is the standard_type ID because it can be matched to the user that way (every user has 1 of the 4 types, 1-4)
2. What do you mean when you talk about 'deactivated' and 'reactivated'? Are just talking about updating all the booleans to false?

**Comment by aaronstephenson** [comment]
1. That ID is for the standard cue record. It is now always included in every response from /users/, under "notification_cue_standards", as shown in the response to the example PATCH. I thought about using the standard type ID but it would require more work and I wanted to get something out to you. I can start working on that now, tho.
2. Yes. Deactivate and reactivate was just my shorter way of saying "setting all the preference booleans to False" and "setting all the preference booleans to True", since the trigger for both is when the user's account's `is_active` boolean value is changed. Not official terms, was just trying to save some typing.

**Comment by aaronstephenson** [comment]
OK, you can now made the updates using the `standard_type` field _or_ `id` (if both are submitted, `standard_type` will be used in the lookup) (I'm keeping `id` as a more natural option for API users).

![image](https://user-images.githubusercontent.com/8713712/72936624-3037b000-3d2d-11ea-94a0-0bcc4d360681.png)

**Comment by BlakeDraper** [comment]
This interface designed and released for testing.
