### ISSUE TITLE
Update initial dialog brought up by clicking 'Generate Search Results Report'

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/whispers#802]
comment from Jennifer: 

I like what Lauren did with this loading page for the event details report with regarding to replacing the header with information for the user as the process unfolds.

**Comment by lprivette** [comment]
I can do dis

**Comment by lprivette** [comment]
Done, but i'm unable to figure out why the progress bar behaves differently than the ones on the event report. It's much slower, despite the function being exactly the same.
