### ISSUE TITLE
Investigate issue with multiple runs of search not exporting a report the second time

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/whispers#805]
Comment from Jennifer:
similar to the event details report, if I run the same search twice in firefox it'll let me export it once but not a second time. If I try to export it a second time I just get the blue progress bar going forever

**Comment by lprivette** [comment]
doing this now

**Comment by lprivette** [comment]
actually back off this one for today. Firefox is borderline unusable on the network I'm on.

**Comment by lprivette** [comment]
This appears to be resolved with changes made to fix issue https://github.com/USGS-WiM/whispers/issues/828.

**Comment by BlakeDraper** [comment]
published with 2.12.1
