### ISSUE TITLE
summary results report: add scale bar and explanation to map

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/whispers#809]

**Comment by lprivette** [comment]
working on this one

**Comment by lprivette** [comment]
I've added the scale bar locally, but I feel that adding the legend will cover up too much of the pdf ready map.

Maybe make it an image on it's own? or add a custom legend using pdfmake/code?

**Comment by njestes** [comment]
yeah or maybe just put an image somewhere in the 'explanation of terms' appendix
