### ISSUE TITLE
map not loading on event details page

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#819]
Map doesn't load on some event detail pages. 200112 doesn't load a map for me on my work computer (neither firefox or chrome) nor on my home computer (chrome), though it did load on the conference room computer during our joint meeting. 
![image](https://user-images.githubusercontent.com/49287076/73014086-2ff7ed00-3ddf-11ea-8b8a-cfceb13cb8c7.png)

I checked other events that were grouped in case that was the issue (since 200112 is grouped), but the group that includes 200174 has maps that load.

.....
I left this ticket half written for an hour or two and just checked again and NOW 200112 loads a map relatively quickly on both firefox and chrome... did you already fix it?... or is just something with the internet connection/server that makes it spotty?

**Comment by JChipault** [comment]
this was an interesting one in the production site in firefox.... the event I had been looking at before was in MN and this event was in MI so not sure why I'm seeing part of CA. It stayed like this if I hit the back and forward buttons of my browser to toggle between the MN event and the MI event, but the map loaded correctly (to show MI) when I hit the refresh button on my browser. Worked in chrome. So maybe just an issue with firefox?
![image](https://user-images.githubusercontent.com/49287076/73193418-2678c880-40f0-11ea-8801-1950db3edd78.png)

**Comment by JChipault** [comment]
.... and later Boise....
![image](https://user-images.githubusercontent.com/49287076/73205852-67300c00-4107-11ea-8106-0d13d358873a.png)

**Comment by BlakeDraper** [comment]
Implemented a change that should fix this.

**Comment by BlakeDraper** [comment]
Published v2.13.4.
