### ISSUE TITLE
not all polygons fill in on event details map

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#820]
this happens sometimes. This polygon did not fill in around 10:15a this morning when we looked at this event together in the conference room and still the same polygon isn't filling in on chrome nor firefox at 1:45p.

![image](https://user-images.githubusercontent.com/49287076/73018669-ba444f00-3de7-11ea-9a22-f50bccccbd39.png)

**Comment by JChipault** [comment]
Oddly, 200106 does not fill in in firefox or chrome (single county) but that same county DOES fill in for it's associated events 200133 and 200135

**Comment by BlakeDraper** [comment]
Nick going to tackle this one for now.

**Comment by JChipault** [comment]
FYI - Neil has noted that the polygon doesn't fill in if there are 2 or more locations with the same county (i.e. shape)

**Comment by BlakeDraper** [comment]
Done with the fix for #1225.

**Comment by BlakeDraper** [comment]
Published in v2.16.10.
