### ISSUE TITLE
duplicate lab on first page

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#842]
When the same lab is listed multiple times at the species diagnosis level, can it only be listed once on the first page of the report?
![image](https://user-images.githubusercontent.com/49287076/73579367-d3807780-4447-11ea-863c-0e61e9af4d08.png)

**Comment by JChipault** [comment]
also, if there are two different labs, then it'd be good to use a semicolon to separate, in addition to starting a new line of text for subsequent labs.

**Comment by BlakeDraper** [comment]
@lprivette will just need to run a simple function to remove duplicates .

There is `checkDuplicateInObject()` in `app.utilities.ts` you could use or also  `checkForDuplicateDiagnosis()`on line 484 of `edit-species-diagnosis.component.ts` that could be copied and adapted.

**Comment by lprivette** [comment]
Done Locally

**Comment by BlakeDraper** [comment]
Published v2.2.3
