### ISSUE TITLE
Labels for maps?

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#844]
Can the labels for the two maps that are on the downloading eye candy subpage be put onto the report itself so that the two maps are labeled at the top with "Geographic Context" and "Counties (or equivalent) Affected"

**Comment by JChipault** [comment]
actually looks like just the "Counties (or equivalent) Affected" was in the original mock up so just that label is fine. It also kind of serves as the legend for this map so that you know why the polygons are the shape they are (county outlines)

**Comment by lprivette** [comment]
Done locally.

I added the label "Counties (or equivalent) Affected" to the details map.

**Comment by BlakeDraper** [comment]
Published v2.2.3
