### ISSUE TITLE
spacing in metadata

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#845]
There are more blank-line-spaces within a definition in the metadata on the event report than the search results report. I prefer the search results report style but mostly want it to be consistent. As an example, can the event report here:
![image](https://user-images.githubusercontent.com/49287076/73579852-49d1a980-4449-11ea-8ae5-e7fc986c94f1.png)
look like the search results report here, without the blank line between the definition of morbidity/mortality and surveillance:
![image](https://user-images.githubusercontent.com/49287076/73579970-a1701500-4449-11ea-8624-ef47875cb082.png)

**Comment by lprivette** [comment]
Done locally.

I hooked up summary report definitions to the source definition file `app.field-help-text.ts`. So it will be formatted like it is on the event report.

I also made the widths of the columns (word, definition) the same on both reports.

**Comment by JChipault** [comment]
thanks!!

**Comment by BlakeDraper** [comment]
Published v2.2.3
