### ISSUE TITLE
Longest Running Event Question

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#847]
When I ran a search for Oct 30-Jan 27 on Jan 27, I got event 170787 as the Longest Running Event on page 1 but when I look at the details, there are two events that have that same length (170787 and 170786), why aren't both listed on the first page?

**Comment by JChipault** [comment]
same for "Event with Most Affected"... if there's a tie, would I see both events?

**Comment by BlakeDraper** [comment]
@lprivette @njestes up to you guys who should tackle this one

**Comment by lprivette** [comment]
Fixed locally.

**Comment by BlakeDraper** [comment]
Published v2.2.3

**Comment by JChipault** [comment]
would it be possible to remove the excess space before the comma in the string of events? 
![image](https://user-images.githubusercontent.com/49287076/74067765-8fe5ba80-49bf-11ea-83e8-670a8629be4b.png)

**Comment by JChipault** [comment]
hmmmm... more importantly, links here take me to a website that is 403 forbidden. Though I guess that might not apply when we push this to the production site?

**Comment by BlakeDraper** [comment]
@JChipault that's correct. the test environment has an extra step in its path (related to having the separate notifications branch) which is making that link break. won't happen on production.

**Comment by JChipault** [comment]
sweet

**Comment by lprivette** [comment]
Fixing the affected text, and trying to figure out why that space is getting added

**Comment by lprivette** [comment]
Should I change the titles to 'Longest Running Event(s)' and 'Event(s) with Most Affected'? @JChipault

**Comment by JChipault** [comment]
Good thought but then we'd have to do "Most Frequent Event Diagnosis(es)" and that gets messy. Let's just leave it as singular.

**Comment by JChipault** [comment]
@lprivette shouldn't this report have two longest running? I'm in test 2.12.4 and 
![image](https://user-images.githubusercontent.com/49287076/74269760-9d58b880-4ccf-11ea-8828-b1381b723caf.png)
![image](https://user-images.githubusercontent.com/49287076/74269794-ae092e80-4ccf-11ea-9683-110274b09f4c.png)

**Comment by lprivette** [comment]
What was the search criteria so I can recreate @JChipault ?

**Comment by JChipault** [comment]
This: 
![image](https://user-images.githubusercontent.com/49287076/74276217-ed894800-4cda-11ea-9504-5b748023ef62.png) 
but when I just ran it again, it worked great!
![image](https://user-images.githubusercontent.com/49287076/74276260-fda12780-4cda-11ea-88ba-e06c6ce7cddc.png)

**Comment by lprivette** [comment]
Great! Sounds like it was caching issue.

**Comment by JChipault** [comment]
Just triple-checking the metadata and noticed that for "Most Frequent Event Diagnosis" we acknowledge that it could be a diagnosis or multiple diagnoses; so could we update the metadata to incorporate your idea above such that the metadata for "Event with Most Affected" says "WHISPers event(s) with...." and same for "Longest Running Event"?

**Comment by lprivette** [comment]
Yep, done locally.

**Comment by BlakeDraper** [comment]
done 2.13.2
