### ISSUE TITLE
map legend a little off

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#850]
Legend on report not as polished looking as legend on website. At the least, can we add some hard returns so that "Indicated by shape" and "Indicated by color" and "Multiple Events in One County (or equivalent)" are on their own lines?

**Comment by lprivette** [comment]
done locally

**Comment by BlakeDraper** [comment]
Published v2.12.3

**Comment by JChipault** [comment]
Looking better, but now missing the grey box at the bottom that explains multiple diagnoses

**Comment by lprivette** [comment]
@JChipault is this the grey box explaining multiple diagnoses or is it something else? 
![image](https://user-images.githubusercontent.com/23640741/74166298-56e25b80-4bf4-11ea-8913-ae71740a2cc8.png)

**Comment by JChipault** [comment]
yes, that one

**Comment by lprivette** [comment]
hmm. It is in there. I bet this is a screen size issue. The legend is a little long and getting cut off. I'll play around with the sizing.

**Comment by JChipault** [comment]
interesting. here's what i see 
![image](https://user-images.githubusercontent.com/49287076/74171202-c6a41680-4bf3-11ea-86c7-1639ef0b898a.png)

**Comment by JChipault** [comment]
maybe shift the whole legend up?

**Comment by lprivette** [comment]
I've moved the legend up in the dialog (which moves it up in the pdf) and removed the 'legend' text in order to maximize the amount of space available to the dialog when it's loading on smaller screens.

I also made font size smaller for the larger labels, and reduced some white space.

**Comment by JChipault** [comment]
@lprivette Now I see this, where the "Multiple Diagnosis Type" looks like a different font maybe? It's ok because it's at least all there but is there an easy way to make it look more like what people see on the homepage regarding font and font size?
![image](https://user-images.githubusercontent.com/49287076/74270074-40113700-4cd0-11ea-9ccc-bb7ca923f54a.png)
