### ISSUE TITLE
surveillance events in separate details table

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#857]
morbidity/mortality events should be in a separate details table from surveillance events as per https://doimspp.sharepoint.com/:p:/r/sites/GS-NWHCWHISPers/_layouts/15/Doc.aspx?sourcedoc=%7B4F249A27-BF9B-4121-886B-347B7A600FA0%7D&file=Search%20Results%20print%20out%20with%20comments.pptx&action=edit&mobileredirect=true

**Comment by lprivette** [comment]
Corrected locally.

I've set it up so that if there are no results for Morbidity/Mortality or surveillance an empty table won't show up on the report.

**Comment by JChipault** [comment]
thanks for making it so that there aren't empty tables!

**Comment by BlakeDraper** [comment]
Published v2.12.3
