### ISSUE TITLE
if multiple contact agencies

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#858]
Looks like there's use of grey text to distinguish between multiple contact agencies??? I'd suggest sticking with a similar convention that's used for county and using semicolons to separate.
Starting each new org on a new line might be good, in addition to the semicolon

**Comment by BlakeDraper** [comment]
Published v2.12.3

**Comment by JChipault** [comment]
semicolon should probably be added to first page of event detail report too, for consistency and clarity
![image](https://user-images.githubusercontent.com/49287076/74070942-0981a680-49c8-11ea-808c-6b299e4a12d0.png)

**Comment by lprivette** [comment]
fixed locally
