### ISSUE TITLE
separator between event diagnoses

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#859]
we need some sort of separator between event diagnoses. It'd be good to make whatever divider is used here (comma? semicolon?) the same as what is used on the event details report first page

![image](https://user-images.githubusercontent.com/49287076/73594607-729f8080-44d5-11ea-8d69-786972eb084f.png)

**Comment by lprivette** [comment]
Done locally.

**Comment by BlakeDraper** [comment]
Published v2.12.3

**Comment by JChipault** [comment]
still could use a semicolon on the first page of the event report.
