### ISSUE TITLE
Explanation of Terms pages

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#864]
On the event report, the text at the top is smaller than the definitions; whereas, on the search results report the text at the top appears bigger than the definitions. I prefer the definitions to be bigger (or have it all be the same font size), but mostly these reports should feel similar.

Also the footer for "Explanation of Terms cont..." is positioned differently between the two reports. I prefer it on the bottom like on the search results report but mostly it should be consistent between reports.

**Comment by lprivette** [comment]
Made explanation text and definitions the same size on both reports. Moved footer to bottom on events reports so that they are the same on both.

Done locally.

**Comment by BlakeDraper** [comment]
Published v2.12.3
