### ISSUE TITLE
page headers same size and right align

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#865]
Looks like there's some variation in font size in the headers (e.g., "Summary of Search Results" "Explanation of Terms") between the two reports. These should be consistent.

Also, would it be possible to right align the text headers (not the banner) so that it's always hits the upper right hand margin? The first couple of pages of the event report almost look like they are but then the explanation of terms header is farther left

**Comment by lprivette** [comment]
Made page headers and footers the same size in both reports. Right-aligned the header text.

done locally.

**Comment by BlakeDraper** [comment]
Published v2.12.3
