### ISSUE TITLE
JSON error when try to register

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#880]
We had a new staff member try to register on the live site as a Natural Resource Management Professional and he got this when he submitted:
![image](https://user-images.githubusercontent.com/49287076/74380756-cbadc500-4daf-11ea-973d-174816b211a0.png)

I tried it on the test site and initially got a cryptic error message similar (the same?) to what our new employee got, and then I hit submit again (to try to reproduce the error message in order to screen shot it) and got this: Error. User registration failed. Error message: {"username":["A user with that username already exists."],"email":["user with this email address already exists."]}

My second error message at least tells me what's wrong but my first error message was cryptic. I've noticed the warnings on the production site have been cryptic lately (e.g., I get a cryptic JSON error on the production page if I'm trying to add a comment and don't select a comment type; but if I do the same sequence of steps on the test page I'm told in plain language that I have to select a comment type)... not sure if there's just a general issue with the error messages not displaying in plain language, or if the registration flow shouldn't be showing an error message at all for our new employee.

**Comment by BlakeDraper** [comment]
Resolved with EROS WAF update
