### ISSUE TITLE
Report formatting issue

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#888]
Reports generated on the updated live site, v2.12.5, have some formatting issues. See attached.
[WHISPers_Search_Results_20200221.pdf](https://github.com/USGS-WiM/whispers/files/4236838/WHISPers_Search_Results_20200221.pdf)
[WHISPers_Event_200284_20200221.pdf](https://github.com/USGS-WiM/whispers/files/4236839/WHISPers_Event_200284_20200221.pdf)

**Comment by BlakeDraper** [comment]
@nbaertlein Fixed! sorry - it was one missing slash. Consequences of a 9pm deployment. Just hard refresh and you should be good.
