### ISSUE TITLE
Page load error

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#889]
Live v2.12.5 error.  
Can't jump to an event (neither firefox nor chrome) when entering a new event number in the url.  For example changing 'https://whispers.usgs.gov/home/event/200278' to 'https://whispers.usgs.gov/home/event/200284' yields the image below.

![image](https://user-images.githubusercontent.com/38669574/75050301-56b64b80-5491-11ea-96fa-8a5c555e2674.png)

**Comment by BlakeDraper** [comment]
@nbaertlein also fixed. same root cause as #888
