### ISSUE TITLE
Complete Event Details page to show all event details data

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispers#89]
In the 'privileged data' section (below the line), page should show
1) The event record details (already done)
2) Each event location and it's details within a collapsible panel (mat-expansion-panel)
      - Use the  already coded actionable species (locationspecies) table within each event location for that particular event location's array of location species
       - List the comments and their type
       - all this wrapped up in a *ngFor for the eventlocation in the event_details record that is already available on page load (in the variable `eventData`)

**Comment by njestes** [comment]
This is mostly done. If we want actionable tables for species at each event location, there is work to be done to dynamically supply selection models, paginators, and sorts to each table so they are distinct.

however, I'm having issue creating an event with multiple event locations at the moment. For the time being, I may just fake some data, so I can work through the coding for the actionable species tables.
