### ISSUE TITLE
Improve indicators for read/unread notifications

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#892]
Feel free to move this to deferred if it's not something we need to be thinking about right now.

**Undesired Design or Confusing behavior**:
The bold/unbold to indicate unread/read isn't obvious.

**If Possible, Describe a Solution**:
Unread messages would be bold and full color/ read messages would not be bold and duller colored. See screen shot for example.

I'm probably just too used to the read/unread indicators that gmail uses.

**Screenshots**:
![image](https://user-images.githubusercontent.com/23640741/75284773-6b714700-57e3-11ea-9f7f-70f24ea03b19.png)

**Comment by BlakeDraper** [comment]
I've lightened the text on read messages. Coloring the whole row will disrupt the alternating shading for readability it currently has - but let's see how this works and if not enough we can take that step.
![image](https://user-images.githubusercontent.com/6978380/75356838-16324580-5876-11ea-9ffc-4013949ff082.png)

**Comment by lprivette** [comment]
Ooo that helps a ton!

**Comment by BlakeDraper** [comment]
Done 2.13.1
