### ISSUE TITLE
Do not display badge if notifications == 0

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#893]
![image](https://user-images.githubusercontent.com/23640741/75285995-aaa09780-57e5-11ea-875b-6f36d1cf0816.png)

**Comment by BlakeDraper** [comment]
Done locally. Not only did I remove the badge when notifications length === 0, I also:

- Made the button go directly to the notifications area when there are none (no dropdown, so no 2nd click)
- added an icon

Some notifications:
![image](https://user-images.githubusercontent.com/6978380/75366792-e9d1f580-5884-11ea-96c4-abb7c11ca5c6.png)

No notifications:
![image](https://user-images.githubusercontent.com/6978380/75366966-2dc4fa80-5885-11ea-88d6-f4d1cc650722.png)

**Comment by BlakeDraper** [comment]
Done 2.13.1
