### ISSUE TITLE
Standard notifications, new and updated checked boxes not working for nwhcPartnerUser && wimPartnerUser

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#894]
**Describe the bug**
While logged in as nwhcPartnerUser and checking the boxes for new and updated under Standard Notifications, there is no toast notification and the state has not been saved upon refresh.

No errors in the console when checking the box. There is an existing error in the console on page load that may or may not be causing this.
![image](https://user-images.githubusercontent.com/23640741/75287442-5d71f500-57e8-11ea-8f6e-7278f43325f3.png)

**To Reproduce**
1. login as nwhcPartnerUser or wimPartnerUser
2. In menu bar, click on Notifications > See all notifications
3. Click on "Notification Preferences" to expand it
4. Check 'new' and or 'updated' 
5. Note that there is no toast and reload page.
6. Note that the checked boxes are not checked.

**Expected behavior**
When a box is checked there should be a toast notification and state should persist after page reload.

**Desktop (please complete the following information):**
 - OS [Win 10]
 - Browser [chrome]
 - Version [Version 80.0.3987.106 (Official Build) (64-bit)]
- On Network [Yes]

**Comment by BlakeDraper** [comment]
Ah yes. I know exactly why this is not working. Actually a data issue I forgot about. Those users (along with all users) need to have the 4 standard notifications type preferences (https://whispersdev.wim.usgs.gov/whispersservices/notificationcuestandards/). All new users get them automatically, but these user pre-date that logic so will need to be added manually. I'll get on that.

**Comment by BlakeDraper** [comment]
Done 2.13.1 (actually done in DB)
