### ISSUE TITLE
real-time notifications

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#900]
Here's a summary of what we're seeing with the real-time notifications in test 2.13.0. When I say "no alerts sent" I mean that we see no emails in inboxes nor do we see notifications within the application. We haven't tested the real-time notifications associated with setting up accounts yet. The rest fall into two categories.
1)
No alerts sent:
Request for new species, diagnosis, org
collaboration request 
service request 
service request response
service request response comments
add collaborator

2) 
Error message (and no alerts sent):
collaborator alert --> get this toast message after hit "issue alert": Error. Collaboration request response not submitted. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data. Blue loading bar at the bottom of the screen just goes on forever after toast message with error disappears. Nothing else happens.

high impact diagnosis --> get this toast message: Error. Species Diagnosis not created. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data  However, it did add the data. No alerts sent.

quality check --> get this toast message when try to set process status to Quality Check Needed: Error. Event not updated. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
However, it does seem to save the process status (i.e., it's set to "Quality Check Needed" if I click back into that subform and look at it again). No alerts sent.

**Comment by JChipault** [comment]
re-check of notifications that produced error messages...
collaborator alert --> same error
high impact diagnosis --> same error
quality check --> same error

**Comment by JChipault** [comment]
Request for new species, diagnosis, org --> working
collaboration request --> working
service request --> working
service request response --> working, but sending in duplicate
service request response comments --> working, but sending in duplicate
add collaborator --> working

**Comment by BlakeDraper** [comment]
Do believe this is addressed on backend but will proceed with testing.

**Comment by BlakeDraper** [comment]
@JChipault our testing has indicated that these issues are resolved and real-time notifications are behaving as expected. Do you agree with that, or are you still experiencing these problems?

**Comment by JChipault** [comment]
collaborator alert --> working now. Few tweaks: 
1) Can comment type be "collaborator alert"? (currently coming through as "other") 
2) Can the [ ] and '' be removed from around the name on this part of the long-form of the message I received: Alert sent to: ['Jenny Chipault']. 
3) can we get some of the language from the notifications table (pasted below) integrated into the interface under the comment box? Suggest: "Enter a comment to be saved to the event record. This comment will also be sent to the selected collaborators and overrides their WHISPers email notification settings to allow you to immediately email important communications.  Please use thoughtfully."
![image](https://user-images.githubusercontent.com/49287076/77769445-d9db3c00-7011-11ea-946d-7f8afb936458.png) 
4) the sort arrow in the collaborators column doesn't seem to do anything. if it's easier to remove than to fix, that's fine.
![image](https://user-images.githubusercontent.com/49287076/77769913-7d2c5100-7012-11ea-8146-5d7a58adc267.png)

**Comment by JChipault** [comment]
high impact diagnosis --> working, but sending in duplicate
![image](https://user-images.githubusercontent.com/49287076/77770152-d0060880-7012-11ea-87c3-cf4304e05133.png)

**Comment by JChipault** [comment]
quality check --> working

**Comment by JChipault** [comment]
service request response --> working, but sending in duplicate

probably because I'm both user who made the request and event owner? 

This scenario will likely happen quite often... any chance we could prevent it from sending two of the same emails to the same person? However, sometimes the event owner and the write collaborator making a service request could be different people.

![image](https://user-images.githubusercontent.com/49287076/77777462-9b4b7e80-701d-11ea-8b03-7b8786ee2991.png)

**Comment by JChipault** [comment]
service request response comments --> working, but getting a lot of emails (see github #342).

**Comment by BlakeDraper** [comment]
Closing this issue because the issues mentioned have been distributed among other issues across the two repos.

**Comment by BlakeDraper** [comment]
@JChipault Let's move any future problem with realtime notifications into individual issues.
