### ISSUE TITLE
API exposure of whispers_userchangerequest

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#902]
The table whispers_userchangerequest appears to be exposed in web API.  Probably shouldn't be.

**Comment by BlakeDraper** [comment]
To clarify, I think what you mean is it is exposed to non-authenticated users?

**Comment by aaronstephenson** [comment]
That's true, it does list all records.

We have a few options. I could restrict the visibility only to certain users, like NWHC admins or relevent org admins. Or I could not return any records at all, and only sent a response to POSTs and PUTs/PATCHes.

@BlakeDraper what do you need on the client from this?

**Comment by nbaertlein** [comment]
I would think admins (PartnerAdmin, Adminm & SuperAdmin) would need this.  Restriction for PartnerAdmin based on requesting org.

**Comment by BlakeDraper** [comment]
not currently hitting this endpoint at all. I would just restrict the response to NEHC admins and relevent org admins.

**Comment by aaronstephenson** [comment]
OK, restricted to admins (NWHC and relevant org admins) it is! Will make the change shortly.

**Comment by aaronstephenson** [comment]
This is now changed in the dev and test environments.
