### ISSUE TITLE
spacing in emails inconsistent

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#904]
Some of the emails have pretty big line spaces (e.g. user account assigned):
![image](https://user-images.githubusercontent.com/49287076/75591555-a4105b00-5a45-11ea-8e77-b484639c5022.png)

It looks like maybe two hard enters between paragraphs? Can we make those paragraphs a bit less spaced out?

Some (e.g., service request comment) look good regarding spacing:
![image](https://user-images.githubusercontent.com/49287076/75591657-e89bf680-5a45-11ea-940c-a9e2fbf5b9a4.png)

**Comment by aaronstephenson** [comment]
I'm _pretty_ sure I just used whatever Ali put in those HTML text files. But feel free to change the values yourselves, they're just in the whispers_notificationmessagetemplate table. Tom and Neil have access to directly to the database, so you can get access from either of them.

**Comment by BlakeDraper** [comment]
@nbaertlein This is a data issue.

**Comment by nbaertlein** [comment]
These will be addressed with event id link #905 fixes.

**Comment by nbaertlein** [comment]
@JChipault  I fixed the referenced text above.  Please help me identify any other messages that need to be addressed.  We can play with the html tags to get it right.  Thanks.
