### ISSUE TITLE
event numbers in emails should be links

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#905]
event numbers in emails need to be links (e.g., when I add someone as a collaborator, the email message says that there's a link, but there isn't):

You have been added as a [H] collaborator for WHISPers event [A] by [C] ([D]). 
Follow the event link provided to access privileged event information....

**Comment by aaronstephenson** [comment]
This wasn't included in the HTML text files Ali supplied. Please feel free to make whatever changes you like to those values in the whispers_notificationmessagetemplate table yourself.

**Comment by JChipault** [comment]
these event numbers are a dynamic variable so weren't in the html files.

**Comment by BlakeDraper** [comment]
@nbaertlein data issue

**Comment by nbaertlein** [comment]
Working on it.  All non-user permissions notifications (15 of 20) will need to be updated.

**Comment by nbaertlein** [comment]
@JChipault Text has been updated so links are active in emails.  Feel free to double check.
