### ISSUE TITLE
Test site diagnosis entry JSON error

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#914]
Adding a rabies species diagnosis through event details (event 170842) yielded JSON error below.  Data saved correctly, no notification sent for high impact disease.

Error. Species Diagnosis not created. Error message: SyntaxError: Unexpected token F in JSON at position 0

**Comment by aaronstephenson** [comment]
Ugh, sorry Neil. Blake discovered this bug yesterday on the dev server. The notification creation code is looking for a field named 'name' when it should be looking for 'username'. The fix is already in the repo, I just haven't deployed it to the test environment yet.

**Comment by aaronstephenson** [comment]
OK, this should be fixed now. Let us know how it goes.

**Comment by nbaertlein** [comment]
Looks good now.  Data saved and high impact notification sent.  No JSON error.
Thanks!
