### ISSUE TITLE
Close 'Request New Item' dialog on submit

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#915]
Just noticed that it didn't close after I submitted my request
![image](https://user-images.githubusercontent.com/23640741/76227843-4bd01a80-61f6-11ea-8b37-ef2ad9415aa6.png)

**Comment by BlakeDraper** [comment]
Good catch. I'll jump on this.

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by BlakeDraper** [comment]
Published with v2.13.3.
