### ISSUE TITLE
Sorting by message is not working

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#918]
no errors in the console.

![image](https://user-images.githubusercontent.com/23640741/76251746-f14ab480-621d-11ea-8b8d-bad6f1b82502.png)

**Comment by lprivette** [comment]
huh now it's working. Moving to "Deferred - In need of more info/evidence".

**Comment by lprivette** [comment]
actually it's just not working with a certain user. Investigating now

**Comment by lprivette** [comment]
well, now it's working again and I am unable to determine steps to reproduce the error. Moving back to Deferred.

**Comment by BlakeDraper** [comment]
There is something wonky happening with it.

**Comment by BlakeDraper** [comment]
Feexed her up. Done in code.

**Comment by BlakeDraper** [comment]
Published with v2.13.3.
