### ISSUE TITLE
Home map not loading after logging out from event details page

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#926]
**Describe the bug**
Error message is 'Invalid username/password'.

**To Reproduce**
1. Login to Whispers
2. Navigate to any event details page
3. Click the Log out button
4. Note that the home page map does not load

**Expected behavior**
Home page map should load

**Screenshots**
![image](https://user-images.githubusercontent.com/23640741/76456713-cd1ddd80-63ad-11ea-8a00-c1a39edf2b76.png)
____
![image](https://user-images.githubusercontent.com/23640741/76457189-b1670700-63ae-11ea-946a-fec748b47860.png)

**Additional context**
This is occurring because when the page is redirected and `queryEvents` function is ran the `this.isloggedIn` variable is still set to true.

**Comment by BlakeDraper** [comment]
Published v2.13.4.
