### ISSUE TITLE
update whispers url in FAQs

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#929]
The "How do I cite this information?" in the FAQs is errant since we've changed the url. 
Can you update the text below to include the correct urls?

Information presented on the WHISPers website is considered public information and may be distributed or copied. Use of the appropriate citation is requested. To direct readers to the entire WHISPers website, it is sufficient to give the address of the site in text: Retrieved [month, day, year], from the Wildlife Health Information Sharing Partnership event reporting system (http://www.nwhc.usgs.gov/whispers/). To cite data obtained from WHISPers, the following citation format is offered as a suggestion: Retrieved [month, day, year], from the Wildlife Health Information Sharing Partnership event reporting system on-line database, http://www.nwhc.usgs.gov/whispers/. Citations can be formatted to the style needed for your publication as long as there is sufficient information included to return the reader to the referenced information.

**Comment by BlakeDraper** [comment]
Done locally.

**Comment by BlakeDraper** [comment]
Published v2.13.4.
