### ISSUE TITLE
don't see notification preferences option

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#944]
when I arrive on the notifications dashboard tab, I cannot see that there is something to toggle open to set notifications. maybe use white space above the "date" and "source" columns to put in a button that would jump you down the page? Maybe 'Notification Preferences' button that would open the bottom and move focus there?
 
![image](https://user-images.githubusercontent.com/49287076/77461539-b70e1500-6dd0-11ea-90a5-d03d12c666c9.png)

**Comment by BlakeDraper** [comment]
@JChipault I know I have said before I wanted to avoid it, but I am giving the idea of another layer of tabs a shot. I think that may be better than adding another button to jump to an area down the page. Here is a preview of tabs within the Notifications tab. What you you think of this approach?

Notifications list tab:
![image](https://user-images.githubusercontent.com/6978380/77588627-3cb8c000-6eb8-11ea-9009-a47dcf12a6d6.png)

Notifications preferences tab:
![image](https://user-images.githubusercontent.com/6978380/77588668-4f32f980-6eb8-11ea-82b4-1638014ab1a5.png)

**Comment by JChipault** [comment]
That could work. I'll check in with the rest of the team here

**Comment by BlakeDraper** [comment]
@JChipault I have completed a bevy of tasks from your UI requests and bug reports this week. I am just about to ready to publish those as a release, but wanted to bump this issue back to the fore of your attention so that I might be able to include this change in that release (depending on your decision). If you all need more time to discuss, that is fine too.

**Comment by JChipault** [comment]
It's on the list to discuss on Monday. Neil is on leave today.

**Comment by JChipault** [comment]
We're happy with this tab system, but can the second tab be labeled "Manage Notification Settings"? And, just to be clear, we don't need any of the sort of sub-header language then that was on this old banner (no need for "Manage Standard Notifications, Add Custom Notifications or edit existing ones
Standard Notifications" text): 
![image](https://user-images.githubusercontent.com/49287076/77965779-618da880-72a7-11ea-88ab-48d4aa5d3b65.png)

**Comment by BlakeDraper** [comment]
Published v2.14.1.
