### ISSUE TITLE
change copy all species icon?

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#945]
Event Groups tab icon is the same as the icon used to copy all species to other locations... is there a different icon that would work for copy all species to other locations (like 2 stacked pages)? We like this "group_work" icon for event groups

![image](https://user-images.githubusercontent.com/49287076/77466495-5e427a80-6dd8-11ea-885f-86095be9b1e4.png)

![image](https://user-images.githubusercontent.com/49287076/77466554-72867780-6dd8-11ea-90b8-0d9253a9a7ce.png)

**Comment by JChipault** [comment]
It's also used for copy contact to other locations
![image](https://user-images.githubusercontent.com/49287076/77466681-98ac1780-6dd8-11ea-9846-9692eabbd12a.png)

**Comment by BlakeDraper** [comment]
I'll see what I can do. I mindfully used that icon knowing it was being used in the ways you show here. The Material icon library is somewhat limited.

**Comment by BlakeDraper** [comment]
@JChipault is this the kind of thing you want for copy to other locations?

![image](https://user-images.githubusercontent.com/6978380/77687471-71864f00-6f6c-11ea-869a-fc84eef7aaed.png)

**Comment by JChipault** [comment]
@nbaertlein is this the icon you were thinking of?

**Comment by JChipault** [comment]
I like it

**Comment by nbaertlein** [comment]
Yes

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by BlakeDraper** [comment]
Published in v2.14.0.
