### ISSUE TITLE
default to most recent notification on top

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#946]
When I navigate to the notifications listed in my dashboard, I expect to find the most recent at the top (default sort) but instead I see this:
![image](https://user-images.githubusercontent.com/49287076/77467010-2c7de380-6dd9-11ea-8c5f-2743a6220aee.png)

**Comment by BlakeDraper** [comment]
@aaronstephenson can you update the notifications response to sorted most recent first? More efficient than re-sorting them on load on the client, I think.

**Comment by aaronstephenson** [comment]
Can do.

**Comment by aaronstephenson** [comment]
Implemented in e374a48e

**Comment by JChipault** [comment]
@aaronstephenson looks like it's sorting unread separately?? Here's what I saw when I landed.
![image](https://user-images.githubusercontent.com/49287076/77539097-cc398100-6e6e-11ea-9c83-4654c2d8959d.png)

**Comment by JChipault** [comment]
though, it could be that there's something wonky about that 2/28 notification that's at the top of my list. See second half of ticket #949

**Comment by JChipault** [comment]
Played around some more.... in the above image, the only read message is the 2/28 new lookup request. If I mark another message as read, then they all resort and I get the expected presentation with the most recent on top.
![image](https://user-images.githubusercontent.com/49287076/77541522-c6459f00-6e72-11ea-8b19-2acc87c83858.png)
But then if I hit control-F5, both read messages float to the top.
![image](https://user-images.githubusercontent.com/49287076/77541669-f55c1080-6e72-11ea-8e80-141a9f6fcddc.png)

**Comment by BlakeDraper** [comment]
@JChipault I am working on issue #949 which will likely address most of what you are seeing.
