### ISSUE TITLE
sort notifications by date feature doesn't always work

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#947]
In chrome on 3/12, the sort by date arrow in the column header didn't work, then hours later worked fine, then 20 minutes later didn't work again. Kim has also had mixed results with this. Was working fine for Neil yesterday and works for me currently but putting it here so that we keep an eye on it. Here's what happens when it doesn't work
![image](https://user-images.githubusercontent.com/49287076/77467478-1290d080-6dda-11ea-98fb-825da2b65b66.png)

**Comment by BlakeDraper** [comment]
Done is code. See also #948.

**Comment by BlakeDraper** [comment]
Published in v2.14.0.
