### ISSUE TITLE
sort notifications by source not functioning as expected

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#948]
In chrome and firefox and on multiple different days (3/12 and today), when sorting by "source" it groups like-with-like, but not alphabetically

![image](https://user-images.githubusercontent.com/49287076/77467602-4835b980-6dda-11ea-883a-cf50cdbd70c6.png)

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by BlakeDraper** [comment]
This is fixed, along with #947. Do note that when sorting the message, you may see something like this:

![image](https://user-images.githubusercontent.com/6978380/77768958-3853ea80-7011-11ea-9bc0-955e478ddfee.png)

The quote `"` counts as a character for the alpha sorting, that is why the red arrowed line appears before the next line despite `Y` falling after `C` in the alphabet. Just a heads up.

**Comment by BlakeDraper** [comment]
Published in v2.14.0.

**Comment by JChipault** [comment]
I land here when I first arrive at notifications dashboard page:
![image](https://user-images.githubusercontent.com/49287076/78383622-4f10b900-759e-11ea-8cc2-19c3b01f26fb.png)

then sort by source and get this: 
![image](https://user-images.githubusercontent.com/49287076/78383692-6780d380-759e-11ea-8b04-22de64af9091.png)

Is there space or some other character at the beginning of KaitlinSGCI, test, and test2?
