### ISSUE TITLE
banner notifications flag

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#950]
When we see the number 2 in the red circle, we only expect 2 notifications in this dropdown. Can we make it show just the UNREAD notifications in the dropdown from the banner? And have most recent on top.

![image](https://user-images.githubusercontent.com/49287076/77474777-b3d15400-6de5-11ea-92ab-3332efdfe433.png)

**Comment by BlakeDraper** [comment]
Done in code. Also added an inter-component service that updates the notifications preview and unread badge in response to changes in the notifications table (which was not happening before).

**Comment by BlakeDraper** [comment]
Published in v2.14.0.
