### ISSUE TITLE
front end design of standard and custom notification settings

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#952]
I'm going to list a few things here that feel related to me but parse them out into separate tickets if that's easier.

1) The "Do not email" makes us think that clicking the box to the left of that clause means that we do not want an email. It's extra-confusing given the "click to receive emails for all" phrase in the column header, which kind of words things in the opposite way.
![image](https://user-images.githubusercontent.com/49287076/77554242-d2862800-6e83-11ea-9e59-1daaf84222b2.png)

We prefer the "on/off" button and something closer to the column header from our most recent mockup:  
![image](https://user-images.githubusercontent.com/49287076/77553216-84bcf000-6e82-11ea-8a86-6621bed772df.png)

Or maybe "on/off" with parenthetical "Email/Do Not Email"?

2) Also, lining up the on/off toggle under the column header of "Email me" would be good - they are a bit askew in the mockup.

3) And can we have the same apply-email-setting-to-all situation for custom notifications? We had it in our mockup but it doesn't seem to be a function on the test site. If someone has a lot of custom notifications then this apply-all feature is more important in the custom area than the standard area.

4) Can similar types of columns line up with each other vertically between the Standard and Custom notifications? As is, Custom Notifications columns are shifted to the left a bit. That's probably to accommodate "delete cue" but we think it'd be better to have some blank space to the right on the standard notifications. This will help users see that they have pretty much the same options for standard and custom. Also, the current "cue" column could use a bit more space.

5) Need a possessive apostrophe in "Your Organization's Events"

**Comment by JChipault** [comment]
the "do not email" toggle is also here
![image](https://user-images.githubusercontent.com/49287076/77559317-0b290000-6e8a-11ea-922f-54079cc55726.png)

**Comment by BlakeDraper** [comment]
1. I suggest fixing this by simply removing the "Do Not Email" text when the box is unchecked. It will only say "Email" when on. I think the checkbox is a better idea for consistency of the interface, over the on/off button. The mockup is just a starting point of layout concept.

2.  Without redesign from #1, this one is not relevant.

3. I'd like to add that to a future development list. Custom notifications are a very different animal than the standard ones, despite the settings here looking consistent. We would have to write more on both front and backend to make that work seamlessly and we are critically low on hours for Effort 2 right now. 

4. I'll see what we can do.

5. Should we just drop the "Your" for Org and Collab, which would both be more succinct make 'Organization Events' more grammatically correct? So: Organization Events and Collaboration Events?

**Comment by JChipault** [comment]
1. Fair enough. Curious about your vision for the column header in this scenario, especially for custom notifications if there won't be an email-all button. What we found when showing the early-on mockups to external partners is that they were confused about the distinction between within-app notifications and email notifications... they couldn't tell that this interface was allowing them to set both options. So we tried to make the email option pretty distinct in the later mock ups. You've probably got some good ideas for how to accomplish this.

5. I'd vote to just add the possessive because I think that text is more intuitive

**Comment by JChipault** [comment]
github relabeled my numbers (like they assumed I'd go in order or something!?)... 2 above is in reference to 5

**Comment by BlakeDraper** [comment]
Fixed item 4 in code.

**Comment by BlakeDraper** [comment]
Published in v2.14.0.
