### ISSUE TITLE
"Administrative Level One" translated

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#953]
"Administrative Level One" is listed as a cue... can we translate these table names to the things that people see on the front end (like has been done for Search)?

**Comment by BlakeDraper** [comment]
@JChipault Can you clarify what you mean? The Administrative Level One is translated, just not for other countries.

**Comment by JChipault** [comment]
When I look at my list of custom notifications I see this with "Administrative Level One":
![image](https://user-images.githubusercontent.com/49287076/77574190-abd5ea80-6e9f-11ea-87e6-1c8d27ca29ca.png)

Versus if I search by state, I see this with "State" which I like better:
![image](https://user-images.githubusercontent.com/49287076/77574374-e63f8780-6e9f-11ea-9cfc-aa810e89d5a9.png)

**Comment by BlakeDraper** [comment]
This was a data issue. The localities table was empty in the test DB. Fixed now.
