### ISSUE TITLE
can't select email if neither "new" nor "updated" selected

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#954]
shouldn't be able to have Email On if neither "new" nor "updated" selected because that will make the user think they'll get emails when they never will.

Clicking on email with nothing caused a looping error for Neil.

Can it grey out if neither are checked?

**Comment by BlakeDraper** [comment]
Done in code.

**Comment by BlakeDraper** [comment]
Published in v2.14.0.
