### ISSUE TITLE
email on or off for all

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#956]
Maybe this is by design but it didn't feel intuitive to me after I got used to what the check-all column header checkbox was doing to my notifications messages pane.....

If I click "Click to recieve emails for all" then all get selected... awesome
![image](https://user-images.githubusercontent.com/49287076/77560345-598ace80-6e8b-11ea-9ac2-92cacae645b9.png)

But then my intuition tells me to click that header checkbox again if I want them all unselected, but that doesn't happen. 
![image](https://user-images.githubusercontent.com/49287076/77560662-c0a88300-6e8b-11ea-9fbc-8303df44a5a9.png)

This might be more crucial if we can get this "email on or off for all" feature for custom notifications because if someone has a lot of custom cues set up and wants to turn email off for all of them it'd be great to do that in one click.

NOTE: I realized in copying it here that "recieve" is spelled wrong... if retaining that header language, change spelling.

**Comment by BlakeDraper** [comment]
It was design, but can be done the way you suggest. Done in code.

**Comment by BlakeDraper** [comment]
Published in v2.14.0.
