### ISSUE TITLE
footnotes in manage custom notification settings

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#975]
1) Since the * is used to indicate required fields elsewhere on this website, can we change the symbol by "All Events" to something else that directs the user's eye to the footer information? Here's what wikipedia suggests: https://en.wikipedia.org/wiki/Dagger_(typography)

2) To be consistent with standard notifications, can we add a double symbol (so if using the dagger then two daggers) by the "Delete" column header in the custom notifications to direct the user to read the footnote for the custom section?

![image](https://user-images.githubusercontent.com/49287076/77966603-f8a73000-72a8-11ea-82a0-bc9fd843a780.png)

**Comment by BlakeDraper** [comment]
Published v2.14.1.
