### ISSUE TITLE
event report not generating in test site

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#988]
I tried to generate an event details report from the test site in firefox and chrome. I just got stuck on this screen with the blue line running (so looked like it was processing but would just do that for forever. The search results report downloads just fine.

![image](https://user-images.githubusercontent.com/49287076/78814077-b3af8780-7993-11ea-8f2e-8bb2f975adaf.png)

**Comment by BlakeDraper** [comment]
Published w/v.2.14.3
