### ISSUE TITLE
captive field data wrong in report

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#989]
On the live site, if the website says "No" for captive, then the report says "Yes". However, if the website says "Yes" then the report also says "Yes" (appropriately)

![image](https://user-images.githubusercontent.com/49287076/78815358-c75bed80-7995-11ea-871d-b71b9280b34c.png)

![image](https://user-images.githubusercontent.com/49287076/78815407-da6ebd80-7995-11ea-830d-f572e42ee170.png)

**Comment by BlakeDraper** [comment]
@lprivette you able to look at this one too?

**Comment by lprivette** [comment]
yep will do

**Comment by JChipault** [comment]
still seeing the wrong data, even after a hard refresh... 
![image](https://user-images.githubusercontent.com/49287076/78838472-deadd180-79bb-11ea-98b0-dd04072c13f6.png)

![image](https://user-images.githubusercontent.com/49287076/78838515-f71dec00-79bb-11ea-941f-19ba23dd6047.png)

It probably wouldn't matter, but I'm logged in as the affiliateTest user

**Comment by lprivette** [comment]
@JChipault what's the event ID for that details page?

**Comment by JChipault** [comment]
170874

**Comment by BlakeDraper** [comment]
Published w/v.2.14.4
