### ISSUE TITLE
affiliate role not seeing notifications in banner

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#990]
An affiliate user reported that they did not see the bell symbol in the banner of the test site, but they do appropriately see notifications in their dashboard. I checked and looks like partneradmin, partnermanager, and partneruser all see the bell symbol in the banner even if they don't have any unread messages (or any messages at all):
![image](https://user-images.githubusercontent.com/49287076/78817012-23c00c80-7998-11ea-8c2a-f5ec32c53d8a.png)

So that's good.

But the affiliate sees this:
![image](https://user-images.githubusercontent.com/49287076/78817274-8dd8b180-7998-11ea-8d75-c0cc52e358a9.png)

**Comment by BlakeDraper** [comment]
This was done intentionally, but now changed locally.

**Comment by BlakeDraper** [comment]
Published w/v.2.14.3
